### ISSUE TITLE
Outdated dependencies in aptitude, ....

### ISSUE THREAD

**Issue by jonasdt** [coursera-dl/coursera-dl#139]
Installing the dependencies with aptitude, mac-ports, ... should not be encouraged because they install outdated versions. We should encourage people to use pip, which is nowadays the best way to install python dependencies. Likewise, we should encourage people to use virtualenv.

**Comment by programmin1** [comment]
I'm getting the same error even after sudo easy_install --upgrade requests, and  sudo pip install --upgrade requests

Why does it require requests >2.4?
Before upgrade it was giving weird error:
```
Downloading class: audio-001
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): accounts.coursera.org
Could not authenticate: Cannot login on accounts.coursera.org.
```
although it worked before - could this be a bug in earlier versions of the library?

**Comment by rbrito** [comment]
Hi, @programmin1.

I received a bug report of a user that told me that requests 2.2 didn't work for him, but when upgrading to 2.4, things worked: https://github.com/coursera-dl/coursera/issues/291

I put there the version that I know that works for me as the minimum (I also remember that, at the time, it wasn't the latest version).

Regarding login problems, are you using the most recent changes in the master branch? There was a major change in the way that authentication happens in coursera's side and you should have, at least, the following commit: https://github.com/coursera-dl/coursera/pull/305

Regards,

Rogério.

**Comment by deepaksuresh** [comment]
Hello Everyone!
I am running Linux Mint, and python 2.7.6. 
I've installed everything with pip, coursera-dl threw the following error while download was in progress.
`Traceback (most recent call last):
  File "/home/dpk/anaconda/bin/coursera-dl", line 7, in <module>
    from coursera.coursera_dl import main
  File "/home/dpk/anaconda/lib/python2.7/site-packages/coursera/coursera_dl.py", line 90, in <module>
    assert V(requests.__version__) >= V('2.4'), "Upgrade requests!" + _see_url
AssertionError: Upgrade requests! See https://github.com/coursera-dl/coursera/issues/139
`
I tried installing coursera-dl with python3, but the issue persists. My `pip six` is up to date.

Deepak

**Comment by henryxwong** [comment]
The error message directed me to here

> Henrys-iMac:Desktop henry$ coursera-dl 
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 85, in <module>
    assert V(six.__version__) >= V('1.5'), "Upgrade six!" + _SEE_URL
AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139
Henrys-iMac:Desktop henry$ pip install -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.1.3 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): html5lib>=1.0b2 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.4.3 in /Library/Python/2.7/site-packages/requests-2.9.1-py2.7.egg (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.0 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): keyring>=4.0 in /Library/Python/2.7/site-packages (from -r https://raw.githubusercontent.com/coursera-dl/coursera-dl/master/requirements.txt (line 7))
Henrys-iMac:Desktop henry$

**Comment by SuzanaK** [comment]
I was redirected to this issue in an error message from the script. The solution was for me (Linux Mint 17):

sudo pip uninstall coursera
sudo pip3 install coursera

**Comment by ilovejs** [comment]
sudo vim /Library/Python/2.7/site-packages/coursera/coursera_dl.py

comment out line 91, three assert statements.
