### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by enigne** [coursera-dl/coursera-dl#166]
When I type in the general download command like:
python coursera-dl -u myname -p mypsword 'matrix-001'

The following prompt appears:
Downloading class: matrix-001
Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/media/work/my_work/learn_by_Myself/coursera/coursera/coursera_dl.py", line 693, in main
    if download_class(args, class_name):
  File "/media/work/my_work/learn_by_Myself/coursera/coursera/coursera_dl.py", line 648, in download_class
    username=args.username, password=args.password
  File "/media/work/my_work/learn_by_Myself/coursera/coursera/cookies.py", line 324, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/media/work/my_work/learn_by_Myself/coursera/coursera/cookies.py", line 163, in get_authentication_cookies
    login(session, class_name, username, password)
  File "/media/work/my_work/learn_by_Myself/coursera/coursera/cookies.py", line 80, in login
    r = requests.get(class_url, allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 331, in send
requests.exceptions.SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib

I tried the same command on the other machine, it works fine. My OS is Ubuntu 12.04.2 and the program did work a few days ago. Please help me, thank you.

**Comment by thiagof** [comment]
+1 solving with python 3

install dependencies with `pip3`

**Comment by sakovias** [comment]
It's a great suggestion to use Python 3. With Python 2 on my Ubuntu 14.04 I was also getting the above error. I had modify installation instructions:

    cd /directory/where/I/want/my/courses
    virtualenv -p /usr/bin/python3 my-coursera # use Python 3
    cd my-coursera
    source bin/activate
    git clone https://github.com/coursera-dl/coursera
    cd coursera

Also, I've found that for newer courses where URL has the format `https://www.coursera.org/learn/course-name/` one has to use `--on-demand` command line option:

    ./coursera-dl -n --path /my/course/dir --on-demand course-name
