### ISSUE TITLE
ImportError: No module named six

### ISSUE THREAD

**Issue by firesofmay** [coursera-dl/coursera-dl#169]
I updated to the latest commit : 

```
commit 088f4b96af91ebcf9a25f56b7402bd37e0d69a7b
Author: Rog<C3><A9>rio Brito <rbrito@ime.usp.br>
Date:   Wed Jul 17 09:34:09 2013 -0300

    README: Add newer examples to avoid misleading people.

    We had more than one issue filed where people thought that they only had to
    specify the "base name" of the classes.

    While this was true during the inception of Coursera, their naming of the
    classes has changed during time and this makes the documentation clearer to
    match the post-initial naming.
```

Getting the following error (Using mac OSX 10.8.4)

```
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/Users/firesofmay/src/coursera/coursera/coursera_dl.py", line 53, in <module>
    from six import iteritems
ImportError: No module named six
```

**Comment by vigneshhere** [comment]
for windows?

**Comment by rbrito** [comment]
You people should be using the instructions that I gave in:

https://github.com/coursera-dl/coursera#install-any-missing-dependencies
