### ISSUE TITLE
Not able to download videos

### ISSUE THREAD

**Issue by rpolavar** [coursera-dl/coursera-dl#170]
Hi All:

I am facing a problem with the script for the last two days.  I have upgraded the script.  I have stopped calling coursera_dl.py.  Instead, as recommended, I am calling coursera-dl from the top directory.  Here is the error:
casebasedbiostat-001 
Downloading class: casebasedbiostat-001
Traceback (most recent call last):
  File "c:\z\coursera\coursera\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "c:\z\coursera\coursera\coursera\coursera_dl.py", line 693, in main
    if download_class(args, class_name):
  File "c:\z\coursera\coursera\coursera\coursera_dl.py", line 648, in download_class
    username=args.username, password=args.password
  File "c:\z\coursera\coursera\coursera\cookies.py", line 320, in get_cookies_for_class
    session.cookies.update(cookies)
  File "C:\Anaconda\lib\_abcoll.py", line 494, in update
    self[key] = other[key]
  File "C:\Anaconda\lib\site-packages\requests\cookies.py", line 241, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Anaconda\lib\site-packages\requests\cookies.py", line 282, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name=Cookie(version=0, name='csrf_token', value='Hsa8Q5jWGacAABdlDU8o', port=None, port_specified=False, domain='class.coursera.org', domain_specified=False, domain_initial_dot=False, path='/compmethods-003', path_specified=False, secure=False, expires=1378357039, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), domain=None, path=None"

**Comment by victorwestmann** [comment]
Is this issue fixed somehow? I have Windows as my main platofrm. Perhaps I can help.

**Comment by rbrito** [comment]
Thanks for the bug triage, Victor. I guess that the remaining bits of this bug (namely, downloading files with very long filenames under Windows) is already covered by other bug reports.

Thanks to everyone involved!
