### ISSUE TITLE
error downloading video files of a course

### ISSUE THREAD

**Issue by knoxxs** [coursera-dl/coursera-dl#222]
I have been trying to download the course **compilers-2012-002**.

You can see the output here:

```
~/coursera [master*]>> ./coursera-dl -u ******* -p ******* compilers-2012-002
Downloading class: compilers-2012-002
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): class.coursera.org
Starting new HTTPS connection (1): accounts.coursera.org
Logged in on accounts.coursera.org.
Found authentication cookies.
Downloaded https://class.coursera.org/compilers-2012-002/lecture/index (262831 bytes)
Introduction
  01-01-_Introduction
  01-02-_Structure_of_a_Compiler
  01-03-_The_Economy_of_Programming_Languages
The_Cool_Programming_Language
  02-01-_Cool_Overview
  02-02-_Cool_Example_II
  02-03-_Cool_Example_III
Lexical_Analysis
  03-01-_Lexical_Analysis
  03-02-_Lexical_Analysis_Examples
  03-03-_Regular_Languages
  03-04-_Formal_Languages
  03-05-_Lexical_Specifications
  DeduceIt_Demo
Finite_Automata
  04-01-_Lexical_Specification
  04-02-_Finite_Automata
  04-03-_Regular_Expressions_into_NFAs
  04-04-_NFA_to_DFA
  04-05-_Implementing_Finite_Automata
Parsing
  05-01-_Introduction_to_Parsing
  05-02-_Context_Free_Grammars
  05-03-_Derivations
  05-04-_Ambiguity
Top-Down_Parsing
  06-01-_Error_Handling
  06-02-_Abstract_Syntax_Trees
  06-03-_Recursive_Descent_Parsing
  06-04-_Recursive_Descent_Algorithm
  06-04-1-_Recursive_Descent_Limitations
  06-05-_Left_Recursion
Bottom-Up_Parsing_I
  07-01-_Predictive_Parsing
  07-02-_First_Sets
  07-03-_Follow_Sets
  07-04-_LL1_Parsing_Tables
  07-05-_Bottom-Up_Parsing
  07-06-_Shift-Reduce_Parsing
Bottom-Up_Parsing_II
  08-01-_Handles
  08-02-_Recognizing_Handles
  08-03-_Recognizing_Viable_Prefixes
  08-04-_Valid_Items
  08-05-_SLR_Parsing
  08-06-_SLR_Parsing_Example
  08-07-_SLR_Improvements
  08-08-_SLR_Examples
Semantic_Analysis_and_Type_Checking
  09-01-_Introduction_to_Semantic_Analysis
  09-02-_Scope
  09-03-_Symbol_Tables
  09-04-_Types
  09-05-_Type_Checking
  09-06-_Type_Environments
  09-07-_Subtyping
  09-08-_Typing_Methods
  09-09-_Implementing_Type_Checking
Cool_Type_Checking
  10-01-_Static_vs._Dynamic_Typing
  10-02-_Self_Type
  10-03-_Self_Type_Operations
  10-04-_Self_Type_Usage
  10-05-_Self_Type_Checking
  10-06-_Error_Recovery
Runtime_Organization
  11-01-_Runtime_Organization
  11-02-_Activations
  11-03-_Activation_Records
  11-04-_Globals_and_Heap
  11-05-_Alignment
  11-06-_Stack_Machines
Code_Generation
  12-01-_Introduction_to_Code_Generation
  12-02-_Code_Generation_I
  12-03-_Code_Generation_II
  12-04-_Code_Generation_Example
  12-05-_Temporaries
  12-06-_Object_Layout
Operational_Semantics
  13-01-_Semantics_Overview
  13-02-_Operational_Semantics
  13-03-_Cool_Semantics_I
  13-04-_Cool_Semantics_II
Local_Optimization
  14-01-_Intermediate_Code
  14-02-_Optimization_Overview
  14-03-_Local_Optimization
  14-04-_Peephole_Optimization
Global_Optimization
  15-01-_Dataflow_Analysis
  15-02-_Constant_Propagation
  15-03-_Analysis_of_Loops
  15-04-_Orderings
  15-05-_Liveness_Analysis
Register_Allocation
  16-01-_Register_Allocation
  16-02-_Graph_Coloring
  16-03-_Spilling
  16-04-_Managing_Caches
Garbage_Collection
  17-01-_Automatic_Memory_Management
  17-02-_Mark_and_Sweep
  17-03-_Stop_and_Copy
  17-04-_Conservative_Collection
  17-05-_Reference_Counting
Java
  18-01-_Java
  18-02-_Java_Arrays
  18-03-_Java_Exceptions
  18-04-_Java_Interfaces
  18-05-_Java_Coercions
  18-06-_Java_Threads
  18-07-_Other_Topics
Found 18 sections and 97 lectures on this page
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction_0_Cool_Manual_PDF.pdf
Downloading https://d2bk0s8yylvsxl.cloudfront.net/stanford-compilers/resources%2Fcool_manual.pdf -> compilers-2012-002/01_Introduction/01_01-01-_Introduction_0_Cool_Manual_PDF.pdf
Starting new HTTPS connection (1): d2bk0s8yylvsxl.cloudfront.net
[##################################################] 100%         220.94KB at 432.50KB/s
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction_1_Slides.pdf
Downloading https://d2bk0s8yylvsxl.cloudfront.net/stanford-compilers/slides%2F01-01-introduction.pdf -> compilers-2012-002/01_Introduction/01_01-01-_Introduction_1_Slides.pdf
[##################################################] 100%         231.43KB at 453.98KB/s
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction.pdf
Downloading https://d2bk0s8yylvsxl.cloudfront.net/stanford-compilers/slides%2F01-01-introduction-annotated.pdf -> compilers-2012-002/01_Introduction/01_01-01-_Introduction.pdf
[##################################################] 100%         904.47KB at 714.52KB/s
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction.mp4
Downloading https://class.coursera.org/compilers-2012-002/lecture/download.mp4?lecture_id=1 -> compilers-2012-002/01_Introduction/01_01-01-_Introduction.mp4
Starting new HTTPS connection (1): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 2 seconds ...
Starting new HTTPS connection (2): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 4 seconds ...
Starting new HTTPS connection (3): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 8 seconds ...
Starting new HTTPS connection (4): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 16 seconds ...
Starting new HTTPS connection (5): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 32 seconds ...
Skipping, can't download file ...
Forbidden 403
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction.txt
Downloading https://class.coursera.org/compilers-2012-002/lecture/subtitles?q=1_en&format=txt -> compilers-2012-002/01_Introduction/01_01-01-_Introduction.txt
[##################################################] 100%            7.07KB at 29.48KB/s
Downloading: compilers-2012-002/01_Introduction/01_01-01-_Introduction.srt
Downloading https://class.coursera.org/compilers-2012-002/lecture/subtitles?q=1_en&format=srt -> compilers-2012-002/01_Introduction/01_01-01-_Introduction.srt
[##################################################] 100%           10.31KB at 70.91KB/s
Downloading: compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler_0_Slides.pdf
Downloading https://d2bk0s8yylvsxl.cloudfront.net/stanford-compilers/slides%2F01-02-structure-of-a-compiler.pdf -> compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler_0_Slides.pdf
[##################################################] 100%         247.05KB at 354.04KB/s
Downloading: compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler.pdf
Downloading https://d2bk0s8yylvsxl.cloudfront.net/stanford-compilers/slides%2F01-02-structure-of-a-compiler-annotated.pdf -> compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler.pdf
[##################################################] 100%         953.17KB at 542.95KB/s
Downloading: compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler.mp4
Downloading https://class.coursera.org/compilers-2012-002/lecture/download.mp4?lecture_id=2 -> compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler.mp4
Starting new HTTPS connection (6): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 2 seconds ...
Starting new HTTPS connection (7): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 4 seconds ...
Starting new HTTPS connection (8): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 8 seconds ...
Starting new HTTPS connection (9): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 16 seconds ...
Starting new HTTPS connection (10): d28rh4a8wq0iu5.cloudfront.net
Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 32 seconds ...
^CKeyboard Interrupt -- Removing partial file: compilers-2012-002/01_Introduction/02_01-02-_Structure_of_a_Compiler.mp4
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/me/coursera/coursera/coursera_dl.py", line 769, in main
    if download_class(args, class_name):
  File "/home/me/coursera/coursera/coursera_dl.py", line 749, in download_class
    args.intact_fnames)
  File "/home/me/coursera/coursera/coursera_dl.py", line 393, in download_lectures
    downloader.download(url, lecfn)
  File "/home/me/coursera/coursera/downloaders.py", line 51, in download
    raise e
KeyboardInterrupt
~/coursera [master*]>>
```

**Comment by joeshaw** [comment]
Just ran into this same issue.  The cloudfront hostname they're using changed -- d2bk0s8yylvsxl.cloudfront.net works but the one linked in the page (d28rh4a8wq0iu5.cloudfront.net) doesn't.

I was searching around to see if there was an easy way to override this, but found this and just downloaded compilers-003 instead.  Thanks!
