### ISSUE TITLE
setup.py requires 'README.rst'

### ISSUE THREAD

**Issue by thedewster74** [coursera-dl/coursera-dl#354]
running setup.py throws the following error:

C:\Tools\coursera-dl>setup.py
Traceback (most recent call last):
  File "C:\Tools\coursera-dl\setup.py", line 26, in <module>
    long_description=open('README.rst', 'r').read(),
IOError: [Errno 2] No such file or directory: 'README.rst'

Looks like it wants a readme file.

**Comment by rbrito** [comment]
Hi.

Are you trying to use setup.py from a git clone or from the package distributed from pypi? The rst file is generated from the markdown file via pandoc when I release/upload things to pypi.


On May 9, 2015 7:36:19 AM GMT-03:00, thedewster74 <notifications@github.com> wrote:
>running setup.py throws the following error:
>
>C:\Tools\coursera-dl>setup.py
>Traceback (most recent call last):
>  File "C:\Tools\coursera-dl\setup.py", line 26, in <module>
>    long_description=open('README.rst', 'r').read(),
>IOError: [Errno 2] No such file or directory: 'README.rst'
>
>Looks like it wants a readme file.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/coursera-dl/coursera/issues/354

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rbrito** [comment]
Ping.

**Comment by amsourav** [comment]
I am also having the same problem. And yes it happens only when installing from git clone.

**Comment by rbrito** [comment]
Hi.

This should be fixed with the current git revision, provided that you have pandoc installed to generate README.rst (which is needed for uploads to PyPI).  As far as I know, PyPI doesn't seem to accept Markdown formatted documents, which is a pain for me.

If any of you know if it started accepting markdown documents, then I'd be glad to remove a lot of the useless code that I put into it to convert the files.

Thanks,

Rogério Brito.

**Comment by spl** [comment]
I believe the installation error I'm seeing is related to this issue:

```
$ pip install --pre coursera
Collecting coursera
  Using cached coursera-0.1.0a2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/w5/3q_d5d7s0gvgtf6rrnd94ydw0000gn/T/pip-build-pIbik5/coursera/setup.py", line 53, in <module>
        generate_readme_rst()
      File "/private/var/folders/w5/3q_d5d7s0gvgtf6rrnd94ydw0000gn/T/pip-build-pIbik5/coursera/setup.py", line 33, in generate_readme_rst
        subprocess.call(pandoc_cmd)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
```

**Comment by spl** [comment]
0.1.0a1 has the same issue:

```
$ pip install --pre coursera==0.1.0a1
Collecting coursera==0.1.0a1
  Downloading coursera-0.1.0a1.tar.gz (48kB)
    100% |████████████████████████████████| 49kB 26kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/w5/3q_d5d7s0gvgtf6rrnd94ydw0000gn/T/pip-build-oGhL7e/coursera/setup.py", line 53, in <module>
        generate_readme_rst()
      File "/private/var/folders/w5/3q_d5d7s0gvgtf6rrnd94ydw0000gn/T/pip-build-oGhL7e/coursera/setup.py", line 33, in generate_readme_rst
        subprocess.call(pandoc_cmd)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
```

**Comment by rbrito** [comment]
@spl, ouch! That's a brown paper bag issue. A million thanks for testing this! I will fix it and push an update ASAP.

**Comment by spl** [comment]
Success. :+1:

```
$ pip install --pre -U coursera
Collecting coursera
  Downloading coursera-0.1.0a3.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 100kB/s
Requirement already up-to-date: beautifulsoup4>=4.1.3 in /usr/local/lib/python2.7/site-packages (from coursera)
Requirement already up-to-date: html5lib>=1.0b2 in /usr/local/lib/python2.7/site-packages (from coursera)
Requirement already up-to-date: requests>=2.4.3 in /usr/local/lib/python2.7/site-packages (from coursera)
Requirement already up-to-date: six>=1.5.0 in /usr/local/lib/python2.7/site-packages (from coursera)
Requirement already up-to-date: urllib3>=1.10 in /usr/local/lib/python2.7/site-packages (from coursera)
Requirement already up-to-date: pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from coursera)
Collecting keyring>=4.0 (from coursera)
  Downloading keyring-5.4.tar.gz (68kB)
    100% |████████████████████████████████| 69kB 65kB/s
Installing collected packages: keyring, coursera
  Running setup.py install for keyring
  Found existing installation: coursera 0.0.3
    Uninstalling coursera-0.0.3:
      Successfully uninstalled coursera-0.0.3
  Running setup.py install for coursera
Successfully installed coursera-0.1.0a3 keyring-5.4
```
