### ISSUE TITLE
runtime error 

### ISSUE THREAD

**Issue by Archer-Hidden** [coursera-dl/coursera-dl#376]
just got the latest version from pip 

when i tried to download something i got this:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/courseradownloader/courseradownloader.py", line 98
    print "Invalid week filter, should be a comma separated list of integers", e
       

input command is :courser-dl -u xxxx -p xxxxx datascitoolbox-022

**Comment by mxamin** [comment]
I think you're using a different application, try:
`pip install coursera`

**Comment by PeterHuang2015** [comment]
or sudo pip install coursera

**Comment by rbrito** [comment]
Hi, @Archer-Hidden.

As @mxamin and @PeterHuang2015 told you already, your problem is due to a different program that (unfortunately) has the same name as ours. In addition to what they say, to avoid future problems, please, before using

```
pip install coursera
```

Please try to uninstall your previous program (possibly with `pip uninstall coursera-dl`).

I'm closing this issue, but please feel free to experiment our program and feel free also to contribute to our documentation (our README file), to prevent people from having the same difficulties.

Thanks,

Rogério.
