### ISSUE TITLE
Download error : Exceeded 30 redirects.

### ISSUE THREAD

**Issue by olemis** [coursera-dl/coursera-dl#410]
I'm downloading on demand courses . I often succeed but seldom I get `Exceeded 30 redirects` errors with particular course IDs e.g. `swiftprogramming` , `datasci` .

```
# coursera-dl -u USER -p PASS --on-demand datasci
Downloading class: datasci
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Traceback (most recent call last):
  File "/path/to/env/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.0.3', 'console_scripts', 'coursera-dl')()
  File "/path/to/env/lib/python2.7/site-packages/coursera/coursera_dl.py", line 942, in main
    result = download_on_demand_class(args, class_name)
  File "/path/to/env/lib/python2.7/site-packages/coursera/coursera_dl.py", line 888, in download_on_demand_class
    page = get_on_demand_syllabus(session, class_name)
  File "/path/to/env/lib/python2.7/site-packages/coursera/coursera_dl.py", line 214, in get_on_demand_syllabus
    page = get_page(session, url)
  File "/path/to/env/lib/python2.7/site-packages/coursera/coursera_dl.py", line 141, in get_page
    r = session.get(url)
  File "/path/to/env/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/path/to/env/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/path/to/env/lib/python2.7/site-packages/requests/sessions.py", line 594, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/path/to/env/lib/python2.7/site-packages/requests/sessions.py", line 114, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by rbrito** [comment]
Hi.

On Sep 16 2015, Olemis Lang wrote:
> I'm downloading on demand courses . I often succeed but seldom I get
> `Exceeded 30 redirects` errors with particular course IDs
> e.g. `swiftprogramming` , `datasci` .

Strange, since I was a beta-tester of datasci (see [my twitter post][0]) and
it worked perfectly fine with me.

[0]: https://twitter.com/rtdbrito/status/639187291001462784

I'm not enrolled in the course right now (it seems that Coursera
automatically "unenrolled" me from the course---as the beta-test period was
over), which means that I'm not able to test it right now (and I'm quite
busy, since I'm taking about 5 courses right now, with some more coming).

I may test later, though, if the problem persists. In the mean time, I
suppose that the best action would be to upgrade all the modules on which we
depend *and* to upgrade your version of coursera-dl with:

    pip install --upgrade --pre coursera

(note the lack of `-dl` when issuing the pip command).


Regards,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by olemis** [comment]
Since the beginning I've been using latest version of `coursera` PyPI package . Both of them seem to be working now, so I guess it was kind of a temporary outage due to course setup (or something alike) .

For the record , if users notice this issue then just wait a few days and retry . Feel free to reopen this ticket if the problem persists .

--
Regards

**Comment by rbrito** [comment]
Thanks for the confirmation, @olemis.
