### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hxhxd** [coursera-dl/coursera-dl#423]
```shell
Traceback (most recent call last):
  File "/home/pierre/.local/bin/coursera-dl", line 7, in <module>
    from courseradownloader.courseradownloader import main
  File "/home/pierre/.local/lib/python3.4/site-packages/courseradownloader/courseradownloader.py", line 98
    print "Invalid week filter, should be a comma separated list of integers", e
                                                                            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by hxhxd** [comment]
insatlled with pip insatll --user coursera-dl
Python 3.4.3
pip 7.1.2 from /usr/local/lib/python3.4/site-packages (python 3.4)
9.3-RELEASE-p10 FreeBSD

Thanks.

**Comment by outrofelipe** [comment]
I had the same problem, I followed the instructions on the follow issue https://github.com/coursera-dl/coursera-dl/issues/424, works for me.

**Comment by hxhxd** [comment]
@outrofelipe 
Thanks :)
