### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by chashmeetsingh** [coursera-dl/coursera-dl#426]
Starting new HTTPS connection (1): class.coursera.org
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
404 Client Error: Not Found for url: https://class.coursera.org/ruby-on-rails
Starting new HTTPS connection (1): www.coursera.org
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/cashrulz/Desktop/coursera-dl/coursera/coursera_dl.py", line 1111, in main
    if download_class(args, class_name):
  File "/home/cashrulz/Desktop/coursera-dl/coursera/coursera_dl.py", line 1089, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/cashrulz/Desktop/coursera-dl/coursera/coursera_dl.py", line 1028, in download_on_demand_class
    login(session, args.username, args.password)
  File "/home/cashrulz/Desktop/coursera-dl/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

**Comment by balta2ar** [comment]
Please search through the older issues (both open and closed) to find a solution. This issue has been reported numerous times already.
