### ISSUE TITLE
Problem installing dependencies: URL Error

### ISSUE THREAD

**Issue by auz107** [coursera-dl/coursera-dl#431]
I get the following error when trying to install the dependencies:

FesenjoonAZ:coursera-master auz107$ pip install -r requirements.txt
Downloading/unpacking argparse==1.2.1 (from -r requirements.txt (line 1))
  Error <urlopen error [Errno 1] _ssl.c:504: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm> while getting https://pypi.python.org/packages/source/a/argparse/argparse-1.2.1.tar.gz#md5=2fbef8cb61e506c706957ab6e135840c (from https://pypi.python.org/simple/argparse/)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "//anaconda/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "//anaconda/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "//anaconda/lib/python2.7/site-packages/pip/download.py", line 602, in unpack_http_url
    resp = _get_response_from_url(target_url, link)
  File "//anaconda/lib/python2.7/site-packages/pip/download.py", line 638, in _get_response_from_url
    resp = urlopen(target_url)
  File "//anaconda/lib/python2.7/site-packages/pip/download.py", line 176, in __call__
    response = self.get_opener(scheme=scheme).open(url)
  File "//anaconda/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "//anaconda/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "//anaconda/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "//anaconda/lib/python2.7/site-packages/pip/download.py", line 155, in https_open
    return self.do_open(self.specialized_conn_class, req)
  File "//anaconda/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 1] _ssl.c:504: error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm>

Storing complete log in /Users/auz107/.pip/pip.log

ANSWER TO GENERAL QEUSTIONS
Is the problem happening with the latest version of the script?
> Yes, I just downloaded it from GitHub

What operating system are you using?
> MAC OSX 10.11.2

My version of python is: 2.7.5

**Comment by auz107** [comment]
Problem was resolved by upgrading python
