### ISSUE TITLE
IOError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by BadWindshield** [coursera-dl/coursera-dl#444]
When I tried to run coursera-dl in Ubuntu (as a guest OS in VirtualBox) for this class

https://www.coursera.org/learn/regression-models/home/welcome

I got

```
Starting new HTTPS connection (1): eventing.coursera.org
Starting new HTTPS connection (1): github.com
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/williamw/coursera/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/home/williamw/coursera/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/williamw/coursera/coursera/coursera_dl.py", line 1015, in download_on_demand_class
    args.resume
  File "/home/williamw/coursera/coursera/coursera_dl.py", line 528, in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "/home/williamw/coursera/coursera/downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "/home/williamw/coursera/coursera/downloaders.py", line 366, in _start_download
    f = open(filename, 'ab') if resume else open(filename, 'wb')
IOError: [Errno 36] File name too long: u'regression-models/01_week-1-least-squares-and-linear-regression/01_introduction/01_welcome-to-regression-models_Kbp848YCgjxdpeGihUcxr4_PL8JM5tJxrEVr91e09B5KidCoGXWxe8c2AEKCoEXbBAaW4JMUUXI0R-KgvzNd7g.JywEThkg4eCE-iu2MYP7iw.u4f02fpu8cveioeaveh3pytdntarjbyzyhigjfodbxsywgvqb0rd-dhdgbcygy3zs-tn62p7m08wdsmxoq7n1vm-hxv5uf4gft-i8n_pbbvfqe4bjjnlqj5eek8cuxbhqc8pesyaeijrgmyf3lxvzhpq-ut2ipxkzgr1bxwtpzieja8wnnfsxkz46fhpt1cuqqxktkhcolibotm2j5derfgsluulj92-hui4hwyjt6hat5hyl5w6dzzv2aifotsbp_l9kcefdg51fpkyyxradyao4gbwdxrau1iwz1cbujan4mmtmsjfsg_2vkidpohjxzln_cbt2c9mfmvgzjoq7q'
```

For ext4, the maximum length of a file name is 255, but the file name above has a length of 564.

**Comment by BadWindshield** [comment]
I tried running the same command on a _real_ Ubuntu 15.10 machine but got the same error -(

**Comment by samcarter8** [comment]
I had the same problem with this course. As a workaround you try

`-f "mp4"`

to get only the video files.

**Comment by BadWindshield** [comment]
@samcarter8 +1

**Comment by rbrito** [comment]
Dear people,

Since this was already reported on issue #414, could you please add your problems there? As this is a duplicate report, I am closing it or I am going to lose my mind...

I would sincerely appreciate it if you could keep following that issue with further information and testing solutions as we develop them.

Thanks in advance,

Rogério.
