### ISSUE TITLE
‘HTML, CSS, and Javascript for Web Developers’  not working with coursera-dl

### ISSUE THREAD

**Issue by deepakjois** [coursera-dl/coursera-dl#454]
https://www.coursera.org/learn/html-css-javascript-for-web-developers

```
> coursera-dl -n -- html-css-javascript-for-web-developers
Downloading class: html-css-javascript-for-web-developers
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/html-css-javascript-for-web-developers
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/html-css-javascript-for-web-developers (51606 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <4vJt-9A5EeWlUAoDb6ezeQ>.
Proceeding with download of resolution 540p of <4vJt-9A5EeWlUAoDb6ezeQ>.
Gathering subtitle URLs for video_id <4vJt-9A5EeWlUAoDb6ezeQ>.
Gathering transcript URLs for video_id <4vJt-9A5EeWlUAoDb6ezeQ>.
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/deepak/code/personal/coursera/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Users/deepak/code/personal/coursera/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/deepak/code/personal/coursera/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Users/deepak/code/personal/coursera/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Users/deepak/code/personal/coursera/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Users/deepak/code/personal/coursera/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Users/deepak/code/personal/coursera/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
KeyError: 'assetId'
```

**Comment by deepakjois** [comment]
Duplicate of #454. Sorry, should have checked. Please feel free to close.
