### ISSUE TITLE
Some Courses Fail to Download

### ISSUE THREAD

**Issue by GlowingCrystallineEntity** [coursera-dl/coursera-dl#462]
Python 3.4, Windows 7, up-to-date coursera-dl

A handful of courses fail to download with the below exception.  Since I can't find anything to link them, I'll mention one example:  statistical-inference at https://www.coursera.org/learn/statistical-inference/home/welcome

>coursera-dl -n -- statistical-inference

Downloading class: statistical-inference
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/statistical-inference
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/statistical-inference (25283 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Proceeding with download of resolution 540p of <TQpj65IAEeWiUwofNmHWVw>.
Gathering subtitle URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Gathering transcript URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "C:\Python34\lib\site-packages\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/statistical-inference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: statistical-inference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "C:\Python34\lib\site-packages\coursera\api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "C:\Python34\lib\site-packages\coursera\api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "C:\Python34\lib\site-packages\coursera\api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "C:\Python34\lib\site-packages\coursera\api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by ZhouningMan** [comment]
+1, I have similar exception:
Downloading http://blog.differential.com/meteor-vs-angular/?utm_medium=email&utm_source=other&utm_campaign=opencourse.discourse.web-frameworks%7Eopencourse.discourse.ycQnChn3EeWDtQoum3sFeQ.PfN0mIYyEeWOJwp8z3qGpQ%7EBqJDTIboEeWL6AoNmIctaQ -> angular-js\01_front-end-javascript-frameworks-angularjs-overview\02_introduction-to-angularjs\05_introduction-to-angularjs-additional-resources_?utm_medium=email&utm_source=other&utm_campaign=opencourse.discourse.web-frameworks%7Eopencourse.discourse.ycQnChn3EeWDtQoum3sFeQ.pfn0miyyeewojwp8z3qgpq%7ebqjdtiboeewl6aonmictaq
Starting new HTTP connection (1): blog.differential.com
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 91, in login
    r.raise_for_status()
  File "C:\Python34\lib\site-packages\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/angular-js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "C:\Python34\lib\site-packages\coursera\cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: angular-js

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 1015, in download_on_demand_class
    args.resume
  File "C:\Python34\lib\site-packages\coursera\coursera_dl.py", line 528, in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "C:\Python34\lib\site-packages\coursera\downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "C:\Python34\lib\site-packages\coursera\downloaders.py", line 366, in _start_download
    f = open(filename, 'ab') if resume else open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'angular-js\\01_front-end-javascript-frameworks-angularjs-overview\\02_introduction-to-angularjs\\05_introduction-to-angularjs-additional-resources_?utm_medium=email&utm_source=other&utm_campaign=opencourse.discourse.web-frameworks%7Eopencourse.discourse.ycQnChn3EeWDtQoum3sFeQ.pfn0miyyeewojwp8z3qgpq%7ebqjdtiboeewl6aonmictaq'

**Comment by GlowingCrystallineEntity** [comment]
This is blocking some of the most important classes to me.  Any chance someone familiar with the code will be able to look at it?  Thanks....

**Comment by GlowingCrystallineEntity** [comment]
May be a duplicate of #456

**Comment by GlowingCrystallineEntity** [comment]
Also appears to be a duplicate of #463

**Comment by GlowingCrystallineEntity** [comment]
And indeed, the latest version from GitHub seems to work.

When will this become part of the pip install?

**Comment by GlowingCrystallineEntity** [comment]
And indeed, the latest version from GitHub seems to work.

When will this become part of the pip install?

**Comment by rbrito** [comment]
I will update the version on pip as soon as I have some time. To do that, I need to have access to my GPG key, so that all my uploads are cryptographically signed and can be verified.

That being said, it should be soon. I would appreciate it if our users could write some release notes for the versions that will be uploaded.

I have some sketches here and, if there is any interest, I can upload them as a changelog.

That would be a very useful feature for people having issues with the program and to see if their problems are solved or not with a particular update.

**Comment by smaudet** [comment]
I've also experienced some issues with downloading...the new events.coursera.org website is performing some redirects that are breaking the code. There is also a failure to handle files with query parameters after them.

Is there any patch around solving either of these issues? I've developed something locally, I don't know if it would be helpful to PR my changes.

**Comment by smaudet** [comment]
https://github.com/coursera-dl/coursera-dl/issues/481

Similar to my patch, so its probably ok.

**Comment by programmin1** [comment]
Yeah, just installed with pip3 install and I get error trying to download "audio" class that is,
https://www.coursera.org/course/audio

**Comment by balta2ar** [comment]
All mentioned issues here should be fixed in the master branch. Unfortunately, I cannot update pip package. Please use version from github. I'm closing the issue. Feel free to comment if you're still having problems.
