### ISSUE TITLE
Download problem : AttributeError: 'NoneType' object has no attribute 'wrap_socket'

### ISSUE THREAD

**Issue by judywawira** [coursera-dl/coursera-dl#468]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### AttributeError: 'NoneType' object has no attribute 'wrap_socket'
I am trying to download the R programming course but i get this error 

### Your environment
* Operating System (name/version): El Capitan
* Python version:2.7

### Steps to reproduce

python coursera-dl -u <myuser> -p <mypass> r-programming-001

* Is the problem happening with the latest version of the script? yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes 
* What is the course that you are trying to access?R Programming
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
python coursera-dl -u <myuser> -p <mypass> r-programming-001

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
root[main] Downloading class: r-programming-001
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
Traceback (most recent call last):
  File "coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/judywawira/Programming/Coursera/coursera/coursera/coursera_dl.py", line 769, in main
    if download_class(args, class_name):
  File "/Users/judywawira/Programming/Coursera/coursera/coursera/coursera_dl.py", line 716, in download_class
    username=args.username, password=args.password
  File "/Users/judywawira/Programming/Coursera/coursera/coursera/cookies.py", line 318, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/Users/judywawira/Programming/Coursera/coursera/coursera/cookies.py", line 155, in get_authentication_cookies
    login(session, class_name, username, password)
  File "/Users/judywawira/Programming/Coursera/coursera/coursera/cookies.py", line 80, in login
    r = requests.get(class_url, allow_redirects=False)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
    conn.connect()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connection.py", line 169, in connect
    self.sock = ssl.wrap_socket(conn, self.key_file, self.cert_file)
AttributeError: 'NoneType' object has no attribute 'wrap_socket'
```

### Expected behaviour
Should download the course

### Actual behaviour

Shows the above error

**Comment by balta2ar** [comment]
You seem to be trying to download old version of this course. Try new one (enroll here https://www.coursera.org/learn/r-programming):
```
python coursera-dl -u -p r-programming
```

**Comment by balta2ar** [comment]
@judywawira Any luck?

**Comment by balta2ar** [comment]
Closing as no response has been given.
