### ISSUE TITLE
I cannot download this class: https://www.coursera.org/learn/responsivedesign/home/welcome

### ISSUE THREAD

**Issue by codiceexerceo** [coursera-dl/coursera-dl#472]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I cannot download the class: https://www.coursera.org/learn/responsivedesign/home/welcome

### Your environment
* Operating System (name/version): OS-X El Capitan / 10.11.4
* Python version: 2.7.11
* coursera-dl version: how do I check for coursera-dl version?

### Steps to reproduce
Downloading class: responsivedesign
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/responsivedesign
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/responsivedesign (23904 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering supplement URLs for element_id <ZiQZT>.
Gathering supplement URLs for element_id <ssiNo>.
Gathering supplement URLs for element_id <zkVnX>.
Gathering video URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Proceeding with download of resolution 540p of <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering subtitle URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering transcript URLs for video_id <2KpzhdPsEeWGIhKYWqjAgQ>.
Gathering video URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Proceeding with download of resolution 540p of <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering subtitle URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering transcript URLs for video_id <5GVwttdAEeWXSxI4GxQ8ow>.
Gathering video URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Proceeding with download of resolution 540p of <qvomt-xEEeWYIQ7qEqibNw>.
Gathering subtitle URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Gathering transcript URLs for video_id <qvomt-xEEeWYIQ7qEqibNw>.
Traceback (most recent call last):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Users/SK/ZCode/coursera_virtual_env/venv/lib/python2.7/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
KeyError: 'assetId'

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by agug85** [comment]
I have the same behaviour with the course https://www.coursera.org/learn/converter-circuits/home/welcome
I'm running Opensuse Leap 4.1 and I tried both with python 2.7 and python 3.4
coursera-dl has been installed as per your instructions (virtualenv and pip) without any problem.
With the other courses of the specialty, converter-control for example, all runs smoothly.
In short, this is the command and the result:
coursera-dl -u myuser -p mypass --path=/home/alberto/corsi/  converter-circuits
Downloading class: converter-circuits
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/converter-circuits
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/converter-circuits (16076 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering supplement URLs for element_id <EtarH>.
Gathering supplement URLs for element_id <U8pWy>.
Gathering video URLs for video_id <yPFVQjYKEeWm9yIAC5QHTw>.
Proceeding with download of resolution 540p of <yPFVQjYKEeWm9yIAC5QHTw>.
Gathering subtitle URLs for video_id <yPFVQjYKEeWm9yIAC5QHTw>.
Gathering transcript URLs for video_id <yPFVQjYKEeWm9yIAC5QHTw>.
Gathering video URLs for video_id <yPHKczYKEeWm9yIAC5QHTw>.
Proceeding with download of resolution 540p of <yPHKczYKEeWm9yIAC5QHTw>.
Gathering subtitle URLs for video_id <yPHKczYKEeWm9yIAC5QHTw>.
Gathering transcript URLs for video_id <yPHKczYKEeWm9yIAC5QHTw>.
Gathering video URLs for video_id <yPK01DYKEeWm9yIAC5QHTw>.
Proceeding with download of resolution 540p of <yPK01DYKEeWm9yIAC5QHTw>.
Gathering subtitle URLs for video_id <yPK01DYKEeWm9yIAC5QHTw>.
Gathering transcript URLs for video_id <yPK01DYKEeWm9yIAC5QHTw>.
Gathering supplement URLs for element_id <eA6Qt>.
Gathering video URLs for video_id <yPMqBTYKEeWm9yIAC5QHTw>.
Proceeding with download of resolution 540p of <yPMqBTYKEeWm9yIAC5QHTw>.
Gathering subtitle URLs for video_id <yPMqBTYKEeWm9yIAC5QHTw>.
Gathering transcript URLs for video_id <yPMqBTYKEeWm9yIAC5QHTw>.
Traceback (most recent call last):
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/home/alberto/coursera3/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/converter-circuits

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: converter-circuits

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "/home/alberto/coursera3/lib/python3.4/site-packages/coursera/api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'

**Comment by balta2ar** [comment]
You're using version from pip which is outdated. Use github version for the time being.
