### ISSUE TITLE
[ssl-issues] Course not found...

### ISSUE THREAD

**Issue by Make42** [coursera-dl/coursera-dl#478]
To download and install coursera-dl I proceeded in the way described in https://github.com/coursera-dl/coursera-dl/issues/475#issuecomment-211243263 and now I just did

    ./coursera/bin/coursera-dl -u username@provider.com -p password mycourse

which worked for the course `hadoop`, but the courses `intro-to-big-data` and `graph-analytics` cannot be found apparently:

```
$ ./coursera/bin/coursera-dl -u username -p password graph-analytics
Downloading class: graph-analytics
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/graph-analytics
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/graph-analytics (29882 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <kJVkEcxpEeWcGApkjP9KTQ>.
Proceeding with download of resolution 540p of <kJVkEcxpEeWcGApkjP9KTQ>.
Gathering subtitle URLs for video_id <kJVkEcxpEeWcGApkjP9KTQ>.
Gathering transcript URLs for video_id <kJVkEcxpEeWcGApkjP9KTQ>.
Gathering supplement URLs for element_id <iEzJg>.
Gathering video URLs for video_id <TNTMTbr7EeWvegpOvElysQ>.
Proceeding with download of resolution 540p of <TNTMTbr7EeWvegpOvElysQ>.
Gathering subtitle URLs for video_id <TNTMTbr7EeWvegpOvElysQ>.
Gathering transcript URLs for video_id <TNTMTbr7EeWvegpOvElysQ>.
Gathering video URLs for video_id <mgIxSbsvEeWbMRIzWTFZPQ>.
Proceeding with download of resolution 540p of <mgIxSbsvEeWbMRIzWTFZPQ>.
Gathering subtitle URLs for video_id <mgIxSbsvEeWbMRIzWTFZPQ>.
Gathering transcript URLs for video_id <mgIxSbsvEeWbMRIzWTFZPQ>.
Gathering video URLs for video_id <IaNNyLsxEeWS_A6rDePrsQ>.
Proceeding with download of resolution 540p of <IaNNyLsxEeWS_A6rDePrsQ>.
Gathering subtitle URLs for video_id <IaNNyLsxEeWS_A6rDePrsQ>.
Gathering transcript URLs for video_id <IaNNyLsxEeWS_A6rDePrsQ>.
Gathering video URLs for video_id <5QBi27ytEeWjmAoYFnTFNw>.
Proceeding with download of resolution 540p of <5QBi27ytEeWjmAoYFnTFNw>.
Gathering subtitle URLs for video_id <5QBi27ytEeWjmAoYFnTFNw>.
Gathering transcript URLs for video_id <5QBi27ytEeWjmAoYFnTFNw>.
Gathering video URLs for video_id <pTXjJ7y2EeWl5BKFfRwcCw>.
Proceeding with download of resolution 540p of <pTXjJ7y2EeWl5BKFfRwcCw>.
Gathering subtitle URLs for video_id <pTXjJ7y2EeWl5BKFfRwcCw>.
Gathering transcript URLs for video_id <pTXjJ7y2EeWl5BKFfRwcCw>.
Gathering video URLs for video_id <qgTBrcPFEeWqIg4sbfgzqw>.
Proceeding with download of resolution 540p of <qgTBrcPFEeWqIg4sbfgzqw>.
Gathering subtitle URLs for video_id <qgTBrcPFEeWqIg4sbfgzqw>.
Gathering transcript URLs for video_id <qgTBrcPFEeWqIg4sbfgzqw>.
Gathering video URLs for video_id <3EYNK8PFEeWqIg4sbfgzqw>.
Proceeding with download of resolution 540p of <3EYNK8PFEeWqIg4sbfgzqw>.
Gathering subtitle URLs for video_id <3EYNK8PFEeWqIg4sbfgzqw>.
Gathering transcript URLs for video_id <3EYNK8PFEeWqIg4sbfgzqw>.
Gathering video URLs for video_id <OGgZU7AbEeWuqgro24JvYQ>.
Proceeding with download of resolution 540p of <OGgZU7AbEeWuqgro24JvYQ>.
Gathering subtitle URLs for video_id <OGgZU7AbEeWuqgro24JvYQ>.
Gathering transcript URLs for video_id <OGgZU7AbEeWuqgro24JvYQ>.
Gathering supplement URLs for element_id <6VYKD>.
Gathering supplement URLs for element_id <dOxiY>.
Gathering video URLs for video_id <7Fwjcr7ZEeW-BxKkQ3M7cQ>.
Proceeding with download of resolution 540p of <7Fwjcr7ZEeW-BxKkQ3M7cQ>.
Gathering subtitle URLs for video_id <7Fwjcr7ZEeW-BxKkQ3M7cQ>.
Gathering transcript URLs for video_id <7Fwjcr7ZEeW-BxKkQ3M7cQ>.
Gathering supplement URLs for element_id <4fYq9>.
Gathering supplement URLs for element_id <cr5Lr>.
Gathering video URLs for video_id <9gTRcb7vEeWEvQpIZOIdpw>.
Proceeding with download of resolution 540p of <9gTRcb7vEeWEvQpIZOIdpw>.
Gathering subtitle URLs for video_id <9gTRcb7vEeWEvQpIZOIdpw>.
Gathering transcript URLs for video_id <9gTRcb7vEeWEvQpIZOIdpw>.
Gathering video URLs for video_id <1UVLacQ_EeWpAQq6LZ9qww>.
Proceeding with download of resolution 540p of <1UVLacQ_EeWpAQq6LZ9qww>.
Gathering subtitle URLs for video_id <1UVLacQ_EeWpAQq6LZ9qww>.
Gathering transcript URLs for video_id <1UVLacQ_EeWpAQq6LZ9qww>.
Gathering video URLs for video_id <ecqcuMRPEeWN6QpxjiSRMw>.
Proceeding with download of resolution 540p of <ecqcuMRPEeWN6QpxjiSRMw>.
Gathering subtitle URLs for video_id <ecqcuMRPEeWN6QpxjiSRMw>.
Gathering transcript URLs for video_id <ecqcuMRPEeWN6QpxjiSRMw>.
Gathering video URLs for video_id <W-f_bcRAEeWYehJPwvucLw>.
Proceeding with download of resolution 540p of <W-f_bcRAEeWYehJPwvucLw>.
Gathering subtitle URLs for video_id <W-f_bcRAEeWYehJPwvucLw>.
Gathering transcript URLs for video_id <W-f_bcRAEeWYehJPwvucLw>.
Gathering video URLs for video_id <UNARR8YEEeWCLxJR83TgdQ>.
Proceeding with download of resolution 540p of <UNARR8YEEeWCLxJR83TgdQ>.
Gathering subtitle URLs for video_id <UNARR8YEEeWCLxJR83TgdQ>.
Gathering transcript URLs for video_id <UNARR8YEEeWCLxJR83TgdQ>.
Gathering video URLs for video_id <JqSqlMYFEeWCLxJR83TgdQ>.
Proceeding with download of resolution 540p of <JqSqlMYFEeWCLxJR83TgdQ>.
Gathering subtitle URLs for video_id <JqSqlMYFEeWCLxJR83TgdQ>.
Gathering transcript URLs for video_id <JqSqlMYFEeWCLxJR83TgdQ>.
Gathering video URLs for video_id <Tu8xncBgEeWsAAoccyRv_Q>.
Proceeding with download of resolution 540p of <Tu8xncBgEeWsAAoccyRv_Q>.
Gathering subtitle URLs for video_id <Tu8xncBgEeWsAAoccyRv_Q>.
Gathering transcript URLs for video_id <Tu8xncBgEeWsAAoccyRv_Q>.
Traceback (most recent call last):
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "~/coursera-download/coursera/lib/python3.4/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/graph-analytics

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: graph-analytics

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./coursera/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "~/coursera-download/coursera/lib/python3.4/site-packages/coursera/api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'
```

I am sure the issue is already resolved, but I am not able to decipher the error message. Could someone please point me to the solution? Thanks.

BTW: `--clear-cache` did not help and yes, I logged into the courses to make sure I am registered for them.

**Comment by balta2ar** [comment]
@Make42 This issue was fixed in this pull request: #439. Please use **version from github**, **not pip**.

@rbrito We desperately need to update pip version...

**Comment by Make42** [comment]
I did

```
cd /directory/where/I/want/my/courses
virtualenv my-coursera
cd my-coursera
source bin/activate
git clone https://github.com/coursera-dl/coursera
cd coursera
pip install -r requirements.txt
./coursera-dl ...
```

and got

```
$ ./coursera-dl -u username -p password hadoop
Downloading class: hadoop
Starting new HTTPS connection (1): class.coursera.org
~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
404 Client Error: Not Found for url: https://class.coursera.org/hadoop
Starting new HTTPS connection (1): www.coursera.org
~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "~/coursera-download/my-coursera/coursera/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "~/coursera-download/my-coursera/coursera/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "~/coursera-download/my-coursera/coursera/coursera/coursera_dl.py", line 973, in download_on_demand_class
    login(session, args.username, args.password)
  File "~/coursera-download/my-coursera/coursera/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "~/coursera-download/my-coursera/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

Take in mind that the course "hadoop" had already worked with my previous approach...

**Comment by balta2ar** [comment]
@Make42 In that I suggest that you offload file downloading to an external downloader such as aria2 (`--aria` option). If aria2 fails with similar error code too, you can configure it to ignore SSL certificate verification in its configuration file.

**Comment by Make42** [comment]
@balta2ar: `./coursera-dl --aria -u name -p pass hadoop` fails similarily. Can you point were to configure aria?

**Comment by balta2ar** [comment]
@Make42 Put this into `~/.aria2/aria2.conf`:
```
check-certificate=false
```

But I'm afraid this isn't gonna help. aria2 is only used to download media files such as lectures. Course pages are still downloaded using requests (or urllib3) python library. coursera-dl does not support an option to turn off SSL verification for that part of networking interaction.

If you're really motivated, you can fix the code. It's actually very simple to do a few hacks here and there. For example, your code currently fails at this line: https://github.com/coursera-dl/coursera-dl/blob/master/coursera/cookies.py#L121. All you need to do (according to the documentation: http://docs.python-requests.org/en/v1.0.4/user/advanced/#ssl-cert-verification) is to add `verify=False` argument to the function call. You most certainly will need to do the same in other places where requests library is called.

P.S. While answering your question I glimpsed over the older similar SSL issues and noticed this: https://github.com/coursera-dl/coursera-dl/issues/377#issue-94456820. Dude, what the f*ck?? You already reported that very same issue last year and the thread is full of discussions and advices on how to address the problem. Go read the thread and try suggested solutions.

**Comment by Make42** [comment]
@balta2ar: I know, I know - and the issue still stands. The problem is that I am using Python 2.7.6 which is a little old on my Kubuntu 14.4. There is no new Python in the repos. Trying to update python f** up my **entire machine** - I am not doing that again! **So** for some reason the whole thing works with *not using Github-Version*, but the pip-version. Don't ask me why. You asking me to use the Github-Version and I had hoped that this would have been resolved by now, but I guess it never will and I will just have to wait until I get a new Kubuntu and with it a newer Python.
