### ISSUE TITLE
[ssl-issues] 404 Client Error: Not Found for url: https://class.coursera.org/negotiation-skills

### ISSUE THREAD

**Issue by KwToPA** [coursera-dl/coursera-dl#480]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
can't download negotiation-skills
 
### Your environment
* Operating System (name/version): OS X 10.10.5
* Python version:  Python 2.7.6
* coursera-dl version: last

```
proxychains4 coursera-dl -u user -p password  -f "mp4 srt pdf" --resume negotiation-skills
```
```
[proxychains] config file found: /usr/local/Cellar/proxychains-ng/4.7/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.7/lib/libproxychains4.dylib
[proxychains] DLL init
[proxychains] DLL init
Downloading class: negotiation-skills
Starting new HTTPS connection (1): class.coursera.org
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  class.coursera.org:443  ...  OK
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
404 Client Error: Not Found for url: https://class.coursera.org/negotiation-skills
Starting new HTTPS connection (1): www.coursera.org
[proxychains] Strict chain  ...  127.0.0.1:1080  ...  www.coursera.org:443  ...  OK
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/coursera_dl.py", line 973, in download_on_demand_class
    login(session, args.username, args.password)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

```

**Comment by KwToPA** [comment]
```
coursera-dl -u user -p password  -f "mp4 srt pdf" --resume negotiation-skills 
```
is ok without proxychains4 but it has a very slow speed
