### ISSUE TITLE
[shorten-filenames] URL Not found

### ISSUE THREAD

**Issue by zenny** [coursera-dl/coursera-dl#483]
Hi,

* UPDATE with pip3 at the end. Also tried with https://github.com/coursera-dl/coursera-dl/issues/480#issuecomment-213962319 with the same error.

I have tried with binary and pulling from this repo to download
https://www.coursera.org/learn/personalizedmed

but, I am getting:

> 404 Client Error: Not Found for url: https://class.coursera.org/personalizedmed

The command I used was:

> ./coursera-dl -u 'username' -p 'password' --aria2 --resume --path=/home/zenny/Downloads/coursera/ personalizedmed

### Your environment
* Operating System (name/version): Ubuntu 14.04.4
* Python version: Python 2.7.6 and 3.4
* coursera-dl version: latest master from github and 0.5

### Steps to reproduce
As stated above

* Is the problem happening with the latest version of the script?

yes

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.

Yes

* What is the course that you are trying to access?
https://www.coursera.org/learn/personalizedmed

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

./coursera-dl -u 'username' -p 'password' --aria2 --resume --path=/home/zenny/Downloads/coursera/ personalizedmed

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
$ ./coursera-dl --debug -u 'user' -p 'password' --aria2 --resume --path=/home/zennyDownloads/coursera/ personalizedmed
root[main] Downloading class: personalizedmed
root[download_class] Downloading old style class personalizedmed
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /tmp/zenny_coursera_dl_cache/cookies/user.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
requests.packages.urllib3.connectionpool[_make_request] "GET /personalizedmed HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/personalizedmed
root[download_class] Downloading new style (on demand) class personalizedmed
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=eRMxO8MEyc1DMdzepe3q; csrf2_token_yzu6ArTj=5QPEb4QkCHfd1InQMbsZFN7F.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/zennyDownloads/coursera/my-coursera/coursera/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/home/zennyDownloads/coursera/my-coursera/coursera/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/zennyDownloads/coursera/my-coursera/coursera/coursera/coursera_dl.py", line 973, in download_on_demand_class
    login(session, args.username, args.password)
  File "/home/zennyDownloads/coursera/my-coursera/coursera/coursera/cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/zennyDownloads/coursera/my-coursera/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

# UPDATE

After reinstalling with `pip3 install --user coursera`, the error reports as:

```
$ ./coursera-dl -u 'username' -p 'password' --aria2 --resume --path=/home/zenny/Downloads/coursera/ personalizedmed
root[main] Downloading class: personalizedmed
root[download_class] Downloading old style class personalizedmed
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /tmp/zenny_coursera_dl_cache/cookies/<USER>.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /personalizedmed HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/personalizedmed
root[download_class] Downloading new style (on demand) class personalizedmed
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=TwwgLIw2h3B7bAGt2X2y; csrf2_token_HThWBPyG=3qYqVD0voyWxPoSDwpQazb9c.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/course/personalizedmed HTTP/1.1" 200 None
root[get_on_demand_syllabus] Downloaded https://www.coursera.org/api/opencourse.v1/course/personalizedmed (44171 bytes)
root[parse_on_demand_syllabus] Parsing syllabus of on-demand course. This may take some time, be patient ...
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/pmz1vJkgEeWubRKNGLFvBw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <pmz1vJkgEeWubRKNGLFvBw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <pmz1vJkgEeWubRKNGLFvBw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <pmz1vJkgEeWubRKNGLFvBw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <pmz1vJkgEeWubRKNGLFvBw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <pmz1vJkgEeWubRKNGLFvBw>.
root[extract_links_from_supplement] Gathering supplement URLs for element_id <CCjsE>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupplements.v1/p6GNi4gDEeW0iQ6RUMSWEQ~CCjsE?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/p-lreYgDEeWZVw6NBrQ7nw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <p-lreYgDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <p-lreYgDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <p-lreYgDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <p-lreYgDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <p-lreYgDEeWZVw6NBrQ7nw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/77u7FJqvEeWAWApk6BgvdQ HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <77u7FJqvEeWAWApk6BgvdQ>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assets.v1/7ZXNUZqvEeW-eA7BpFa39Q HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/p-ngqogDEeWZVw6NBrQ7nw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <p-ngqogDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <p-ngqogDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 540p of <p-ngqogDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <p-ngqogDEeWZVw6NBrQ7nw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <p-ngqogDEeWZVw6NBrQ7nw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/Hcr135qwEeW7KQpS0XqOiw HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <Hcr135qwEeW7KQpS0XqOiw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assets.v1/G01x35qwEeWlHhKJ1B0NIQ HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/A90jmJ3fEeWLThJXTDFJIQ HTTP/1.1" 200 175
root[_get_open_course_asset_ids] Parsing JSON for asset_id <A90jmJ3fEeWLThJXTDFJIQ>.
Traceback (most recent call last):
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/home/zenny/.local/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/personalizedmed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: personalizedmed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./coursera-dl", line 9, in <module>
    load_entry_point('coursera==0.5.2', 'console_scripts', 'coursera-dl')()
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "/home/zenny/.local/lib/python3.4/site-packages/coursera/api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'
```

**Comment by eddeyang** [comment]
Confirmed, I have the same issue on Windows.

**Comment by fogine** [comment]
Also same issue on:
Operating System (name/version): Ubuntu 14.04.4
Python version: 3.4.3
coursera-dl version: 0.5.2

Trying to download: https://www.coursera.org/learn/practical-machine-learning/
but the coursera-dl is searching for https://class.coursera.org/practical-machine-learning

**Comment by balta2ar** [comment]
I've downloaded the course just fine a moment ago. Could you try version from github instead of pip?

**Comment by cobbit** [comment]
I am having the same issue. 
Downloading aborted for two courses. I tried to resume but it happens again and again, the same issue every time.
Courses were iot and calculus1
Half of the courses downloaded fine and then the exceptions happened.

I have the latest version of python and coursera-dl (installed yesterday). 
OS: Windows 7
To resume I used command: coursera-dl -u 'username' -p 'password' --calculus1 --resume

**Comment by balta2ar** [comment]
@cobbit Are you using github version? Do not use pip for now, it's very old.
Show me the full debug log if you're still having problems with the latest github version.

**Comment by balta2ar** [comment]
@cobbit Oh, you're Windows user. You might be still experiencing long-filenames issue. I have plans to address it soon.

**Comment by cobbit** [comment]
I installed it from pip because I find that easy. I will try to install it from github.

**Comment by balta2ar** [comment]
@cobbit Breaking news: do `pip uninstall coursera` and then `pip install coursera-dl`. Yes, with `-dl` suffix the second time.

**Comment by cobbit** [comment]
@balta2ar I did it the other way: `pip install <address_of_the _local_directory>`. Thanks, I have got the courses I wanted.

**Comment by pmcfarland** [comment]
@balta2ar  I tried to reinstall using pip install coursera-dl and got this:

Could not find a version that satisfies the requirement coursera-dl (from versions: )
No matching distribution found for coursera-dl

I'll try installing from github directly for now but anything to suggest?

**Comment by balta2ar** [comment]
@pmcfarland That's the way to go now. Sorry for the confusion, I'm also having troubles with installing `coursera-dl`. I wonder why, it worked couple of days ago... I'll look into this.

**Comment by balta2ar** [comment]
@pmcfarland Doing `pip uninstall coursera-dl` and `pip install --upgrade coursera-dl` helped me. Could you check whether it works for you?
