### ISSUE TITLE
ERROR: No connection adapters were found for 'mailto:eslinfo@pe.gatech.edu'

### ISSUE THREAD

**Issue by amirj** [coursera-dl/coursera-dl#487]
### Subject of the issue
coursera-dl -u "user" -p "pass" professional-emails-english

### Your environment
* Operating System (name/version): OSX
* Python version: 2.7
* coursera-dl version: latest version from pip

### Steps to reproduce
coursera-dl -u "user" -p "pass" professional-emails-english

### Actual behaviour
Downloading: professional-emails-english/01_get-to-know-basic-email-writing-structures/03_punctuation-and-capitalization/04_get-more-from-the-georgia-tech-language-institute_mailto:eslinfo@pe.gatech.edu
Downloading mailto:eslinfo@pe.gatech.edu -> professional-emails-english/01_get-to-know-basic-email-writing-structures/03_punctuation-and-capitalization/04_get-more-from-the-georgia-tech-language-institute_mailto:eslinfo@pe.gatech.edu
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1015, in download_on_demand_class
    args.resume
  File "/usr/local/lib/python2.7/site-packages/coursera/coursera_dl.py", line 528, in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "/usr/local/lib/python2.7/site-packages/coursera/downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "/usr/local/lib/python2.7/site-packages/coursera/downloaders.py", line 322, in _start_download
    r = self.session.get(url, stream=True, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 579, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 653, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'mailto:eslinfo@pe.gatech.edu'

**Comment by HihoHa** [comment]
I have similar problem
`coursera-dl -u'******@gmail.com' -p'*******' introclassicalmusic`

output snippet:
Downloading: introclassicalmusic/01_what-is-music/01_course-pages/04_travel-opportunity-vienna-a-city-of-music-october-18-24-2016_mailto:edtravel@yale.edu
Downloading mailto:edtravel@yale.edu -> introclassicalmusic/01_what-is-music/01_course-pages/04_travel-opportunity-vienna-a-city-of-music-october-18-24-2016_mailto:edtravel@yale.edu
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 1015, in download_on_demand_class
    args.resume
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 528, in download_lectures
    downloader.download(url, lecfn, resume=resume)
  File "/usr/local/lib/python2.7/dist-packages/coursera/downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "/usr/local/lib/python2.7/dist-packages/coursera/downloaders.py", line 322, in _start_download
    r = self.session.get(url, stream=True, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 579, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 653, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'mailto:edtravel@yale.edu'
