### ISSUE TITLE
Course won't download

### ISSUE THREAD

**Issue by racemus** [coursera-dl/coursera-dl#499]
### Subject of the issue
Course won't download.

### Your environment
* Operating System (name/version): Mac OS X 10.11.5
* Python version: 3.5.1
* coursera-dl version: last

### Steps to reproduce
Just try to download "java-programming-design-principles" course

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yep
* What is the course that you are trying to access? java-programming-design-principles
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
coursera-dl -u ####@####.com -p ************* --video-resolution 720p java-programming-design-principles
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
root[main] Downloading class: java-programming-design-principles
root[download_class] Downloading old style class java-programming-design-principles
root[get_cookies_from_cache] Trying to get cookies from the cache.
root[load_cookies_file] Loading cookie file /var/folders/6z/7_w0ynld5bl45wk9q6b0pdch0000gn/T/aries_coursera_dl_cache/cookies/aries.elein@gmail.com.txt into memory.
root[get_cookies_from_cache] Could not load cookies from the cache.
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): class.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "GET /java-programming-design-principles HTTP/1.1" 404 None
root[login] 404 Client Error: Not Found for url: https://class.coursera.org/java-programming-design-principles
root[download_class] Downloading new style (on demand) class java-programming-design-principles
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=b6BffJWr9wiuFxHp1Q8o; csrf2_token_pY89uLht=wxaC7oxsECOVwLLHwN1BJgjY.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/course/java-programming-design-principles HTTP/1.1" 200 None
root[get_on_demand_syllabus] Downloaded https://www.coursera.org/api/opencourse.v1/course/java-programming-design-principles (23754 bytes)
root[parse_on_demand_syllabus] Parsing syllabus of on-demand course. This may take some time, be patient ...
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/2b9JAaQNEeWeig6Xp9V2dw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <2b9JAaQNEeWeig6Xp9V2dw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <2b9JAaQNEeWeig6Xp9V2dw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 720p of <2b9JAaQNEeWeig6Xp9V2dw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <2b9JAaQNEeWeig6Xp9V2dw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <2b9JAaQNEeWeig6Xp9V2dw>.
root[extract_links_from_supplement] Gathering supplement URLs for element_id <Yyrxg>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupplements.v1/dB1qehnoEeWwrBKfKrqlSQ~Yyrxg?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
root[extract_links_from_supplement] Gathering supplement URLs for element_id <03Pyh>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/onDemandSupplements.v1/dB1qehnoEeWwrBKfKrqlSQ~03Pyh?includes=asset&fields=openCourseAssets.v1%28typeName%29,openCourseAssets.v1%28definition%29 HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/assetUrls.v1?ids=Ak8E_sOTEeWUahLPevmjfw%2C9ycdS8OUEeWu4ApYq4IbUQ%2CW6WBVsOTEeWicwr5JH8fgw%2CRpYoI8OUEeWPRQ4YsSEORQ%2CKImh1sOVEeWPRQ4YsSEORQ%2CECYcb8OTEeWFNA5XwZEiOw%2C7wykMcOTEeWPRQ4YsSEORQ%2CnKpJ-sOUEeWu4ApYq4IbUQ%2Ct2GnUcOSEeWzmA6yyDbkWw%2CyjYPG8OSEeWVLw5DTx4w7w%2CHmeOMMOTEeWPRQ4YsSEORQ HTTP/1.1" 200 None
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/kqxrbp6fEeWwrA7gXKI29w HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <kqxrbp6fEeWwrA7gXKI29w>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <kqxrbp6fEeWwrA7gXKI29w>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 720p of <kqxrbp6fEeWwrA7gXKI29w>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <kqxrbp6fEeWwrA7gXKI29w>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <kqxrbp6fEeWwrA7gXKI29w>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/Wybulp6SEeWJmQroKumh6Q HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <Wybulp6SEeWJmQroKumh6Q>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <Wybulp6SEeWJmQroKumh6Q>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 720p of <Wybulp6SEeWJmQroKumh6Q>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <Wybulp6SEeWJmQroKumh6Q>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <Wybulp6SEeWJmQroKumh6Q>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/opencourse.v1/video/vzCFP56SEeW7tAou3qoLgw HTTP/1.1" 200 None
root[_extract_videos_and_subtitles_from_lecture] Parsing JSON for video_id <vzCFP56SEeW7tAou3qoLgw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering video URLs for video_id <vzCFP56SEeW7tAou3qoLgw>.
root[_extract_videos_and_subtitles_from_lecture] Proceeding with download of resolution 720p of <vzCFP56SEeW7tAou3qoLgw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering subtitle URLs for video_id <vzCFP56SEeW7tAou3qoLgw>.
root[_extract_videos_and_subtitles_from_lecture] Gathering transcript URLs for video_id <vzCFP56SEeW7tAou3qoLgw>.
requests.packages.urllib3.connectionpool[_make_request] "GET /api/openCourseAssets.v1/qnI3nqTrEeWY7gq_5mSiqQ HTTP/1.1" 200 None
root[_get_open_course_asset_ids] Parsing JSON for asset_id <qnI3nqTrEeWY7gq_5mSiqQ>.
Traceback (most recent call last):
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/java-programming-design-principles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: java-programming-design-principles

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aries/.virtualenvs/coursera/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "/Users/aries/.virtualenvs/coursera/lib/python3.5/site-packages/coursera/api.py", line 153, in <listcomp>
    for element in dom['elements']]
KeyError: 'assetId'
```

**Comment by balta2ar** [comment]
You're using version from pip, unfortunately it's outdated. Please use the latest version from github.

**Comment by racemus** [comment]
OK. Is there any instruction how to install it?

**Comment by balta2ar** [comment]
Sure, here it is: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by racemus** [comment]
Thank you. Version is the same - 0.5.2 Is this OK?

**Comment by balta2ar** [comment]
Yes, version number has not been updated for while.
