### ISSUE TITLE
keyError: assetId

### ISSUE THREAD

**Issue by thecpshah** [coursera-dl/coursera-dl#502]
### Subject of the issue
I have used the script to download many courses from a specialisation in Robotics. I could download all courses except this https://www.coursera.org/learn/robotics-learning

### Your environment
* Operating System (name/version): Mac OSX, EL Capitan 10.11.5
* Python version: 2.7.11
* coursera-dl version: Latest

### Steps to reproduce
coursera-dl -u email@email.com -p password robotics-learning

### Expected behaviour
The course should download.

### Actual behaviour

I get the following error.
`
Traceback (most recent call last):
  File "/Users/chintanshah/anaconda/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/Users/chintanshah/anaconda/lib/python2.7/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
KeyError: 'assetId'
`

**Comment by RayBB** [comment]
That course downloads fine for me using "robotics-learning"

Perhaps upgrading to Python 3 will fix your issue.
The [install instructions](https://github.com/coursera-dl/coursera-dl#installation-instructions) say that it's highly recommended.

**Comment by balta2ar** [comment]
@thecpshah Most likely you're using `coursera` pip package. This is a known issue, and it's been fixed in the master branch, but I can't update `coursera` pip package. You have two options:

1. Install `coursera-dl` pip package (note the `-dl` suffix): `pip install coursera-dl`
2. Use the latest version from github

The first option is not documented. In fact, documentation says NOT to install `coursera-dl`, but there has been changes to this package and `coursera-dl` will ship code from this repository now. This is not yet in the documentation though.
