### ISSUE TITLE
Docker build error in Step 6: cffi install failure

### ISSUE THREAD

**Issue by stephenwithav** [coursera-dl/coursera-dl#505]
`./build.sh` fails with the following error:

```
Running setup.py install for cffi
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so
    
  Could not find .egg-info directory in install record for cffi>=1.4.1 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 751, in install
    os.rmdir(temp_location)
OSError: [Errno 39] Directory not empty: '/tmp/pip-BAFJIT-record'

Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install ndg-httpsclient' returned a non-zero code: 2
```

### Your environment
* Operating System (name/version): Docker via Debian Jessie

### Steps to reproduce

```
git clone https://github.com/coursera-dl/coursera-dl/
cd coursera-dl
./build.sh
```

**Comment by balta2ar** [comment]
I can't reproduce that. It builds fine for me. @seninds Do you have any ideas?

**Comment by stephenwithav** [comment]
Are you building with `--no-cache`?

Seperately, would you be willing to push your `coursera-img` image to Docker Hub?

**Comment by stephenwithav** [comment]
An automated build succeeded.  Yay. :+1: 

https://hub.docker.com/r/stephenwithav/coursera-dl/builds/

**Comment by balta2ar** [comment]
@stephenwithav Can we close the issue?

**Comment by stephenwithav** [comment]
Sure.
