### ISSUE TITLE
Failed to download courses from the new platform

### ISSUE THREAD

**Issue by biocyberman** [coursera-dl/coursera-dl#515]
### Subject of the issue
Failed to download courses from the new platform

### Your environment
* Operating System (name/version): Ubuntu 14.04
* Python version: 3.4.4
* coursera-dl version: Latest to date (19/6-2016). Installed from pip

### Actual behaviour

```python
(coursera)➜  coursera coursera-dl -n -- statistical-inference
Downloading class: statistical-inference
Starting new HTTPS connection (1): class.coursera.org
404 Client Error: Not Found for url: https://class.coursera.org/statistical-inference
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/statistical-inference (25513 bytes)
Parsing syllabus of on-demand course. This may take some time, be patient ...
Gathering video URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Proceeding with download of resolution 540p of <TQpj65IAEeWiUwofNmHWVw>.
Gathering subtitle URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Gathering transcript URLs for video_id <TQpj65IAEeWiUwofNmHWVw>.
Traceback (most recent call last):
  File "/envs/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/envs/coursera/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/statistical-inference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1031, in download_class
    return download_old_style_class(args, class_name)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 912, in download_old_style_class
    username=args.username, password=args.password)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: statistical-inference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/envs/coursera/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1056, in main
    if download_class(args, class_name):
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1034, in download_class
    return download_on_demand_class(args, class_name)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 987, in download_on_demand_class
    args.video_resolution)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/coursera_dl.py", line 331, in parse_on_demand_syllabus
    video_resolution, assets)
  File "/envs/coursera/lib/python3.4/site-packages/coursera/api.py", line 73, in extract_links_from_lecture
    links, self._extract_links_from_lecture_assets(assets))
  File "/envs/coursera/lib/python3.4/site-packages/coursera/api.py", line 127, in _extract_links_from_lecture_assets
    for open_course_asset_id in self._get_open_course_asset_ids(asset_id):
  File "/envs/coursera/lib/python3.4/site-packages/coursera/api.py", line 153, in _get_open_course_asset_ids
    for element in dom['elements']]
  File "/envs/coursera/lib/python3.4/site-packages/coursera/api.py", line 153, in <listcomp>
    for element in dom['elements']]

```

**Comment by balta2ar** [comment]
See my comment: https://github.com/coursera-dl/coursera-dl/issues/511#issuecomment-226938370

**Comment by PetrToman** [comment]
Hello,
I have a similar problem - see attached logs (with and without --debug):

- OS: Windows Vista SP2 32bit
- Python version: 3.5.1
- pip version: 8.1.2 ('pip install -U -r requirements.txt' run successfully)
- coursera-dl version: latest from git

[log.txt](https://github.com/coursera-dl/coursera-dl/files/322295/log.txt)
[log-debug.txt](https://github.com/coursera-dl/coursera-dl/files/322296/log-debug.txt)

**Comment by balta2ar** [comment]
@PetrToman Fixed in master branch.

**Comment by andyd0** [comment]
Hi.  I just did a new install and running into the same issue.  I'm a little confused on how to fix the issue.

**Comment by balta2ar** [comment]
@andyd0 Which issue exactly? Could you show the log? Two distinct issues has been reported in this thread.

**Comment by andyd0** [comment]
@balta2ar  Sorry it works.  I didn't realize it tried two ways of connecting.  The second error was due to an incorrect username

**Comment by biocyberman** [comment]
Installing the latest 0.6.0.1 from pip and running with python3 works fine. Very happy for this.
