### ISSUE TITLE
extreme amateur problem

### ISSUE THREAD

**Issue by kwy8** [coursera-dl/coursera-dl#524]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I have no idea how to add the Python executable location to my PATH environment, and I am very lost now.

### Your environment
* Operating System (name/version): Mac OS Yosemite 10.10.5
* Python version: Python 3.6 
* coursera-dl version: um it's created on June 19th, 2016

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
I'm not even in the process of producing anything :(

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.
I should be able to download the soon-to-be-removed Coursera courses with ease 
### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
I'm frustrated at myself for not learning Python earlier

**Comment by balta2ar** [comment]
@kwy8 http://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

**Comment by kwy8** [comment]
@balta2ar Hi thanks...but I'm using Mac OS...

**Comment by victorwestmann** [comment]
Using native python2 for Mac (python == 2.7.10) on Mac OSX El Capital (10.11.6).
8 GB RAM. Installed Python 3.6 just today. (this version was release 3 days ago (December 23rd)).

Hi there.

When I run the
```pip install coursera-dl```
on my terminal I get the following error message:


```AdminsMBP56:coursera-dl victorwestmann$ pip install coursera-dl
Collecting coursera-dl
  Using cached coursera-dl-0.8.0.tar.gz
Requirement already satisfied: beautifulsoup4>=4.1.3 in /Library/Python/2.7/site-packages (from coursera-dl)
Requirement already satisfied: requests>=2.10.0 in /Library/Python/2.7/site-packages (from coursera-dl)
Collecting six>=1.5.0 (from coursera-dl)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting urllib3>=1.10 (from coursera-dl)
  Using cached urllib3-1.19.1-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.7 in /Library/Python/2.7/site-packages (from coursera-dl)
Collecting keyring>=4.0 (from coursera-dl)
  Using cached keyring-10.1-py2.py3-none-any.whl
Installing collected packages: six, urllib3, keyring, coursera-dl
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/gl/3v12qsh50jz62c1mxtb9kh200000gq/T/pip-RXE8lE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'```

**Comment by balta2ar** [comment]
This is because you don't have permissions: `OSError: [Errno 1] Operation not permitted`.

Options:
1. Install in a virtualenv (see README)
2. pip install --user coursera-dl
3. sudo pip install coursera-dl

**Comment by victorwestmann** [comment]
Holly cow! IT WORKS! ;-)
