### ISSUE TITLE
AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139

### ISSUE THREAD

**Issue by moun3imy** [coursera-dl/coursera-dl#531]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Can't download the course https://www.coursera.org/course/bitcointech

### Your environment
* OS X Yosemite
* Python version: 2.7.11
* coursera-dl version: 0.6.1
### Steps to reproduce
just run coursera-dl with u and p parameters and the name of the course, I tried the names bitcointech, bitcointech-001, bitcointech-002 as described [here](https://www.class-central.com/mooc/3655/coursera-bitcoin-and-cryptocurrency-technologies)  but it's still causing the following error to appear.

### Actual behaviour
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 7, in <module>
    from coursera.coursera_dl import main
  File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 91, in <module>
    assert V(six.__version__) >= V('1.5'), "Upgrade six!" + _SEE_URL
AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139

I've visited the link https://github.com/coursera-dl/coursera/issues/139 and followed the instructions there, specifically for installing coursera-dl within a virtualenv, but this resulted in the very same error stack.

Please help, thanks in advance !

**Comment by rbrito** [comment]
Please, list the packages that you have installed in your virtual environment (e.g., `pip freeze` while in your virtual environment), so that we can know what the interpreter thinks that it is using.

**Comment by rbrito** [comment]
I just tested quickly and I think that it may be worth it to add to the assert the values of `six.__version__` and `six.__file__`, so that we know where things come from when the user executes the code in the environment where they are executing it.
