### ISSUE TITLE
Crashing with exception on http errors

### ISSUE THREAD

**Issue by macias** [coursera-dl/coursera-dl#534]
*Sidenote: thank you very much for this script, I also write small one on my own, but the pace of changing format killed me. So thank you very much for your work!*

### Subject of the issue
When there is a http error and max tries of fetching is reached the script crashes.

### Your environment
* Operating System (name/version): openSUSE 13.2
* Python version: 3.4.1
* coursera-dl version: ? it does not say, but fetched right today 2016-06-26 (via pip)

### Steps to reproduce
Try to download a class "ml-classification", the link:
https://www.coursera.org/learn/ml-classification/home/week/1

The exception list is pretty long, because of all the unwinding, but the key thing is here:

The following error has occurred while downloading URL http://localhost:8888/notebooks/school/teaching/my_sandbox/module-8-boosting-assignment-1-scikit-learn-solution.ipynb#One-hot-encoding: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /notebooks/school/teaching/my_sandbox/module-8-boosting-assignment-1-scikit-learn-solution.ipynb (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f66046846a0>: Failed to establish a new connection: [Errno 111] Connection refused',))
If you want to ignore HTTP errors, please use "--ignore-http-errors" option

### Expected behaviour
The script should gracefully "jump over" that error (reporting it of course) and continue with the next material to download.

### Actual behaviour
I saw a crash with long stack trace:

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/cookies.py", line 91, in login
    r.raise_for_status()
  File "/home/mist/.local/lib/python3.4/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://class.coursera.org/ml-classification

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1278, in download_class
    return download_old_style_class(args, class_name)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1124, in download_old_style_class
    username=args.username, password=args.password)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/cookies.py", line 345, in get_cookies_for_class
    get_authentication_cookies(session, class_name, username, password)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/cookies.py", line 166, in get_authentication_cookies
    login(session, username, password, class_name=class_name)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/cookies.py", line 94, in login
    raise ClassNotFound(class_name)
coursera.cookies.ClassNotFound: ml-classification

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f66046846a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mist/.local/lib/python3.4/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/mist/.local/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /notebooks/school/teaching/my_sandbox/module-8-boosting-assignment-1-scikit-learn-solution.ipynb (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f66046846a0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mist/.local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==0.6.1', 'console_scripts', 'coursera-dl')()
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1304, in main
    if download_class(args, class_name):
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1281, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 1241, in download_on_demand_class
    failed_urls if args.ignore_http_errors else None
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 709, in download_lectures
    section_dir, skipped_urls, last_update)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/coursera_dl.py", line 578, in handle_resource
    downloader.download(url, lecture_filename, resume=resume)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "/home/mist/.local/lib/python3.4/site-packages/coursera/downloaders.py", line 324, in _start_download
    r = self.session.get(url, stream=True, headers=headers)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/mist/.local/lib/python3.4/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8888): Max retries exceeded with url: /notebooks/school/teaching/my_sandbox/module-8-boosting-assignment-1-scikit-learn-solution.ipynb (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f66046846a0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by balta2ar** [comment]
Did you try the suggestion that the script printed?
> If you want to ignore HTTP errors, please use "--ignore-http-errors" option

**Comment by macias** [comment]
Yes of course, this option works. My point is, that without that option program should not crash, just exit gracefuly. I hope you agree (there is no gain for the user except scaring him/her, and from operational point of view program stopped anyway).

**Comment by balta2ar** [comment]
Maybe I shouldn't have introduced that option in the first place and should have made that behavior by default... Hm. @rbrito What do you think?

**Comment by GlowingCrystallineEntity** [comment]
Another change I have ready to go, pending unrelated tests in #533 , writes the skipped and failed URLs to a file (as well as to stdout at the end of processing) so they can be referenced later.  With that, IMHO, I think defaulting to ignoring http errors would be fine.

btw, the ml-classification class mentioned here is a newer class with a lot of those "eventing" redirect links....

**Comment by arpitnot4u** [comment]
It should not download files except from coursera domain, or at least there should be a flag to on/off the same.

**Comment by rbrito** [comment]
Hi there.

On Sun, Jun 26, 2016 at 4:39 PM, Yuri Bochkarev
<notifications@github.com> wrote:
> Maybe I shouldn't have introduced that option in the first place and should
> have made that behavior by default... Hm. @rbrito What do you think?

Yet another 100% agreement. I think that we can release another
version (say, 0.7.0---what number would make sense if we tried to use
semantic versioning?) and make that the default.


Thanks,

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by rbrito** [comment]
Hi, @macias.

On Sun, Jun 26, 2016 at 4:18 PM, macias <notifications@github.com> wrote:
> Yes of course, this option works. My point is, that without that option program should not crash, just exit gracefuly. I hope you agree (there is no gain for the user except scaring him/her, and from operational point of view program stopped anyway).

I agree completely. I really don't like to have stack traces thrown on
me when I am using other people's programs.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br
