### ISSUE TITLE
Exception while downloading mentalhealth-002

### ISSUE THREAD

**Issue by diimdeep** [coursera-dl/coursera-dl#544]
Exception while downloading mentalhealth-002

### Your environment
* OSX El Capitan 10.11.5
* Python 3.5
* coursera-dl 0.6.1

### Steps to reproduce
`coursera-dl -u **** -p **** mentalhealth-002`

```
root[handle_resource] Downloading: mentalhealth-002/06_Lecture_5-_Families_caregiving_and_mental_illness/01_5.0_introduction_to_lecture_5_5-20.pdf
root[_start_download] Downloading http://www.anzjft.com/pages/articles/537.pdf -> mentalhealth-002/06_Lecture_5-_Families_caregiving_and_mental_illness/01_5.0_introduction_to_lecture_5_5-20.pdf
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTP connection (1): www.anzjft.com
root[download_lectures] The following error has occurred while downloading URL http://www.anzjft.com/pages/articles/537.pdf: HTTPConnectionPool(host='www.anzjft.com', port=80): Max retries exceeded with url: /pages/articles/537.pdf (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x103f74588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
root[download_lectures] If you want to ignore HTTP errors, please use "--ignore-http-errors" option
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 67, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x103f74588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.anzjft.com', port=80): Max retries exceeded with url: /pages/articles/537.pdf (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x103f74588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1304, in main
    if download_class(args, class_name):
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1278, in download_class
    return download_old_style_class(args, class_name)
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 1176, in download_old_style_class
    args.video_resolution)
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 709, in download_lectures
    section_dir, skipped_urls, last_update)
  File "/usr/local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 578, in handle_resource
    downloader.download(url, lecture_filename, resume=resume)
  File "/usr/local/lib/python3.5/site-packages/coursera/downloaders.py", line 50, in download
    self._start_download(url, filename, resume)
  File "/usr/local/lib/python3.5/site-packages/coursera/downloaders.py", line 324, in _start_download
    r = self.session.get(url, stream=True, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.anzjft.com', port=80): Max retries exceeded with url: /pages/articles/537.pdf (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x103f74588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by balta2ar** [comment]
@diimdeep There was an issue indeed. `--ignore-http-errors` option didn't do anything to old-style courses. I've fixed it in the master branch. Please install from github and use `--ignore-http-errors` option.
