### ISSUE TITLE
The error for  max retries

### ISSUE THREAD

**Issue by oliyiyi** [coursera-dl/coursera-dl#548]
when downloading the enrolled course, I met the the error below:

E:\cousera3>coursera-dl -u ******@gmail.com -p ****** --ignore-http-errors  --d
isable-url-skipping biostatistics
coursera_dl version 0.6.1
Downloading class: biostatistics
Starting new HTTPS connection (1): www.coursera.org
Traceback (most recent call last):
  File "E:\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==0.6.1', 'console_scripts', 'coursera-dl')()
  File "E:\Python27\lib\site-packages\coursera\coursera_dl.py", line 1304, in ma
in
    if download_on_demand_class(args, class_name):
  File "E:\Python27\lib\site-packages\coursera\coursera_dl.py", line 1189, in do
wnload_on_demand_class
    login(session, args.username, args.password)
  File "E:\Python27\lib\site-packages\coursera\cookies.py", line 121, in login
    headers=headers, allow_redirects=False)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 475, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "E:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "E:\Python27\lib\site-packages\requests\adapters.py", line 465, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.coursera.org', por
t=443): Max retries exceeded with url: /api/login/v3 (Caused by ProxyError('Cann
ot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection
.VerifiedHTTPSConnection object at 0x0000000003984A58>: Failed to establish a ne
w connection: [Errno 10061] ',)))

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version): win7
* Python version: 2.7.10
* coursera-dl version:0.6.1

**Comment by oliyiyi** [comment]
I got reason and fixed it, because of the proxy I set.

**Comment by balta2ar** [comment]
Closing.
