### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by pippocode** [coursera-dl/coursera-dl#557]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
"Could not authenticate: Cannot login on coursera.org"

### Your environment
* MACOS X "El Capitan"
* Python version: 3.5.1
* coursera-dl version: 0.6.1

>> ./coursera-dl/coursera-dl -u xxx -p xxx photography --debug
root[main] coursera_dl version 0.6.1
root[main] Downloading class: photography
root[download_class] Downloading new style (on demand) class photography
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[login] Forging cookie header: csrftoken=P55TWn6oDrPNn1zGmIMa; csrf2_token_PQojug86=7NWt2Vrmpsu4cVKRicY2sKTD.
requests.packages.urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org
requests.packages.urllib3.connectionpool[_make_request] "POST /api/login/v3 HTTP/1.1" 400 None
root[main] Could not authenticate: Cannot login on coursera.org.

Because some issues with El Capitan about python, I installed the script in virtualenv (python3.5 -m venv) and activate env with "source bin/activate".

thanks

**Comment by whyfuture** [comment]
Same here :(

**Comment by pippocode** [comment]
`#547 - see this`

Mmmh, this line is really differet than mine
`requests.packages.urllib3.connectionpool[make_request] "GET /crypto HTTP/1.1" 200 None`

I have a `400 None` and the password is right  :(

**Comment by Macfly** [comment]
same issue but on windows 10...

**Comment by balta2ar** [comment]
@pippocode This comment (https://github.com/coursera-dl/coursera-dl/issues/508#issuecomment-226842459) is outdated meaning that the code in master has changed. If you use the latest version from github, you should be fine.

**Comment by battimaglio** [comment]
No luck

```>> sudo pip2.7 install --upgrade coursera-dl
The directory '/Users/foo/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/foo/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting coursera-dl
Collecting beautifulsoup4>=4.1.3 (from coursera-dl)
  Downloading beautifulsoup4-4.5.0-py2-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 162kB/s
Collecting urllib3>=1.10 (from coursera-dl)
  Downloading urllib3-1.16-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 343kB/s
Collecting requests>=2.4.3 (from coursera-dl)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 271kB/s
Collecting keyring>=4.0 (from coursera-dl)
  Downloading keyring-9.3.1-py2.py3-none-any.whl
Collecting html5lib>=1.0b2 (from coursera-dl)
Collecting pyasn1>=0.1.7 (from coursera-dl)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Requirement already up-to-date: six>=1.5.0 in /Users/foo/Library/Python/2.7/lib/python/site-packages (from coursera-dl)
Collecting setuptools>=18.5 (from html5lib>=1.0b2->coursera-dl)
  Downloading setuptools-25.1.0-py2.py3-none-any.whl (442kB)
    100% |████████████████████████████████| 450kB 324kB/s
Collecting webencodings (from html5lib>=1.0b2->coursera-dl)
Installing collected packages: beautifulsoup4, urllib3, requests, keyring, setuptools, webencodings, html5lib, pyasn1, coursera-dl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 493, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 383, in make_multiple
    filenames.extend(self.make(specification, options))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 372, in make
    self._make_script(entry, filenames, options=options)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 276, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 250, in _write_script
    self._fileop.write_binary_file(outname, script_bytes)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/util.py", line 405, in write_binary_file
    with open(path, 'wb') as f:
IOError: [Errno 1] Operation not permitted: '/bin/keyring'
```

**Comment by balta2ar** [comment]
That's permission issues, not authentication. Try `pip install --user` option.

**Comment by balta2ar** [comment]
@battimaglio If you install coursera-dl into virtualenv, do not use sudo. `pip install` will place files into virtualenv if it's properly activated.

**Comment by balta2ar** [comment]
This should be working in 0.7.0.
