### ISSUE TITLE
Coursera crashes when trying to download a course

### ISSUE THREAD

**Issue by deepakjois** [coursera-dl/coursera-dl#581]
### Subject of the issue
Coursera crashes when trying to download this course: https://www.coursera.org/learn/ideas

### Your environment
* Ubuntu and OS X
* Python 3
* coursera-dl version: latest at 759fe78  

### Steps to reproduce

Please see the command below. I ran it in a virtualenv with the latest 

### Expected behaviour
coursera-dl should download the course

### Actual behaviour

```
$> coursera-dl -n --aria2 -- ideas
…
Processing lecture         4-2-transforming-everyday-objects (lecture)
Processing lecture         4-3-teaching-with-themes-transforming-everyday-objects (lecture)
Processing section     part-ii-look-learn
Processing lecture         4-4-slideshow (slideshow)
Unsupported typename "slideshow" in lecture "4-4-slideshow"
Processing lecture         4-4-slideshow-mobile-friendly-version (supplement)
Traceback (most recent call last):
  File "/home/ubuntu/coursera/coursera/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 235, in main
    error_occured, completed = download_class(args, class_name)
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 210, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 138, in download_on_demand_class
    args.download_quizzes)
  File "/home/ubuntu/coursera/coursera/coursera/extractors.py", line 56, in get_modules
    download_quizzes)
  File "/home/ubuntu/coursera/coursera/coursera/extractors.py", line 145, in _parse_on_demand_syllabus
    lecture['id'])
  File "/home/ubuntu/coursera/coursera/coursera/api.py", line 818, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
  File "/home/ubuntu/coursera/coursera/coursera/api.py", line 158, in __call__
    return soup.prettify()
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/element.py", line 1200, in prettify
    return self.decode(True, formatter=formatter)
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/__init__.py", line 501, in decode
    indent_level, eventual_encoding, formatter)
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/element.py", line 1166, in decode
    indent_contents, eventual_encoding, formatter)
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/element.py", line 1235, in decode_contents
    formatter))
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/element.py", line 1166, in decode
    indent_contents, eventual_encoding, formatter)
  File "/home/ubuntu/coursera/my-coursera/lib/python3.5/site-packages/bs4/element.py", line 1244, in decode_contents
    return ''.join(s)
MemoryError
```

**Comment by balta2ar** [comment]
@deepakjois Thanks for the report. Even though I can't reproduce the crash locally, it is evident that the script consumes a hell lot of memory. In my case it's `1093960maxresident)k`. Could you run it as follows to confirm that:
```
/usr/bin/time coursera-dl -n --aria2 -- ideas
```

Also, how much RAM do you have available in the script environment? At some point in time it stores too much data in memory. We need to revise that.

**Comment by deepakjois** [comment]
Yes, I wanted to put it in the initial report that it looked like some sort of memory related issue.

I have 16GB of RAM on my mac, which ought to be more than enough. So I am a bit surprised that it is not enough even on that. Or is it the case that my Python interpreter is limiting the amount of RAM that the program has access to?

Anyway, here is the output of running it with `time` on Mac. Not sure what you are looking for. Another thing is that it fails slightly differently on my Mac, than on Ubuntu. Look at the stack trace below.

```
$ /usr/bin/time   ../coursera-dl/coursera-dl -n --aria2 -- ideas
coursera_dl version 0.8.0
Downloading class: ideas (1 / 1)
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/ideas?showLockedItems=true (22837 bytes)
Parsing syllabus of on-demand course. This may take some time, please be patient ...
Processing module  module-1-introduction-to-art-ideas-teaching-with-themes
Processing section     part-i-overview
Processing lecture         1-1-introduction-to-art-ideas-teaching-with-themes (supplement)
Processing lecture         1-2-introduction-to-art-ideas (lecture)
Processing lecture         1-3-introduction-to-teaching-with-themes (lecture)
Processing section     part-ii
Processing lecture         1-4-required-readings-additional-resources (supplement)
Processing module  module-2-places-spaces
Processing section     part-i-overview
Processing lecture         2-1-introduction-to-places-spaces (supplement)
Processing lecture         2-2-places-spaces (lecture)
Processing lecture         2-3-teaching-with-themes-places-spaces (lecture)
Processing section     part-ii-look-learn
Processing lecture         2-4-slideshow (slideshow)
Unsupported typename "slideshow" in lecture "2-4-slideshow"
Processing lecture         2-4-slideshow-mobile-friendly-version (supplement)
Starting new HTTPS connection (1): d3c33hcgiwev3.cloudfront.net
Processing lecture         2-5-vincent-van-gogh-the-starry-night-1889 (lecture)
Processing lecture         2-6-piet-mondrian-broadway-boogie-woogie-1942-43 (lecture)
Processing lecture         2-7-gordon-matta-clark-bingo-1974 (lecture)
Processing lecture         2-8-andrew-wyeth-christinas-world-1948 (lecture)
Processing lecture         2-9-salvador-dali-the-persistence-of-memory-1931 (lecture)
Processing lecture         2-10-claude-monet-water-lilies-1914-26 (lecture)
Processing lecture         2-11-rachel-whiteread-water-tower-1998 (lecture)
Processing lecture         2-12-edward-hopper-house-by-the-railroad-1925 (lecture)
Processing lecture         2-13-louis-i-kahn-sher-e-bangla-nagar-capital-of-bangladesh-dhaka-bangladesh (lecture)
Processing section     part-iii-read-review
Processing lecture         2-14-required-readings-additional-resources (supplement)
Processing lecture         quiz (exam)
Processing module  module-3-art-identity
Processing section     part-i-overview
Processing lecture         3-1-introduction-to-art-identity (supplement)
Processing lecture         3-2-art-identity (lecture)
Processing lecture         3-3-teaching-with-themes-art-identity (lecture)
Processing section     part-ii-look-learn
Processing lecture         3-4-slideshow (slideshow)
Unsupported typename "slideshow" in lecture "3-4-slideshow"
Processing lecture         3-4-slideshow-mobile-friendly-version (supplement)
Processing lecture         3-5-frida-kahlo-self-portait-with-cropped-hair-1940 (lecture)
Processing lecture         3-6-andy-warhol-gold-marilyn-monroe-1962 (lecture)
Processing lecture         3-7-pablo-picasso-girl-before-a-mirror-1932 (lecture)
Processing lecture         3-8-marc-chagall-i-and-the-village-1911 (lecture)
Processing lecture         3-9-henri-matisse-the-red-studio-1911 (lecture)
Processing lecture         3-10-rineke-dijkstra-almerisa-series-1994-2008 (lecture)
Processing section     part-iii-read-review
Processing lecture         3-11-required-readings-additional-resources (supplement)
Processing lecture         quiz (exam)
Processing module  module-4-transforming-everyday-objects
Processing section     part-i-overview
Processing lecture         4-1-introduction-to-transforming-everyday-objects (supplement)
Processing lecture         4-2-transforming-everyday-objects (lecture)
Processing lecture         4-3-teaching-with-themes-transforming-everyday-objects (lecture)
Processing section     part-ii-look-learn
Processing lecture         4-4-slideshow (slideshow)
Unsupported typename "slideshow" in lecture "4-4-slideshow"
Processing lecture         4-4-slideshow-mobile-friendly-version (supplement)
        Traceback (most recent call last):
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 451, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 502, in read_chunked
    self._update_chunk_length()
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 455, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 353, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 530, in read_chunked
    self._original_response.close()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../coursera-dl/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/coursera_dl.py", line 235, in main
    error_occured, completed = download_class(args, class_name)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/coursera_dl.py", line 210, in download_class
    return download_on_demand_class(args, class_name)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/coursera_dl.py", line 138, in download_on_demand_class
    args.download_quizzes)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/extractors.py", line 56, in get_modules
    download_quizzes)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/extractors.py", line 145, in _parse_on_demand_syllabus
    lecture['id'])
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/api.py", line 818, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/api.py", line 156, in __call__
    self._convert_markup_images(soup)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/api.py", line 211, in _convert_markup_images
    self._asset_retriever(asset_ids)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/api.py", line 362, in __call__
    reply = get_reply(self._session, url)
  File "/Users/deepak/code/personal/my-coursera/coursera-dl/coursera/network.py", line 44, in get_reply
    reply = session.send(prepared_request)
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/sessions.py", line 628, in send
    r.content
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/deepak/code/personal/my-coursera/lib/python3.5/site-packages/requests/models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
      221.80 real         6.49 user         1.38 sys
```

**Comment by deepakjois** [comment]
I can confirm that on my Mac, the memory tops out at 500Mb, after which the program crashes. I can’t really explain why it cannot use more than 500Mb, when there is plenty of memory available.

**Comment by balta2ar** [comment]
Judging by this line:
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
I think it might be your internet connection. And yes, these seem to be two different issues. Is this the only class where it happens?

**Comment by deepakjois** [comment]
Happens with `mindfullness` as well.

I  think they are related though… because if you see, this part of the stack trace is the same:

```
  File "/home/ubuntu/coursera/coursera/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 235, in main
    error_occured, completed = download_class(args, class_name)
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 210, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/ubuntu/coursera/coursera/coursera/coursera_dl.py", line 138, in download_on_demand_class
    args.download_quizzes)
  File "/home/ubuntu/coursera/coursera/coursera/extractors.py", line 56, in get_modules
    download_quizzes)
  File "/home/ubuntu/coursera/coursera/coursera/extractors.py", line 145, in _parse_on_demand_syllabus
    lecture['id'])
  File "/home/ubuntu/coursera/coursera/coursera/api.py", line 818, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
```

**Comment by deepakjois** [comment]
Happens with `mindfulness` as well

**Comment by deepakjois** [comment]
From what I can see, the course modules include something called a ‘mobile-friendly’ slideshows, which is of type `supplement`. These slideshows contain big images. Example: https://www.coursera.org/learn/ideas/supplement/Dl9Xn/2-4-slideshow-mobile-friendly-version

It seems that the supplement extraction is taking up lots of memory because it is trying to inline images (and other assets). We could use a better strategy to capture an offline version of the supllements, than trying to stuff it into the JSON file that is generated by the extraction phase.

**Comment by deepakjois** [comment]
I commented out the supplement extraction portion, and things start working just fine:

```diff
diff --git a/coursera/extractors.py b/coursera/extractors.py
index a4e8ade..25b7da5 100644
--- a/coursera/extractors.py
+++ b/coursera/extractors.py
@@ -141,8 +141,9 @@ class CourseraExtractor(PlatformExtractor):
                             video_resolution, assets)
 
                     elif typename == 'supplement':
-                        links = course.extract_links_from_supplement(
-                            lecture['id'])
+                        logging.info('Ignoring supplement"')
+                        #links = course.extract_links_from_supplement(
+                        #    lecture['id'])
 
                     elif typename in ('gradedProgramming', 'ungradedProgramming'):
                         links = course.extract_links_from_programming(lecture['id'])

```

**Comment by deepakjois** [comment]
I don’t have a lot of context, but I had a suggestion just looking at the code. How about taking this snippet of code in workflow.py:

```python
if url.startswith(IN_MEMORY_MARKER):
  page_content = url[len(IN_MEMORY_MARKER):]
  logging.info('Saving page contents to: %s', lecture_filename)
  with codecs.open(lecture_filename, 'w', 'utf-8') as file_object:
    file_object.write(page_content)
```

And using it in the extraction phase instead, to write the contents instead of storing them in the JSON file?

**Comment by balta2ar** [comment]
Your suggestion is valid but the devil is in the details. As you could have noticed, there are basically two large stages in the script: parsing and downloading. The parsing stage produces a structure with nested lists and dictionaries that describes the content to download on the later stage. In parsing, we don't know yet the files names where we will store content to. They are generated during the download stage.

The issue that you have encountered is the result of a quick hack. When I was thinking on how to store assets offline, I decided to simply inline images into HTML. A better way could be to link images in HTML and save images to disk. But again, we don't know the target filenames when parsing. A possible solution might be to return lazy handlers from parsing stage which when are called in download stage, request the necessary resources of a page.

I'm explaining all this to show that I think it's not just a matter of fixing two lines of code. A better design is needed here and it requires some thought.

**Comment by deepakjois** [comment]
> I'm explaining all this to show that I think it's not just a matter of fixing two lines of code. A better design is needed here and it requires some thought.

I agree it is not a matter of fixing two lines of code, and that’s why I said I don’t have context. I did not mean my suggestion literally. It was more about shifting the logic from one place to another. 

I realise now that during the parsing stage, the target filename is not known, which is a bit unfortunate.
