### ISSUE TITLE
"socket.gaierror [Errno- 2]: Name or service not found" while listing courses

### ISSUE THREAD

**Issue by manas271196** [coursera-dl/coursera-dl#582]
Getting this error while listing courses:

* Operating System (name/version): Ubuntu 14.04
* Python version: 3.4
* coursera-dl version: 0.8.0

command:./coursera-dl -u username -p password --list-courses

Output:

Listing enrolled courses
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Starting new HTTPS connection (1): www.coursera.org
Traceback (most recent call last):
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f564da5f3c8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f564da5f3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 228, in main
    list_courses(args)
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 107, in list_courses
    courses = extractor.list_courses()
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/extractors.py", line 45, in list_courses
    return course.list_courses()
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/api.py", line 428, in list_courses
    reply = get_page(self._session, OPENCOURSE_MEMBERSHIPS, json=True)
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/network.py", line 85, in get_page
    reply = get_reply(session, url, post=post, data=data, headers=headers)
  File "/home/man1234/Coursera/my-coursera/coursera-dl/coursera/network.py", line 44, in get_reply
    reply = session.send(prepared_request)
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/man1234/Coursera/my-coursera/lib/python3.4/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f564da5f3c8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by balta2ar** [comment]
Closing as outdated. Feel free to comment if you're still having problems.
