### ISSUE TITLE
Coursera-dl error

### ISSUE THREAD

**Issue by Tim541** [coursera-dl/coursera-dl#583]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.~/Desktop/coursera-dl-master$ coursera-dl -u magicmike541@gmail.com -p xxxxxxxxxxx --resume preserving-cultural-heritage
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography

### Your environment
* Operating System (name/version): Ubuntu 14.04
* Python version:2.7.1
* coursera-dl version:latest

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by vossad01** [comment]
Can you provide more details about your setup and how you installed `coursera-dl`?

You indicate "Python version:2.7.1"; however,

> File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in
working_set = WorkingSet._build_master()

Indicates you seem to be running under Python 3.

**Comment by balta2ar** [comment]
Closing due to inactivity. Feel free to comment if you're still having issues with this one.
