### ISSUE TITLE
Can't resume download. 

### ISSUE THREAD

**Issue by moha23** [coursera-dl/coursera-dl#589]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Can't resume download. 
I installed everything via pip and also doing everything using virtualenv. I am trying to download the Machine Learning course by Andrew Ng. It started downloading fine but then I lost my WiFi connection and it got stuck. When I got my connection back the downloading didn't resume on its own and so I used _ctrl +C_ and then tried resuming using `coursera-dl -u <user> -p <pass> --resume sdn1-001`. However, this the error I got :  
>Traceback (most recent call last):
 > File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==0.8.0', 'console_scripts', 'coursera-dl')()
  >File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  >File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  >File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  >File "/Library/Python/2.7/site-packages/coursera/coursera_dl.py", line 83, in <module>
    assert V(six.__version__) >= V('1.5'), "Upgrade six!" + _SEE_URL
>AssertionError: Upgrade six! See https://github.com/coursera-dl/coursera/issues/139

I checked issue 139, and other related issues. Tried the _sudo easy install six_ option as well, but it still gives the same error. Can something be done? Or do I have to restart the whole process? That would be a bummer because my internet connection isn't that good.

### Your environment
* Operating System (name/version): OS X Yosemite
* Python version:2.7.10
* coursera-dl version: 0.8.0

**Comment by moha23** [comment]
Update : 
So I tried downloading again and even though there was no interruption in my wifi connection, the downloading has been stuck for quite a while. Here's a screenshot. 
<img width="1280" alt="screen shot 2017-03-06 at 9 40 13 am" src="https://cloud.githubusercontent.com/assets/10138421/23596391/0d4da312-0250-11e7-8449-2ed3e2165f3a.png">

**Comment by balta2ar** [comment]
@moha23 Are you sure this isn't because of the internet connection? Are you still having issue with that?

**Comment by balta2ar** [comment]
I'm closing this due to inactivity. Feel free to comment if you're still having issues on this one.
