### ISSUE TITLE
Error when downloading video in Mac

### ISSUE THREAD

**Issue by banpie** [coursera-dl/coursera-dl#601]
### Subject of the issue

Error when downloading video in Mac

### Your environment
* Operating System (name/version): Mac
* Python version: 2.6
* coursera-dl version: 

### Steps to reproduce

`cousera-dl -u xxx -p xxx communication`

### Expected behaviour

Download video 

### Actual behaviour

```
Starting new HTTPS connection (1): www.coursera.org
Logged in on coursera.org.
Downloaded https://www.coursera.org/api/opencourse.v1/course/communication?showLockedItems=true (25128 bytes)
Parsing syllabus of on-demand course. This may take some time, please be patient ...
Processing module  the-beginnings-of-communication-science
Processing section     an-introduction-to-communication-science
Processing lecture         welcome-to-introduction-to-communication-science (supplement)
Starting new HTTPS connection (1): d3c33hcgiwev3.cloudfront.net
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1039e8ac8>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /rt1kUOmzEeSAfyIACx4F4g_0e9a812dd778fb19fdea7985aa7382f2_commscience-images-syllabus.png?Expires=1492387200&Signature=OlHrXn12iQfjrk3MLQstu-kaLSgv3wifVwHw6dc-GQRgwb~nE4IO4IN1mLsP7D8UN7mkRj3qnLP~Hjy0HJ1vTp9cf1-XPLzqJAUS7tigE7olJPE5JvGQXqfMhAXs~ggJ2ka9YF0ySLa55wJc9iiaT3DBkNIwP9S2-6-Uuk5RoLY_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1039e8ac8>: Failed to establish a new connection: [Errno 65] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/coursera-dl", line 11, in <module>
    load_entry_point('coursera-dl==0.7.0', 'console_scripts', 'coursera-dl')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/coursera_dl.py", line 221, in main
    if download_class(args, class_name):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/coursera_dl.py", line 198, in download_class
    return download_on_demand_class(args, class_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/coursera_dl.py", line 132, in download_on_demand_class
    args.download_quizzes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/extractors.py", line 56, in get_modules
    download_quizzes)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/extractors.py", line 136, in _parse_on_demand_syllabus
    lecture['id'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/api.py", line 801, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/api.py", line 152, in __call__
    self._convert_markup_images(soup)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/api.py", line 207, in _convert_markup_images
    self._asset_retriever(asset_ids)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/api.py", line 358, in __call__
    reply = get_reply(self._session, url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coursera/network.py", line 44, in get_reply
    reply = session.send(prepared_request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /rt1kUOmzEeSAfyIACx4F4g_0e9a812dd778fb19fdea7985aa7382f2_commscience-images-syllabus.png?Expires=1492387200&Signature=OlHrXn12iQfjrk3MLQstu-kaLSgv3wifVwHw6dc-GQRgwb~nE4IO4IN1mLsP7D8UN7mkRj3qnLP~Hjy0HJ1vTp9cf1-XPLzqJAUS7tigE7olJPE5JvGQXqfMhAXs~ggJ2ka9YF0ySLa55wJc9iiaT3DBkNIwP9S2-6-Uuk5RoLY_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1039e8ac8>: Failed to establish a new connection: [Errno 65] No route to host',))

```

**Comment by balta2ar** [comment]
There is nothing we can do in your case. It's your network's connectivity issues. If you're behind Chinese firewall, try accessing coursera over VPN.
