### ISSUE TITLE
can't download courses after upgrading(ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None)

### ISSUE THREAD

**Issue by ShiChJ** [coursera-dl/coursera-dl#609]
I can't download courses after using this command.
`pip install --upgrade coursera-dl`
I thought it should have updated coursera-dl to the latest version, but something was wrong when I tried to download courses:

coursera_dl version 0.8.0
Downloading class: dataviz-design (1 / 6)
Connection pool is full, discarding connection: www.coursera.org
Traceback (most recent call last):
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\timeout.py", line 124, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'Timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\1\AppData\Local\Continuum\Anaconda3\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 235, in main
    error_occured, completed = download_class(args, class_name)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 210, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 125, in download_on_demand_class
    extractor = CourseraExtractor(session, args.username, args.password)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\coursera\extractors.py", line 31, in __init__
    login(session, username, password)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\coursera\cookies.py", line 145, in login
    headers=headers, allow_redirects=False)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\requests\sessions.py", line 570, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\requests\sessions.py", line 523, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "c:\users\1\appdata\local\continuum\anaconda3\lib\site-packages\urllib3\util\timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.

Can anyone fix this issue? Please help. Thanks a lot.

**Comment by ShiChJ** [comment]
my environment

- Windows 10
- Python 3.6
- coursera-dl version: 0.8.0

**Comment by kohaugustine** [comment]
I'm facing the same problem too, but on a linux machine:

Ubuntu 16.04 
Python 3.5
coursera-dl 0.8.0

and all the package requirements are already satisfied in my conda environment.

**Comment by 32103210** [comment]
me too, facing the same problem 
window7
python 3.5
coursera-dl 0.8.0

**Comment by alexisrobin** [comment]
Same problem right here.
windows10
python3.5
coursera-dl 0.8.0

**Comment by varunarang** [comment]
Hi all,
After some looking around, I figured that the problem was with the version of _requests_ library, I downgraded the version to **requests==2.4.3** in requrements.txt and re-installed the virtualenv setup and it worked for me.

Hope that helps

**Comment by varunarang** [comment]
I haven't submitted a PR because haven't tested it after changing the version thoroughly. But if some can, nothing like that.

**Comment by ShiChJ** [comment]
@varunarang It really worked! Thank you!

**Comment by MortezaRamezani** [comment]
Version 0.8.0 (on Linux (ubuntu) at least) needs requests==2.10.0 and downgrading requests to 2.10.0 just fixed the problem. Thanks @varunarang !

**Comment by balta2ar** [comment]
This a bug in upstream requests, see https://github.com/requests/requests/issues/4101#issuecomment-304742865
Please upgrade once again to `requests==2.17.3`.

**Comment by olbapjose** [comment]
Windows 10, python 2.7.13. Tried the latest version of requests and also version 2.17.3, but neither worked. Tried requests version 2.10.0 and it worked :-)
