### ISSUE TITLE
I cant run coursera-dl

### ISSUE THREAD

**Issue by ahmadabd** [coursera-dl/coursera-dl#612]
HI 
When I run coursera-dl by:
` coursera-dl -u username -p password course_name`
It shows me this error:

> Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==0.9.0', 'console_scripts', 'coursera-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 57, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by ahmadabd** [comment]
I solved it :)

**Comment by balta2ar** [comment]
@ahmadabd Great! Could you please write how you solved it so that those who find your issue later could benefit from that? Thanks.

**Comment by ahmadabd** [comment]
Yes, sure
_base feauture of some of my python modules like html5lib, beautifulsoup4 was ruined
I solved it by this commands:
`sudo pip install --upgrade html5lib`
`sudo pip install --upgrade beautifulsoup4`

**Comment by imdoneok** [comment]
I upgraded these but still have this problem

**Comment by poojasaxena** [comment]
having the same issue and upgrading these packages did not help!!
