### ISSUE TITLE
Coursera-dl not downloading

### ISSUE THREAD

**Issue by lakelord** [coursera-dl/coursera-dl#618]
Problem Downloading Coursera

Python 2.7
Linux Mint 18.2

Traceback message

Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 659, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 672, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 862, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.22 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('urllib3<1.22,>=1.21.1'), set(['requests']))

**Comment by zenny** [comment]
Read my reply at https://github.com/coursera-dl/coursera-dl/issues/614#issuecomment-320922855 if it helps.

**Comment by EMCP** [comment]
please add backticks to make your code more readable

**Comment by balta2ar** [comment]
You could try 1) using pip3 instead of pip2 2) using virtualenv as suggested above. Resolving for now, ping back if you have issues.
