### ISSUE TITLE
Can't install Coursera-dl with python3 pip

### ISSUE THREAD

**Issue by lakelord** [coursera-dl/coursera-dl#619]
Linux Mint 18.2
Python 3

~ $ sudo -H pip3 install coursera-dl
Collecting coursera-dl
  Using cached coursera-dl-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9sd1ylgt/coursera-dl/setup.py", line 62, in <module>
        'Generate README.rst from README.md via pandoc!\n\nExample: '
      File "/tmp/pip-build-9sd1ylgt/coursera-dl/setup.py", line 52, in read_file
        lines = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24109: ordinal not in range(128)

**Comment by zenny** [comment]
@lakelord Had similar problem, but worked well with manual installation as explained at:

https://github.com/coursera-dl/coursera-dl/issues/614#issuecomment-320922855

Hope this helps.

**Comment by balta2ar** [comment]
I consider it resolved then. Ping back if you still have issues.
