### ISSUE TITLE
ImportError: No module named bs4 in debian jessie python 3.4.2

### ISSUE THREAD

**Issue by zenny** [coursera-dl/coursera-dl#620]
Hi again,

There is an issue with debian jessie with python3 (v3.4.2).

The installation goes well:

```
(my-coursera)root@HOST my-coursera/coursera# pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.1.3 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests>=2.10.0 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.0 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): urllib3>=1.10 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): keyring>=4.0 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): configargparse>=0.12.0 in /shared/projects/my-coursera/lib/python3.4/site-packages (from -r requirements.txt (line 7))
Cleaning up...
```

But when I try to run with coursera-dl.conf in the same directory, the script reports:

```
(my-coursera)root@HOST my-coursera/coursera# sudo -u www-data ./coursera-dl --path=/shared/projects/my-coursera/courses <COURSENAME> 
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/shared/projects/my-coursera/coursera/coursera/coursera_dl.py", line 57, in <module>
    import bs4
ImportError: No module named bs4

```
Any clues?

Cheers,
/z

**Comment by zenny** [comment]
Though not desirable, it worked when executed without the different user prefix `sudo -u www-data`

` ./coursera-dl --path=/shared/projects/my-coursera/courses <COURSENAME> `

Is there alternative way to execute the command as a different user so that I do not have to change the ownership of files everytime I run coursera-dl script?

**Comment by balta2ar** [comment]
@zenny The other user should have that package (bs4) available in its PYTHONPATH. What you could do is install coursera-dl into that user's home directory, e.g.:
```
sudo -u www-data pip install --user coursera-dl
```
