### ISSUE TITLE
PermissionError: [Errno 13] Permission denied (can't download)

### ISSUE THREAD

**Issue by b1azk0** [coursera-dl/coursera-dl#621]
### Subject of the issue
Trying to download a course ends up with errror messages:

Traceback (most recent call last):
  File "/home/user/.local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 237, in main
    error_occured, completed = download_class(args, class_name)
  File "/home/user/.local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 212, in download_class
    return download_on_demand_class(args, class_name)
  File "/home/user/.local/lib/python3.5/site-packages/coursera/coursera_dl.py", line 139, in download_on_demand_class
    args.mathjax_cdn_url
  File "/home/user/.local/lib/python3.5/site-packages/coursera/extractors.py", line 56, in get_modules
    download_quizzes, mathjax_cdn_url)
  File "/home/user/.local/lib/python3.5/site-packages/coursera/extractors.py", line 103, in _parse_on_demand_syllabus
    with open('%s-syllabus-raw.json' % course_name, 'w') as file_object:
PermissionError: [Errno 13] Permission denied: 'statistical-inferences-syllabus-raw.json'

### Your environment
* Operating System (name/version): Ubuntu 17.04
* Python version: Python 2.7.13 (i've run pip3 and istalled python3, but for some reason this version pops up when I type python -V)
* coursera-dl version: 0.9.0

### Steps to reproduce
Simply running

coursera-dl -u xxx -p xxx statistical-inferences
or
coursera-dl -u xxx -p xxx advanced-r

both end up with
PermissionError: [Errno 13] Permission denied: 'advanced-r-syllabus-parsed.json'

I'm a linux newbie and can't think of any solution CLI releated.

**Comment by b1azk0** [comment]
solved by running
`sudo -H pip3 install coursera-dl`
and then
`sudo coursera-dl -u xxx -p xxx statistical-inferences`

**Comment by balta2ar** [comment]
Closing then.
