### ISSUE TITLE
Error no route to host

### ISSUE THREAD

**Issue by eileenxz** [coursera-dl/coursera-dl#622]
### OSError: [Errno 65] No route to host

Could not download videos of some classes.
### Your environment

- Operating System (name/version):macOS Sierra 10.12.6
- Python version:3.5
- coursera-dl version:0.9
- from China and using proxies

### Steps to reproduce
I've downloaded videos successfully using

    coursera-dl -u xxx -p xxx -f "mp4" data-cleaning

however, when I try to download another (enrolled) class using a similiar sentence

    coursera-dl -u xxx -p xxx -f "mp4" exploratory-data-analysis

 But I've been getting the following error.

Downloaded https://www.coursera.org/api/opencourse.v1/course/exploratory-data-analysis?showLockedItems=true (22665 bytes)

Parsing syllabus of on-demand course. This may take some time, please be patient ...

Processing module  week-1

Processing section     background-material

Processing lecture         welcome-to-exploratory-data-analysis (supplement)

Processing lecture         syllabus (supplement)

Processing lecture         pre-course-survey (supplement)

Processing lecture         introduction (lecture)

Processing lecture         exploratory-data-analysis-with-r-book (supplement)

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn

    (self.host, self.port), self.timeout, **extra_kw)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection

    raise err

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection

    sock.connect(sa)

OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen

    chunked=chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request

    self._validate_conn(conn)

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn

    conn.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 284, in connect

    conn = self._new_conn()

  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn

    self, "Failed to establish a new connection: %s" % e)

urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10384d7f0>: Failed to establish a new connection: [Errno 65] No route to host

**Comment by balta2ar** [comment]
Try this: https://github.com/coursera-dl/coursera-dl/issues/606#issuecomment-305698809

**Comment by eileenxz** [comment]
It works! Thanks a lot!
