### ISSUE TITLE
Python Library Not Imported 

### ISSUE THREAD

**Issue by mattborhan** [coursera-dl/coursera-dl#637]
Hi 

I'm trying to set up my web-scraping engine with python. I need urllib2 for this project but python doesn't import it. Any idea to solve it is much appreciated. here is what it returns:

**********************************
Traceback (most recent call last):

  File "C:\Users\UserPc\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-40-97993c5a1c61>", line 1, in <module>
    import urllib2

  File "C:\Users\UserPc\AppData\Local\Enthought\Canopy\edm\envs\User\lib\urllib2.py", line 254
    raise AttributeError, attr
                        ^
SyntaxError: invalid syntax

**Comment by balta2ar** [comment]
How is this related to coursera-dl project? Please use more appropriate places to ask general questions about Python and its ecosystem, for example stackoverflow.com.
