### ISSUE TITLE
 Failed building wheel for coursera-dl

### ISSUE THREAD

**Issue by dreamsline** [coursera-dl/coursera-dl#642]
Collecting coursera-dl
  Using cached coursera-dl-0.9.0.tar.gz
Requirement already satisfied: beautifulsoup4>=4.1.3 in e:\python-3.6.2\lib\site-packages (from coursera-dl)
Requirement already satisfied: requests>=2.10.0 in e:\python-3.6.2\lib\site-packages (from coursera-dl)
Requirement already satisfied: six>=1.5.0 in e:\python-3.6.2\lib\site-packages (from coursera-dl)
Requirement already satisfied: urllib3>=1.10 in e:\python-3.6.2\lib\site-packages (from coursera-dl)
Requirement already satisfied: pyasn1>=0.1.7 in e:\python-3.6.2\lib\site-packages (from coursera-dl)
Collecting keyring>=4.0 (from coursera-dl)
  Using cached keyring-10.6.0-py2.py3-none-any.whl
Collecting configargparse>=0.12.0 (from coursera-dl)
  Using cached ConfigArgParse-0.12.0.tar.gz
Requirement already satisfied: certifi>=2017.4.17 in e:\python-3.6.2\lib\site-packages (from requests>=2.10.0->coursera-dl)
Requirement already satisfied: idna<2.7,>=2.5 in e:\python-3.6.2\lib\site-packages (from requests>=2.10.0->coursera-dl)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in e:\python-3.6.2\lib\site-packages (from requests>=2.10.0->coursera-dl)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in e:\python-3.6.2\lib\site-packages (from keyring>=4.0->coursera-dl)
Building wheels for collected packages: coursera-dl, configargparse
  Running setup.py bdist_wheel for coursera-dl ... error
  Failed building wheel for coursera-dl
  Running setup.py clean for coursera-dl
  Running setup.py bdist_wheel for configargparse ... error
  Failed building wheel for configargparse
  Running setup.py clean for configargparse
Failed to build coursera-dl configargparse
Installing collected packages: keyring, configargparse, coursera-dl
  Running setup.py install for configargparse ... error
Exception:
Traceback (most recent call last):
  File "e:\python-3.6.2\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 47: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\python-3.6.2\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "e:\python-3.6.2\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "e:\python-3.6.2\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "e:\python-3.6.2\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "e:\python-3.6.2\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "e:\python-3.6.2\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 47: invalid continuation byte

**Comment by balta2ar** [comment]
Do you still have this problem? I've build `python setup.py bdist` successfully on windows 10 with the latest master.
