### ISSUE TITLE
Unable to install via pip; exception on uninstalling six-1.4.1-py2.7.egg-info'

### ISSUE THREAD

**Issue by pdigioia** [coursera-dl/coursera-dl#643]
### Subject of the issue
sudo pip install coursera-dl
... 
Successfully built coursera-dl
Installing collected packages: six, pyasn1, keyring, coursera-dl
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-HcgWYe-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

### Your environment
* Operating System (name/version): OSX 10.13.3
* Python version: python --version   ->   Python 2.7.10
* coursera-dl version: (on installation)

### Steps to reproduce
sudo pip install coursera-dl

**Comment by balta2ar** [comment]
Could you try the same but with pip3? That would hopefully make it use Python3.

Alternatively, you may want to install coursera-dl into virtualenv: https://github.com/coursera-dl/coursera-dl#alternative-installation-method-for-unix-systems

**Comment by balta2ar** [comment]
Closing due to no activity. I assume you got around that, if not, feel free to comment.
