### ISSUE TITLE
Creation of folders with ':' in the folder name in Windows

### ISSUE THREAD

**Issue by sonapraneeth-a** [coursera-dl/coursera-dl#648]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Creation of folders with ':' in the folder name in Windows
When trying to download python notebooks for the course neural-networks-deep-learning, there is a .ipynb file which has ':' in its name. Due to that colon, which determines the folder to created locally

### Your environment
* Operating System (name/version):
    - Windows 10
* Python version:
    - 3.6.3
* coursera-dl version:
    - 0.10.0

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
   - Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
    - Yes
* What is the course that you are trying to access?
   - neural-networks-deep-learning
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
    - ```.\coursera-dl.bat -u <USERNAME> -p <PASSWORD> neural-networks-deep-learning --download-notebooks```
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Folders should be created properly with alternate names and the program should terminate successfully

### Actual behaviour
```
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 238, in main
    error_occured, completed = download_class(args, class_name)
  File "c:\programdata\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 213, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\programdata\anaconda3\lib\site-packages\coursera\coursera_dl.py", line 140, in download_on_demand_class
    args.download_notebooks
  File "c:\programdata\anaconda3\lib\site-packages\coursera\extractors.py", line 57, in get_modules
    download_quizzes, mathjax_cdn_url, download_notebooks)
  File "c:\programdata\anaconda3\lib\site-packages\coursera\extractors.py", line 170, in _parse_on_demand_syllabus
    links = course.extract_links_from_notebook(lecture['id'])
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 569, in extract_links_from_notebook
    ret = self._get_notebook_json(notebook_id, authorizationId)
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 562, in _get_notebook_json
    return self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path="/", timestamp=int(time.time()))
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\programdata\anaconda3\lib\site-packages\coursera\api.py", line 494, in _get_notebook_folder
    os.makedirs(self._course_name + "/notebook/" + head + "/")
  File "c:\programdata\anaconda3\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\programdata\anaconda3\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: 'neural-networks-deep-learning/notebook/Week 4/Deep Neural Network Application: Image Classification'
```

**Comment by gabriel301** [comment]
I have the same error here. Any Update?
Creating [Week 4/Deep Neural Network Application: Image Classification/datasets] directories...
Traceback (most recent call last):
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Augus\AppData\Local\Continuum\Anaconda3\envs\Python36\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\coursera_dl.py", line 238, in main
    error_occured, completed = download_class(args, class_name)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\coursera_dl.py", line 213, in download_class
    return download_on_demand_class(args, class_name)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\coursera_dl.py", line 140, in download_on_demand_class
    args.download_notebooks
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\extractors.py", line 57, in get_modules
    download_quizzes, mathjax_cdn_url, download_notebooks)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\extractors.py", line 170, in _parse_on_demand_syllabus
    links = course.extract_links_from_notebook(lecture['id'])
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 569, in extract_links_from_notebook
    ret = self._get_notebook_json(notebook_id, authorizationId)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 562, in _get_notebook_json
    return self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path="/", timestamp=int(time.time()))
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 483, in _get_notebook_folder
    a = self._get_notebook_folder(OPENCOURSE_NOTEBOOK_TREE, jupyterId, jupId=jupyterId, path=content['path'], timestamp=int(time.time()))
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\site-packages\coursera\api.py", line 494, in _get_notebook_folder
    os.makedirs(self._course_name + "/notebook/" + head + "/")
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\users\augus\appdata\local\continuum\anaconda3\envs\python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] O nome do diretório é inválido: 'neural-networks-deep-learning/notebook/Week 4/Deep Neural Network Application: Image Classification'

**Comment by noureddin** [comment]
I made a PR that solves this issue. I tried it on my Linux machine and it didn't generate any files or folders with a colon. Can you try it?

**Comment by balta2ar** [comment]
Should be fixed by https://github.com/coursera-dl/coursera-dl/pull/654. It's available in master (not released yet).
