### ISSUE TITLE
Max retries exceeded with url: /api/login/v3

### ISSUE THREAD

**Issue by mohd1996** [coursera-dl/coursera-dl#666]
Hi guys, i got this error

> SSLError HTTPSConnectionPool(host='www.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)'),))

Windows 10
Using python 2.7

**Comment by ethan626** [comment]
I got a similar error on Linux, Python 3.6.
    File "/usr/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1546, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]

**Comment by RaviV1** [comment]
pip install --upgrade coursera-dl
did the trick
coursera-dl --version
0.11.2

**Comment by kishoreo** [comment]
**Please Help me , I could not able to download the courses**
C:\Users\Kishore Odugu>coursera-dl -u myusername -p mypassword ml-regression
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "c:\python37\lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "c:\python37\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "c:\python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "c:\python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "c:\python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "c:\python37\lib\site-packages\coursera\cookies.py", line 146, in login
    headers=headers, allow_redirects=False)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python37\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\python37\lib\site-packages\requests\adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.coursera.org', port=443): Max retries exceeded with url: /api/login/v3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)')))

C:\Users\Kishore Odugu>

**Comment by AVoss84** [comment]
Hi,

I am getting this error, when trying to submit my assignment:

Failed to execute submission request: HTTPSConnectionPool(host='hub.coursera-apps.org', port=443): Max retries exceeded with url: /api/workspaceSubmissions.v1 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe686874d30>, 'Connection to hub.coursera-apps.org timed out. (connect timeout=10)'))

Windows 10; using Google Chrome
