### ISSUE TITLE
requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.

### ISSUE THREAD

**Issue by cshung** [coursera-dl/coursera-dl#667]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.

### Your environment
* Operating System (name/version): Microsoft Windows Version 1803 (OS Build 17134.48)
* Python version: Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
* coursera-dl version: (0.11.2)

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
Running pip install coursera failed with the error message:
`requests 2.18.4 has requirement urllib3<1.23,>=1.21.1, but you'll have urllib3 1.23 which is incompatible.`

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
It should install correctly.

### Actual behaviour
It does install some files, but when I run coursera-dl, it fails:
```
C:\Users\andrewau\AppData\Local\Programs\Python\Python36-32>coursera-dl
Traceback (most recent call last):
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python36-32\Scripts\coursera-dl-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.23 (c:\users\andrewau\appdata\local\programs\python\python36-32\lib\site-packages), Requirement.parse('urllib3<1.23,>=1.21.1'), {'requests'})
```

**Comment by cshung** [comment]
I have got myself a workaround, if anyone ran into the same issue:

Step 1: Download the requirements.txt

Step 2: Modify the requirements.txt from
```
urllib3>=1.10
```
to
```
urllib3==1.21.1
```

Step 3: Install the dependencies manually using

`pip install -r requirements.txt`

Then coursera-dl should work!

**Comment by balta2ar** [comment]
Thanks! I've fixed the version in requirements.txt, it will be available in the next version.

**Comment by unoexperto** [comment]
I ad this problem. Instead I recommend upgrading the library

`pip install --upgrade urllib3`
