### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Charles-vlAd** [coursera-dl/coursera-dl#681]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.
Worked fine one hour ago, now I keep getting time out errors. My internet is fine, I don't know what the problem is.
### Your environment
* Operating System (name/version): win10
* Python version: 3.7
* coursera-dl version: newest version

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
Everything has been working fine until a hour ago when I tried to download a new course, then I tried another course, it just stopped working for some reason. I have checked upgrade and it's the newest version and my internet connection is fine.
* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.
Should've downloaded like the other courses. The following code followed right after syllabus, normally it would start downloading actual files.
### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
Traceback (most recent call last):
  File "c:\users\nikla\env\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "c:\users\nikla\env\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "c:\users\nikla\env\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nikla\env\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\nikla\env\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\nikla\env\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "c:\users\nikla\env\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "c:\users\nikla\env\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x041C9350>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nikla\env\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "c:\users\nikla\env\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\nikla\env\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /imageAssetProxy.v1/fNv81jLIEeiP-Qrke_kVoA_894c7a364552d9c294af95caa8fcfd85_Information.png?expiry=1530662400000&hmac=_NjkHrdK2xnatIHtgIbyh-H9gJu_zrQGGaeD2oRmg5Q (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x041C9350>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nikla\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Nikla\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nikla\env\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\nikla\env\lib\site-packages\coursera\coursera_dl.py", line 245, in main
    session, args, class_name)
  File "c:\users\nikla\env\lib\site-packages\coursera\coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "c:\users\nikla\env\lib\site-packages\coursera\coursera_dl.py", line 142, in download_on_demand_class
    args.download_notebooks
  File "c:\users\nikla\env\lib\site-packages\coursera\extractors.py", line 57, in get_modules
    download_quizzes, mathjax_cdn_url, download_notebooks)
  File "c:\users\nikla\env\lib\site-packages\coursera\extractors.py", line 162, in _parse_on_demand_syllabus
    lecture.id)
  File "c:\users\nikla\env\lib\site-packages\coursera\api.py", line 1270, in extract_links_from_supplement
    instructions = (IN_MEMORY_MARKER + self._markup_to_html(value),
  File "c:\users\nikla\env\lib\site-packages\coursera\api.py", line 182, in __call__
    self._convert_markup_images(soup)
  File "c:\users\nikla\env\lib\site-packages\coursera\api.py", line 241, in _convert_markup_images
    self._asset_retriever(asset_ids)
  File "c:\users\nikla\env\lib\site-packages\coursera\api.py", line 399, in __call__
    reply = get_reply(self._session, url)
  File "c:\users\nikla\env\lib\site-packages\coursera\network.py", line 48, in get_reply
    reply = session.send(prepared_request)
  File "c:\users\nikla\env\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\nikla\env\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3c33hcgiwev3.cloudfront.net', port=443): Max retries exceeded with url: /imageAssetProxy.v1/fNv81jLIEeiP-Qrke_kVoA_894c7a364552d9c294af95caa8fcfd85_Information.png?expiry=1530662400000&hmac=_NjkHrdK2xnatIHtgIbyh-H9gJu_zrQGGaeD2oRmg5Q (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x041C9350>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by williewould** [comment]
I have same error. Do you have any solutions for this?
