### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by loki3789** [coursera-dl/coursera-dl#685]
Enter - https://www.youtube.com/watch?v=l5NrYIa_aG4
Traceback (most recent call last):
  File "C:\Users\lokesh\scrapp.py", line 10, in <module>
    soup = BeautifulSoup(html, 'html.parser')
  File "C:\Users\lokesh\lib\site-packages\bs4\__init__.py", line 153, in __init__
    builder = builder_class()
  File "C:\Users\lokesh\lib\site-packages\bs4\builder\_htmlparser.py", line 39, in __init__
    return super(HTMLParserTreeBuilder, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict'

**Comment by loki3789** [comment]
can any one please help me

**Comment by balta2ar** [comment]
How's your issue related to coursera-dl?
