### ISSUE TITLE
Error 400 when trying to download content

### ISSUE THREAD

**Issue by sjpritchard** [coursera-dl/coursera-dl#690]
### Subject of the issue
Error 400 when trying to download content

### Your environment
* Windows 10
* Python version: 3.6.6
* coursera-dl version: 0.11.4

### Steps to reproduce
* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes
* What is the course that you are trying to access? Machine Learning Foundations
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx https://www.coursera.org/learn/ml-foundations/home/

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

See below

### Expected behaviour
Content should download

### Actual behaviour
PS C:\coursera> coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx https://www.coursera.org/learn/ml-foundations/home/
welcome --debug
root[main] coursera_dl version 0.11.4
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=2lkWiIRS5rfj7imf1mQV; csrf2_token_tYg22jC4=SQqckOchmGtZH9MSZAjKPuNJ.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
root[main] Downloading class: https://www.coursera.org/learn/ml-foundations/home/welcome (1 / 1)
root[download_class] Downloading new style (on demand) class https://www.coursera.org/learn/ml-foundations/home/welcome
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true HTTP/1.1" 400 None
root[get_reply] Error 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
root[get_reply] The server replied: {"msg":"Routing error: Improperly formatted value for parameter 'slug'"}
root[main] HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
root[main] HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
Traceback (most recent call last):
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\coursera_dl.py", line 245, in main
    session, args, class_name)
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\coursera_dl.py", line 142, in download_on_demand_class
    args.download_notebooks
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\extractors.py", line 52, in get_modules
    page = self._get_on_demand_syllabus(class_name)
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\extractors.py", line 68, in _get_on_demand_syllabus
    page = get_page(self._session, url)
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\network.py", line 92, in get_page
    quiet=quiet)
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\coursera\network.py", line 51, in get_reply
    reply.raise_for_status()
  File "c:\users\steve\appdata\local\programs\python\python36\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=https://www.coursera.org/learn/ml-foundations/home/welcome&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true

**Comment by frnsys** [comment]
Try specifying only the course slug, e.g. instead of:

```
coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx https://www.coursera.org/learn/ml-foundations/home/
```

try:

```
coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx ml-foundations
```

**Comment by adityaishan** [comment]
> Try specifying only the course slug, e.g. instead of:
> 
> ```
> coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx https://www.coursera.org/learn/ml-foundations/home/
> ```
> try:
> 
> ```
> coursera-dl -u xxxxxxxxxxxxx@xxxxxx -p xxxxxxx ml-foundations
> ```

Thank you, it worked!!

**Comment by vkasojhaa** [comment]
@frnsys Thank you. it worked. Earlier it would download with full path also.

**Comment by unoexperto** [comment]
Did something change recently ? It worked for me on Jan 18th and now I'm getting the same error. Here is the way I invoke it

```
coursera-dl -u xxx@xxx.com -p password --jobs 4 --download-notebooks --download-quizzes --video-resolution 720p computer-vision-basics
```

Any ideas what to do ?

**Comment by m3r3lin** [comment]
i get this error when type this command:
coursera-dl -u xxx@xxx.com -p password ai

**Comment by saurabh76** [comment]
Hi Guys,
I started getting this issue, it was working fine until last week. Wondering if Coursera changed something at their end and anyone else getting the same issue as well? 

 _in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3_

**Comment by pavelpy** [comment]
The same problem and error as @saurabh76.

**Comment by dirtScrapper** [comment]
I'm also facing the exact same issue @pavelpy  @saurabh76 . Earlier when I faced this issue it was due to presence of special characters in the password like '$*' etc. Resolution for this was to put the password in single quotes like this 'password'. I tried that out but still I'm facing the same issue as others. Can you guys @saurabh76  and @pavelpy try with the single quote on you password?

**Comment by avidLearnerInProgress** [comment]
Facing same issue

**Comment by saurabh76** [comment]
This is weird, I just kept on trying - perhaps tried 13 or 14 times and it finally worked!
Btw, I tried changing the IP Address as well, but that didn't help. Issuing the command multiple times in quick succession somehow seemed to work. I don't have any explanation for this behaviour though :-|

**Comment by mibradev** [comment]
@renatoviolin Thanks for the tip.
You can also execute a command like:

`until coursera-dl <course-name>; do sleep 10; done`

to help you repeat the process automatically until success.
_And if you want to cancel press CTRL+C._

**Comment by unjadded** [comment]
@mibradev , that doesn't work. Coursera will IP block you for spamming them.

**Comment by mibradev** [comment]
@unjadded I don't know. I thought that trying every 10 seconds is not too fast. It worked for me though (after logging in to [https://learner.coursera.help/hc](https://learner.coursera.help/hc)).

**Comment by zhujl1991** [comment]
same error here. tried all methods above. but none worked for me.

**Comment by hammao** [comment]
same problem here !!!

**Comment by mariobecerra** [comment]
Same here. 

First, I had this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/usr/local/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

But after doing @mibradev sleep trick, I got this error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/usr/local/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
coursera_dl version 0.11.4
Logged in on coursera.org.
Downloading class: data-structures-algorithms (1 / 1)
Error 500 Server Error: Internal Server Error for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=data-structures-algorithms&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=data-structures-algorithms&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
```

**Comment by mibradev** [comment]
@mariobecerra Try logging in to [https://learner.coursera.help/hc]() first.

**Comment by mariobecerra** [comment]
Oh, @mibradev , I forgot to say that I also did that. Thanks, though. :)

**Comment by saurabh76** [comment]
Hi Guys, solution here : https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-462163921

**Comment by KanishK-Bakshi** [comment]
D:\coursera-dl>coursera-dl machine-learning
coursera_dl version 0.11.5
Downloading class: machine-learning (1 / 1)
Parsing syllabus of on-demand course (id=T7hf5jWeEeuGCBL8_hyTUQ). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
