### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by g-kartik** [coursera-dl/coursera-dl#692]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here. 
I am facing this error when I am trying to download 1st course from a specialization. All other courses are downloading properly

### Your environment
* Operating System (name/version): Windows 7 SP 1
* Python version: 3.7.1
* coursera-dl version: 0.11.4

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
First join the first course in this specialization https://www.coursera.org/specializations/iot
List all courses, and you shall get the course keyword as 'iot'
Then try to download it
coursera-dl -u <username> -p <password> iot

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt` Yes
* What is the course that you are trying to access? https://www.coursera.org/learn/iot?specialization=iot
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
  coursera-dl -u <username> -p <password> iot
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
  
![screenshot_1](https://user-images.githubusercontent.com/35878512/48395411-33a0d600-e73d-11e8-8d2f-ef28fba2d8e2.png)
TypeError: string indices must be integers

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by evexoio** [comment]
@g-kartik Can confirm. This just happened with me.

Looking for a fix ASAP.

**Comment by g-kartik** [comment]
Please look into this issue.

**Comment by rolandog** [comment]
Hello, while trying to download the `quantitative-methods` course, I received a similar error as the one reported here.

### environment

- os: Ubuntu 20.10
- `python`: 3.8.6
- `coursera-dl`: 0.11.5

### error message

<details><summary>Here is a transcript of the error:</summary>

```
Traceback (most recent call last):
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/extractors.py", line 165, in _parse_on_demand_syllabus
    links = course.extract_links_from_peer_assignment(
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/api.py", line 1220, in extract_links_from_peer_assignment
    text = ''.join(self._extract_peer_assignment_text(element_id))
  File "/home/rolandog/.local/share/virtualenvs/coursera-b_vws8ln/lib/python3.8/site-packages/coursera/api.py", line 1478, in _extract_peer_assignment_text
    result.append(element['instructions']
TypeError: string indices must be integers
```
</details>

### Steps to reproduce & config files

Simplified command (listing only the course that causes a problem:

```bash
coursera-dl --path /remote/path/to/courses/folder quantitative-methods
```
Here's my conf file, in case it is useful:

<details>
<summary>'coursera-dl.conf' (CAUTH redacted)</summary>

```
# Basic options
--subtitle-language en,es
--jobs 2
--download-delay 30


# Selection of material to download
--about
--download-notebooks
--download-quizzes
--video-resolution 720p

# Advanced authentication options
--cauth redacted
--netrc /home/user/.netrc

# Advanced miscellaneous options
--playlist
#--mathjax-cdn https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.0/es5/latest?tex-mml-chtml.js

# References
# https://github.com/coursera-dl/coursera-dl
# https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-693371738
# https://www.youtube.com/watch?v=xpy0H4T9zHU
# https://docs.mathjax.org/en/latest/web/start.html
```

</details>
