### ISSUE TITLE
Not able to download notebooks (KeyError: 'authorizationId')

### ISSUE THREAD

**Issue by sebastianecheverrir** [coursera-dl/coursera-dl#694]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.
I am not able to download the programming assignments using the flag --download-notebooks (Jupyter-notebooks)

### Your environment
* Operating System (name/version):
OpenSuse Leap/42.3 (Also tried in windows 10 with python 2.7.15)
* Python version:
2.7.13 and 3.4.6

* coursera-dl version:
0.11.4

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:
Just input the command
coursera-dl  --download-notebooks  -u <USERNAME> 'nlp-sequence-models'

* Is the problem happening with the latest version of the script?
Yes

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes

* What is the course that you are trying to access?
nlp-sequence-models

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
coursera-dl  --download-notebooks  -u <USERNAME> 'nlp-sequence-models'

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
root[_parse_on_demand_syllabus] According to notebooks platform, content will be downloaded first 
root[prepare_auth_headers] Forging cookie header: CAUTH=EYIFr0EE2Wia047vUktFDzwWxU26ht3ixgCHQn8Now37UttQxbvrVNzEDZktvpCMEEq2e_zIY1zkEubXQtdtDQ.NigyoiLH1u0o9jxWDYEaJA.gC7vKO4uaa1bONrcldwDc-_-uRb78Em20-l8NKinzk1HZgkx-qED0daNEqBmrJ3iPMcXuaaRQ8JnU0CAzrxGsj5Qwq0rZBTCGOxuuV7VfssZHKjUHC0Z1pFL66rwHLLpCDt7S_XsiO6eCJUcgkSVf4uHpriVFlFzxIj43pjlXncvDGZNUYIOspTsCbtCR5hV; csrftoken=QlgAvsTS2Zd7CeU5FdVU; csrf2_token_FaRIaaTu=TGoIULBGJ0CfX0m2LgA4dfqN. 
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/onDemandNotebookWorkspaceLaunches.v1/?fields=authorizationId%2CcontentPath%2CuseLegacySystem HTTP/1.1" 201 None 
Traceback (most recent call last): 
  File "./coursera-dl", line 6, in <module>
    coursera_dl.main() 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/coursera_dl.py", line 245, in main 
    session, args, class_name) 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/coursera_dl.py", line 214, in download_class 
    return download_on_demand_class(session, args, class_name) 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/coursera_dl.py", line 142, in download_on_demand_class 
    args.download_notebooks 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/extractors.py", line 57, in get_modules 
    download_quizzes, mathjax_cdn_url, download_notebooks) 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/extractors.py", line 192, in _parse_on_demand_syllabus lecture.id) 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/api.py", line 768, in extract_links_from_notebook 
    authorizationId = self._extract_notebook_text(notebook_id) 
  File "/home/sebastian/Documents/ManAtWork/DeepLearning/coursera-dl/coursera/api.py", line 1436, in _extract_notebook_text 
    return dom['elements'][0]['authorizationId'] 
KeyError: 'authorizationId'

### Expected behaviour
Tell us what should happen.
The download process should continue. The notebooks should be downloaded

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
The script crashes, I get the message shown above

**Comment by ShiqinHuo** [comment]
same KeyError: 'authorizationId' 
for 
coursera-dl --download-notebooks neural-networks-deep-learning

**Comment by mbaroody** [comment]
Running into the same issues, except I'm using the official docker images: 

```bash
docker run --rm -it -v `pwd`:/courses courseradl/courseradl -u "xxxxxxxxxxxxxxx" -p xxxxxxxxxxxxxx" --download-quizzes --download-notebooks convolutional-neural-networks
```

Running on Ubuntu18.04

**Comment by boberle** [comment]
It seems that sometimes the key is not `authorizationId` but just `id`. Here is a workaround: go to where coursera-dl is installed and open the file `coursera/api.py`. Line 1436 (which reads `return dom['elements'][0]['authorizationId']`), replace `authorizationId` by `id`.

If you want to go further, replace the line by the following ones (respecting the indentation):
```
        try:
            return dom['elements'][0]['authorizationId']
        except KeyError:
            return dom['elements'][0]['id']
```

This worked for me, the course downloaded as usual after the modification.

**Comment by sebastianecheverrir** [comment]
@boberle  I tried your fix. It indeed removes the error and I am able to download the course. But the notebooks are not downloaded. I get the following error

```
According to notebooks platform, content will be downloaded first
Could not download notebook X20PE
```

**Comment by boberle** [comment]
@sebastianecheverrir It doesn't work, indeed. The `authorizationId` seems to be used to download only notebooks. Perhaps it's because you don't have access to the assignments if you didn't purchase the course (even if you have access to the notebook): the Coursera API doesn't give an authorization id.

However, you can download all the notebooks and all associated files at once (for each course) from the Coursera website, just follow the instructions given here: https://learner.coursera.help/hc/en-us/articles/360004990332 .

**Comment by astavonin** [comment]
@boberle , I did try the workaround, but a different crash is happening:

```According to notebooks platform, content will be downloaded first
Traceback (most recent call last):
  File "/home/astavonin/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/astavonin/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Do you have any suggestion for workaround?
