### ISSUE TITLE
can't retreve course list 

### ISSUE THREAD

**Issue by kaveinthran** [coursera-dl/coursera-dl#699]
I am using windows10 build 1809 and python 2.7.15 with latest coursera-dl
when I input my username password and --list-courses it produces bbelow error 
Microsoft Windows [Version 10.0.16299.431]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\kavein>coursera-dl -u email -p password  --list-courses
coursera_dl version 0.11.4
Listing enrolled courses
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\coursera\coursera_dl.py", line 232, in main
    list_courses(args)
  File "c:\python27\lib\site-packages\coursera\coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "c:\python27\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

C:\Users\kavein>

**Comment by beetleb** [comment]
Same here.
