### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by kalyank90** [coursera-dl/coursera-dl#709]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
ImportError: No module named 'bs4'

### Your environment
* Operating System (name/version): Ubuntu 16.04 LTS 64 Bit
* Python version: 2.7.12
* coursera-dl version: 0.11.4

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script? 
Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes
* What is the course that you are trying to access?
excel-essentials
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
./coursera-dl ...
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

(my-coursera) root@vps657146:~/courses/my-coursera/coursera-dl# ./coursera-dl ... --debug
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/root/courses/my-coursera/coursera-dl/coursera/coursera_dl.py", line 57, in <module>
    import bs4
ImportError: No module named 'bs4'

### Expected behaviour
Not sure

### Actual behaviour
(my-coursera) root@vps657146:~/courses/my-coursera/coursera-dl# ./coursera-dl ... --debug
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/root/courses/my-coursera/coursera-dl/coursera/coursera_dl.py", line 57, in <module>
    import bs4
ImportError: No module named 'bs4'

**Comment by rbrito** [comment]
Please, tell us exactly how you installed coursera-dl. It is important.

If possible, use python version 3. **NEVER** use anything that needs root/superuser/administrative permissions to install.

**Comment by zriyansh** [comment]
Try to update coursera-dl. It worked for me.
