### ISSUE TITLE
LOG IN ISSUE

### ISSUE THREAD

**Issue by Ajitesh121** [coursera-dl/coursera-dl#712]
### Subject of the issue
Not able to log in and download

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.7
* coursera-dl version: 0.11.4

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
https://www.coursera.org/learn/machine-learning/home/welcome

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched)
.
coursera-dl -u 12*******@gmail.com -p ********055 machine-learning/home/welcome

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Login and download should happen

### Actual behaviour
Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python37-32\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "c:\users\asus\appdata\local\programs\python\python37-32\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by balta2ar** [comment]
https://github.com/coursera-dl/coursera-dl/issues/702
