### ISSUE TITLE
failled to download (string indices must be integers)

### ISSUE THREAD

**Issue by IbraamYounan** [coursera-dl/coursera-dl#713]
please, help me 

unable / failed to download this course, however the script work fine in another course after using  (temporary fix for login issue on api/login/v3 by @Harjeet Singh)
course name: quantitative-methods
 expected behavior: after successful login and parcing items it should downloading as usual, but it failled as message below.

coursera-dl -u email -p password --resume quantitative-methods

coursera_dl version 0.11.4
Downloading class: quantitative-methods (1 / 1)
Parsing syllabus of on-demand course (id=rTTFFgb8EeWJMSIAC7Jl0w). This may take some time, please be patient ...
Processing module  before-we-get-started
     then after processing many items stop and gave this errowr message

Traceback (most recent call last):
  File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main    "__main__", mod_spec)
  File "c:\python37-32\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)
  File "C:\Python37-32\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>
  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 250, in main    session, args, class_name)
  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 219, in download_class    return download_on_demand_class(session, args, class_name)
  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 147, in download_on_demand_class    args.download_notebooks
  File "c:\python37-32\lib\site-packages\coursera\extractors.py", line 57, in get_modules    download_quizzes, mathjax_cdn_url, download_notebooks)
  File "c:\python37-32\lib\site-packages\coursera\extractors.py", line 166, in _parse_on_demand_syllabus    lecture.id)
  File "c:\python37-32\lib\site-packages\coursera\api.py", line 1220, in extract_links_from_peer_assignment
   text = ''.join(self._extract_peer_assignment_text(element_id))
  File "c:\python37-32\lib\site-packages\coursera\api.py", line 1479, in _extract_peer_assignment_text    ['introduction']['definition']['value']) 
TypeError: string indices must be integers

**Comment by IbraamYounan** [comment]
fixed after apply 
@sollicitudin branch

**Comment by xlazizx** [comment]
hello did you fix the string indices must be integers error? if yes may you post how
