### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by aakash180692** [coursera-dl/coursera-dl#715]
### Subject of the issue
Unable to download. Facing issue - ModuleNotFoundError: No module named 'keyring.util.escape'

### Your environment
* Ubuntu - 18.04:
* Python version: 3
* coursera-dl version: latest

### Steps to reproduce
I tried running coursera-dl command. but faced the error message mentioned above

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes
* What is the course that you are trying to access? competitive-data-science
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched). coursera-dl competitive-data-science
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

error message - 

Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/keyring/backend.py", line 190, in _load_plugins
    init_func = ep.load()
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aakash180692_gmail_com/.local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/home/aakash180692_gmail_com/.local/lib/python3.6/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by amirsaleem1990** [comment]
same issue with me for course data-scientists-tools

**Comment by aakash180692** [comment]
keep trying it again and again. It worked for me after about 20 tries.

**Comment by aj-amitjain** [comment]
## Just posting if someone still needs a solution,  

I tried an upgrade: pip install --upgrade keyrings.alt 
And then tried downloading it (the course) again using the below code and it worked fine for me. 

 ./coursera-dl -u <user>  -p <pass> <coursename>  (details are there in [readme file](https://github.com/coursera-dl/coursera-dl/tree/9b434bcf3c4011bf3181429fe674633ae5fb7d4d))
