### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by vikashinchennai** [coursera-dl/coursera-dl#718]
when i run **./coursera-dl ...** at that time i get below error.  i have updated the ubuntu fully with all installed packages.
/usr/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/root/Documents/my-coursera/coursera-dl/coursera/coursera_dl.py", line 59, in <module>
    import requests
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 105, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'

**Comment by twitu** [comment]
The issue is probably with your `requests` library. I upgraded it using `sudo pip install --upgrade requests` and it worked for me.
