### ISSUE TITLE
unable to download or get course list

### ISSUE THREAD

**Issue by IbraamYounan** [coursera-dl/coursera-dl#719]
hello

the same script was work fine from 2 weeks, i open coursera in browser and expert cookies and replaced old one, but still got errowr message below, 

used on:
os: windows7
python: 3.7
coursera: latest.

coursera-dl -u email -p password --
list-courses --debug
root[main] coursera_dl version 0.11.4
root[main] Listing enrolled courses
Traceback (most recent call last):
  File "c:\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37-32\Scripts\coursera-dl.exe\__main__.py", line 9, in <module>

  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 237, in
main
    list_courses(args)
  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 112, in
list_courses
    session = get_session()
  File "c:\python37-32\lib\site-packages\coursera\coursera_dl.py", line 98, in g
et_session
    cj.load('cookies.txt', ignore_expires=True)
  File "c:\python37-32\lib\http\cookiejar.py", line 1780, in load
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cookies.txt'

  appreciate your help

**Comment by IbraamYounan** [comment]
it just worked now as before, seem problem in coursera itself.
  thanks
