### ISSUE TITLE
451 Client Error: Unavailable For Legal Reasons for url: https://api.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by A-Shahbazi** [coursera-dl/coursera-dl#725]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
I get Error 451 Client Error: Unavailable For Legal Reasons

### Your environment
* Operating System (name/version): Manjaro Linux 18.0.4-19104
* Python version: Python 3.7.3
* coursera-dl version: 0.11.4

### Steps to reproduce

* Is the problem happening with the latest version of the script?
Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes
* What is the course that you are trying to access? 
modern-postmodern-1 but I tried with other courses and the issue is there for all
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
coursera-dl -u $myusername$ -p $mypassword$  modern-postmodern-1
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
```
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
root[main] coursera_dl version 0.11.4
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=0nmY9EE8YOq5Loc44eFg; csrf2_token_hScAHTY2=ImOs4B8in1l4arwpdBcOyNax.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 451 1053
Traceback (most recent call last):
  File "/home/ali/.local/lib/python3.7/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 451 Client Error: Unavailable For Legal Reasons for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/.local/bin/coursera-dl", line 10, in <module>
    sys.exit(main())
  File "/home/ali/.local/lib/python3.7/site-packages/coursera/coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "/home/ali/.local/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 451 Client Error: Unavailable For Legal Reasons for url: https://api.coursera.org/api/login/v3
```
### Expected behaviour
The course material should be downloaded!

### Actual behaviour
The command log is provided just above

**Comment by A-Shahbazi** [comment]
BTW, I used the version suggested in #702 but it doesn't work either. It goes further but it doesn't work. Here is the log using the -ca option:
```
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
coursera_dl version 0.11.4
Downloading class: modern-postmodern-1 (1 / 1)
Error 451 Client Error: Unavailable For Legal Reasons for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=modern-postmodern-1&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=modern-postmodern-1&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
The server replied: <html>
  <head>
    <title>Coursera - OFAC Restrictions</title>
    <meta name="robots" content="noindex, nofollow">
  </head>
  <body style="background-color:#e4e4e4">
    <div style="position:absolute; top:0; bottom:0; left:0; right:0; margin:auto; height:200px; width: 600px">
      <div style="text-align:center">
        <img src="https://coursera.s3.amazonaws.com/error_pages/coursera-logo.svg" width="400">
      </div>
      <h1 style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:100; color: #555">
        OFAC Restrictions
      </h1>
      <div style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:300; font-size:13pt; color: #555">
        We are sorry, but due to OFAC restrictions, learners in your country are not allowed to access the platform.
      </div>
    </div>
    <div style="position: absolute; bottom: 25px; left: 25px; text-align:center; font-family:Helvetica, Arial, sans-serif; font-size:8pt; color: #bbb;">
      Details: No information.
    </div>
  </body>
</html>
HTTPError 451 Client Error: Unavailable For Legal Reasons for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=modern-postmodern-1&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
```

**Comment by A-Shahbazi** [comment]
Oh I figured it out!
I'm using the coursera in a restricted country and I had to use a proxy to be able to get past the authentication and downloading contents.  #682 was required though. Hope that gets merged soon!
