### ISSUE TITLE
cookies.Authentication failed

### ISSUE THREAD

**Issue by ImSiddh** [coursera-dl/coursera-dl#727]
Unable to resume on windows 10
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "C:\coursera-dl-master\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Users\Siddharth\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\coursera-dl-master\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "C:\coursera-dl-master\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by fengzhao** [comment]
API已经不能用了

**Comment by Ubaid-Manzoor** [comment]
same error please solve it

**Comment by raffam** [comment]
Duplicate of #726
