### ISSUE TITLE
Cannot download notebooks: Exception is thrown (KeyError: 'authorizationId')

### ISSUE THREAD

**Issue by raffam** [coursera-dl/coursera-dl#732]
### Subject of the issue
The `--download-notebooks` option makes coursera-dl throws an exception

### Your environment
* Operating System (name/version): Windows 10 Educational
* Python version: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
* coursera-dl version: commit 9b434bcf3c4011bf3181429fe674633ae5fb7d4d

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
Yes

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
Yes

* What is the course that you are trying to access?
Deep learning specialization [link](https://www.coursera.org/specializations/deep-learning)

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

`D:\data\CORSI\MOOC\deep_learning_specialization>coursera-dl -u ***** -p ***** --resume --specialization deep-learning --path=./coursera_scraped_hires --video-resolution 720p -f "mp4" --download-delay 0 --download-quizzes --download-notebooks --lecture_filter "^((?!extended-description-mixed).)*$" --wget `

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
coursera_dl version 0.11.4
Logged in on coursera.org.
Expanded specialization "deep-learning" into the following classes: deep-neural-network machine-learning-projects convolutional-neural-networks nlp-sequence-models neural-networks-deep-learning
Downloading class: deep-neural-network (1 / 5)
Parsing syllabus of on-demand course (id=BZ5quSvBEee6gA5XksfBbg). This may take some time, please be patient ...
Processing module  practical-aspects-of-deep-learning
Processing section     setting-up-your-machine-learning-application
Processing lecture         train-dev-test-sets (lecture)
Processing lecture         bias-variance (lecture)
Processing lecture         basic-recipe-for-machine-learning (lecture)
Processing section     regularizing-your-neural-network
Processing lecture         regularization (lecture)
Processing lecture         why-regularization-reduces-overfitting (lecture)
Processing lecture         dropout-regularization (lecture)
Processing lecture         understanding-dropout (lecture)
Processing lecture         other-regularization-methods (lecture)
Processing section     setting-up-your-optimization-problem
Processing lecture         normalizing-inputs (lecture)
Processing lecture         vanishing-exploding-gradients (lecture)
Processing lecture         weight-initialization-for-deep-networks (lecture)
Processing lecture         numerical-approximation-of-gradients (lecture)
Processing lecture         gradient-checking (lecture)
Processing lecture         gradient-checking-implementation-notes (lecture)
Processing section     practice-questions
Processing lecture         practical-aspects-of-deep-learning (exam)
Processing section     programming-assignments
Processing lecture         initialization (notebook)
According to notebooks platform, content will be downloaded first
Traceback (most recent call last):
  File "D:\data\progetti_miei\coursera-dl\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "D:\data\progetti_miei\coursera-dl\coursera\coursera_dl.py", line 245, in main
    session, args, class_name)
  File "D:\data\progetti_miei\coursera-dl\coursera\coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "D:\data\progetti_miei\coursera-dl\coursera\coursera_dl.py", line 142, in download_on_demand_class
    args.download_notebooks
  File "D:\data\progetti_miei\coursera-dl\coursera\extractors.py", line 57, in get_modules
    download_quizzes, mathjax_cdn_url, download_notebooks)
  File "D:\data\progetti_miei\coursera-dl\coursera\extractors.py", line 192, in _parse_on_demand_syllabus
    lecture.id)
  File "D:\data\progetti_miei\coursera-dl\coursera\api.py", line 768, in extract_links_from_notebook
    authorizationId = self._extract_notebook_text(notebook_id)
  File "D:\data\progetti_miei\coursera-dl\coursera\api.py", line 1436, in _extract_notebook_text
    return dom['elements'][0]['authorizationId']
KeyError: 'authorizationId'
```

### Expected behaviour
Download the notebooks without throwing an exception

### Actual behaviour
An exception is thrown

**Comment by felker** [comment]
Duplicate of #694. Refer to https://learner.coursera.help/hc/en-us/articles/360004990332

**Comment by Rayid-Mojumder** [comment]
If anyone is using windows command prompt and coursera-dl for downloading tutorials and facing problems to get the cauth codes from crome browser. Follow this:

open Crome -> Settings -> Privacy and security -> Cookies and other site data -> All cookies and site data -> Find and Extend coursera.org -> extend CAUTH -> copy the code

This code can be used for coursera authenication.
If you are using other browser check associated cookies of the coursera site.

If no cookies found. First login to the Coursera websites and enroll a course. Then check for cookies

Hope this helps. Thanks

**Comment by Rayid-Mojumder** [comment]
> I can't get nearly as far:
> 
> ```
> coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
> ```
> 
> and sure enough, when trying to hit
> https://api.coursera.org/api/login/v3
> 
> API Route Does Not Exist
> Edge does not know about this API route.
> Check whether this route is exposed in the routing table

If anyone is using windows command prompt and coursera-dl for downloading tutorials and facing problems to get the cauth codes from crome browser. Follow this:

open **_Crome_** -> **_Settings_** -> **_Privacy and security_** -> **_Cookies and other site data_** -> **_All cookies and site data_** -> Find and Extend **_coursera.org_** -> extend **_CAUTH_** -> copy the code

This code can be used for coursera authenication.
If you are using other browser check associated cookies of the coursera site.

If no cookies found. First login to the Coursera websites and enroll a course. Then check for cookies

Hope this helps. Thanks
