### ISSUE TITLE
coursera-dl not running

### ISSUE THREAD

**Issue by lbotelho73** [coursera-dl/coursera-dl#739]
HI
When I run coursera-dl by:
coursera-dl -u username -p password course_name
It shows me this error:

coursera_dl version 0.11.5
Traceback (most recent call last):
  File "/Users/lbotelho/Library/Python/2.7/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/Users/lbotelho/Library/Python/2.7/lib/python/site-packages/coursera/coursera_dl.py", line 235, in main
    session = get_session()
  File "/Users/lbotelho/Library/Python/2.7/lib/python/site-packages/coursera/coursera_dl.py", line 95, in get_session
    session.mount('https://', TLSAdapter())
  File "/Users/lbotelho/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/Users/lbotelho/Library/Python/2.7/lib/python/site-packages/coursera/cookies.py", line 385, in init_poolmanager
    ssl_version=ssl.PROTOCOL_TLSv1_2)
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'

Already upgraded the 
sudo pip install --upgrade html5lib
sudo pip install --upgrade beautifulsoup4

But event that, it is not working. Someone could help?

**Comment by hiqua** [comment]
Have you tried with Python 3?

**Comment by allthingie** [comment]
Trying with Python 3.5 on OSX, gives me the same error

    coursera_dl version 0.11.5
    Listing enrolled courses
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coursera/coursera_dl.py", line 232, in main
    list_courses(args)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coursera/coursera_dl.py", line 107, in list_courses
    session = get_session()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coursera/coursera_dl.py", line 95, in get_session
    session.mount('https://', TLSAdapter())
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/coursera/cookies.py", line 385, in init_poolmanager
    ssl_version=ssl.PROTOCOL_TLSv1_2)
    AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLSv1_2'

**Comment by felker** [comment]
probably related to the EOL of OpenSSL 1.0 near the end of 2019. Which OS are you on? Try reinstalling your Python distribution
