### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by LongxingTan** [coursera-dl/coursera-dl#745]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Thanks for the nice tool. it really helps a lot. But it raise errors like this, fyi i'm from China. it maybe also China specific issue
```
Traceback (most recent call last):
  File "/Users/longxingtan/anaconda3/bin/coursera-dl", line 10, in <module>
    sys.exit(main())
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 248, in main
    session, args, class_name)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 142, in download_on_demand_class
    args.download_notebooks
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/extractors.py", line 52, in get_modules
    page = self._get_on_demand_syllabus(class_name)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/extractors.py", line 68, in _get_on_demand_syllabus
    page = get_page(self._session, url)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/network.py", line 92, in get_page
    quiet=quiet)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/coursera/network.py", line 48, in get_reply
    reply = session.send(prepared_request)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/longxingtan/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.coursera.org', port=443): Max retries exceeded with url: /api/onDemandCourseMaterials.v2/?q=slug&slug=preparing-cloud-professional-data-engineer-exam&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10560e588>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

### Your environment
* Operating System (name/version): mac
* Python version: 3.7
* coursera-dl version: 0.11.5

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
* What is the course that you are trying to access?
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

**Comment by GitHubForPP** [comment]
I was also in China and had the same problem.

**Comment by user670** [comment]
I have the same issue.

I'm in China, tried directly connecting AND various VPN servers, and this error occur regardless. I then tried to load the affected URL  ( https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/h8XR01ZXEeW1EQ7ZpGC66w_a6573d5edc5726f450228cc5f209594d_shutterstock_229243471.jpg?expiry=1600646400000&hmac=5TRQPsgvvJJWhUzjDcskOOSxNbNAXmQpwLS2EHWU_cw - it's an image) using my web browser, but it loads without problem somehow.

**Comment by drnkfa** [comment]
i use vpn 
then problem was solved
you should try some vpn if you are in China

**Comment by selfmakeit** [comment]
you can try add "52.84.167.78 d3c33hcgiwev3.cloudfront.net" to your hosts file. i solved by this way.
