### ISSUE TITLE
Cannot login on coursera.org

### ISSUE THREAD

**Issue by ayman-elbadawy** [coursera-dl/coursera-dl#756]
### Subject of the issue    Cannot login on coursera.org
Describe your issue here.

### Your environment
* Operating System (name/version): ubuntu/18.04
* Python version: 3.7
* coursera-dl version:0.11.5

root[main] coursera_dl version 0.11.5
root[main] Listing enrolled courses
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=CIfxNojk9c9QwrxCJMqe; csrf2_token_8V5IInq5=GcfecgIvgAZwyf00ZizsNYgU.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/home/ayman/anaconda3/lib/python3.7/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/home/ayman/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ayman/anaconda3/bin/coursera-dl", line 10, in <module>
    sys.exit(main())
  File "/home/ayman/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 232, in main
    list_courses(args)
  File "/home/ayman/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "/home/ayman/anaconda3/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by patoomartinez** [comment]
Hi! i had the same problem and today i was able to download a course. you need to login to coursera web with google chrome. Go to >cookies>search coursera> auth. copy the content of this cookie.
then open a terminal> coursera-dl -u <username> -p <password> -ca <contente of cookie> <nameofthecourse>

**Comment by wpav** [comment]
I tried this and got the same error.  Do I need a new session?

**Comment by Andre1989** [comment]
I started downloading yesterday, and in the middle my account was temporarily banned due to too many connections. Today, the script stopped working. It says forbidden for url.
An update of the script is urgently needed.

**Comment by Andre1989** [comment]
Downloading class: learning-how-to-learn (1 / 1)
Parsing syllabus of on-demand course (id=GdeNrll1EeSROyIACtiVvg). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled

**Comment by Andre1989** [comment]
Just try entering these links. It says the following:

Confused deputy attack detected.

**Comment by doctorcolossus** [comment]
Confirmed:
```
$ coursera-dl -u "********@********.***" computer-vision-opencv-for-images
Coursera password for ********@********.***:
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/usr/lib/python3.8/site-packages/coursera/coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "/usr/lib/python3.8/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

**Comment by robe007** [comment]
Following [@patoomartinez's solution](https://github.com/coursera-dl/coursera-dl/issues/756#issuecomment-621456977), you should use the script like this:

`coursera-dl -u <user> -p <password> --video-resolution 720p -sl en --specialization --download-notebooks --download-quizzes -ca <CAUTH_COOKIE_CONTENT> <course-name>`

where `CAUTH_COOKIE_CONTENT` is the content of your `CAUTH` cookie on Coursera.

**Comment by teorems** [comment]
It doesn't work for me.

**Comment by tasnim2487** [comment]
I couldn't find the cookie content?how to find it?

**Comment by sunilshukl64** [comment]
> 

![image](https://user-images.githubusercontent.com/75921158/119224553-846ac400-bb1c-11eb-82c9-0dd669b4a76d.png)

**Comment by sunilshukl64** [comment]
please help regearding this issue

**Comment by sunilshukl64** [comment]
some progress showed about downloading some lectures then it showed this error;

**Comment by ejvingen** [comment]
> I couldn't find the cookie content?how to find it?

In Chrome, on any web page, right click and select "inspect". In DevTools click Application in the menu at the top. Click Cookies in the menu on the left
