### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by mailtosagar** [coursera-dl/coursera-dl#760]
Hi,
I have been trying to install the course lecture. but i have been encountered the error again and again
```
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "/home/sagar-pc/Desktop/Me/www-coursera-downloader-master/env/lib/python3.6/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/home/sagar-pc/Desktop/Me/www-coursera-downloader-master/env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sagar-pc/Desktop/Me/www-coursera-downloader-master/env/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/home/sagar-pc/Desktop/Me/www-coursera-downloader-master/env/lib/python3.6/site-packages/coursera/coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "/home/sagar-pc/Desktop/Me/www-coursera-downloader-master/env/lib/python3.6/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

``` 

I have entered my username and password in the cousera-dl.conf but this error continues. Please help

**Comment by doctorcolossus** [comment]
Same here. I just installed coursera-dl for the first time, but also experience this behavior.

```
$ coursera-dl -u "********@********.***" computer-vision-opencv-for-images
Coursera password for ********@********.***:
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/usr/lib/python3.8/site-packages/coursera/coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "/usr/lib/python3.8/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

**Comment by Daniel-10** [comment]
Found this in the other issues threads and it worked for me.

https://github.com/coursera-dl/coursera-dl/issues/702#issuecomment-605655023

**Comment by antalparth** [comment]
same here.

**Comment by antalparth** [comment]
FInally found the fix. Videos downloading as smooth af!
coursera-dl -u xxx@xxx.com -p password -ca cauth_content course_name
(Note:
1. cauth_content=Settings>Privacy & Security> Search for coursera.org cookies and copy the cauth content
2. course_name: Copy the course name after "learn/" in the Coursera URL)
Just paste the values as it is and it'll work. Happy Coding.

**Comment by thewong-andonly** [comment]
In case anybody else is having this problem, my issue was I was trying to download single lectures.  What the library does is download the entire course and will only understand the course name.

Otherwise, this thing works brilliantly!

**Comment by purav7838** [comment]
Yes the solution provided by @antalparth worked for me too

**Comment by lablnet** [comment]
![image](https://user-images.githubusercontent.com/27757785/92351949-6aa46080-f0f6-11ea-82c5-c27cd61a0c70.png)

Same issue
