### ISSUE TITLE
 command not found: coursera-dl

### ISSUE THREAD

**Issue by noa730** [coursera-dl/coursera-dl#766]
🚨Please review the Troubleshooting section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

**Subject of the issue**
Unable to run command coursera-dl. 
ImportError: zsh: command not found: coursera-dl

**Your environment**
Operating System (name/version): Mac OS Capitan 10.15.6
Python version: 3.8.5
coursera-dl version: -

**Steps to reproduce**
The cmd I use to install is :
cd ~/Documents/coursera
python3 -m pip install -r requirements.txt"

1. Is the problem happening with the latest version of the script?
yes

2. Do you have all the recommended versions of the modules? See them in the
file requirements.txt.
yes all of them installed correctly in folder: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages 

3. What is the course that you are trying to access?
linear-algebra-machine-learning

4. What is the precise command line that you are using (don't forget to obfuscate
your username and password, but leave all other information untouched).
./coursera-dl -u myemail -p linear-algebra-machine-learning

5. What are the precise messages that you get? Please, use the --debug
option before posting the messages as a bug report. Please, copy and paste
them. Don't reword/paraphrase the messages.
Traceback (most recent call last):
  File "./coursera-dl", line 4, in <module>
    from coursera import coursera_dl
  File "/Users/mac/Documents/coursera/coursera/coursera_dl.py", line 62, in <module>
    from bs4 import BeautifulSoup as BeautifulSoup_
  File "/Library/Python/2.7/site-packages/bs4/__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "/Library/Python/2.7/site-packages/bs4/builder/__init__.py", line 306, in <module>
    from . import _html5lib
  File "/Library/Python/2.7/site-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

I see similar issues but I tried their solution and it didn't work, so I posted it again.
Thank you!

**Comment by floviolleau** [comment]
Hi,

Are you sure you that when you ran `python3 -m pip install -r requirements.txt`, all is successful?
