### ISSUE TITLE
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

### ISSUE THREAD

**Issue by zhangxiann** [coursera-dl/coursera-dl#777]
```
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "/home/iot/anaconda3/lib/python3.7/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/home/iot/anaconda3/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iot/anaconda3/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/home/iot/anaconda3/lib/python3.7/site-packages/coursera/coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "/home/iot/anaconda3/lib/python3.7/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

**Comment by saligari** [comment]
Check out issue 773 and the comments (along with the youtube video). I had the same problem as you, creating a coursera-dl.conf with my cauth cookies worked for me.

**Comment by zhangxiann** [comment]
> Check out issue 773 and the comments (along with the youtube video). I had the same problem as you, creating a coursera-dl.conf with my cauth cookies worked for me.
> 
> I think this can be closed as duplicate of #773

Thanks!
