### ISSUE TITLE
ModuleNotFoundError: No module named 'multiprocessing'

### ISSUE THREAD

**Issue by type2b** [coursera-dl/coursera-dl#784]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.
```
Traceback (most recent call last):
  File "c:\users\test\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\test\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\test\AppData\Local\Programs\Python\Python39\Scripts\coursera-dl.exe\__main__.py", line 4, in <module>
  File "c:\users\test\appdata\local\programs\python\python39\lib\site-packages\coursera\coursera_dl.py", line 67, in <module>
    from .parallel import ConsecutiveDownloader, ParallelDownloader
  File "c:\users\test\appdata\local\programs\python\python39\lib\site-packages\coursera\parallel.py", line 4, in <module>
    from multiprocessing.dummy import Pool
ModuleNotFoundError: No module named 'multiprocessing'
```

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.9
* coursera-dl version: last (installed with pip)

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script? 
_Yes_
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.
_yes_
* What is the course that you are trying to access? 
_even coursera-dl --help doesnt work_  fundamentals-of-graphic-design_
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched). 
_coursera-dl -u user -p password fundamentals-of-graphic-design_
* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.
same error as above

### Expected behaviour
Tell us what should happen.
_Coursera-dl should work_
### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.
_Doesn't work at all_

**Comment by ejvingen** [comment]
I had a similar problem: _ModuleNotFoundError: No module named 'distutils'_. 
Once I installed this module using: pip install setuptools, everything worked. 
I think in current versions of Python multiprocessing is already included

**Comment by vaswork** [comment]
> I had a similar problem: _ModuleNotFoundError: No module named 'distutils'_. Once I installed this module using: pip install setuptools, everything worked. I think in current versions of Python multiprocessing is already included

Looks like py **3.11** is a newest version compatible with **coursera-dl**.  I have got the same *No module* accordingly *readme*:
```
We strongly recommend that you use a Python 3 interpreter (3.9 or later).
```
, when I have tried to use **3.14**. More details in **distutils.rst.txt**:
```
.. module:: distutils
   :synopsis: Removed in 3.12.
   :deprecated:

.. deprecated-removed:: 3.10 3.12
```

Reinstallation **3.11** works for me.
