### ISSUE TITLE
HTTPError 400 Client Error

### ISSUE THREAD

**Issue by tasnim2487** [coursera-dl/coursera-dl#796]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Your environment
* Operating System (name/version): Debian 9
* Python3 version:3.5
* coursera_dl version 0.11.5

* Is the problem happening with the latest version of the script? yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`...yes
* What is the course that you are trying to access?--Astro 101:Black Holes
* command line 
/coursera-dl -u xx -p xx  Astro 101:Black Holes

### Expected behaviour
Download should begin

### Actual behaviour
The server replied: {"msg":"Routing error: Improperly formatted value for parameter 'slug'"}
HTTPError 400 Client Error: Bad Request for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=Python&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true

**Comment by otterlover24** [comment]
Same issue, below is the output of `coursera-dl -u <user> --list-courses`:

```
Coursera password for tiansheng2424@gmail.com:
coursera_dl version 0.11.5
Listing enrolled courses
Traceback (most recent call last):
  File "/home/otterlover24/.local/lib/python3.8/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/otterlover24/.local/bin/coursera-dl", line 8, in <module>
    sys.exit(main())
  File "/home/otterlover24/.local/lib/python3.8/site-packages/coursera/coursera_dl.py", line 232, in main
    list_courses(args)
  File "/home/otterlover24/.local/lib/python3.8/site-packages/coursera/coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "/home/otterlover24/.local/lib/python3.8/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

**UPDATE: Found a fix**
I found the fix by following https://github.com/coursera-dl/coursera-dl/issues/773 and creating a coursera-dl.conf file.
