### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by sghinescu** [coursera-dl/coursera-dl#799]
G:\Coursera>coursera-dl -u xyzdoe@gmail.com -ca mgmc6yheYS9ZFlQbLKyTMWvky8vWDsDFRbHFLaB99LEyVuy8WnUco0CJA4MnC3mJixeZ5ZlRE1utwX_hp7NVXg.kKLS5wYyFf-48BljvqWLJQ.4fIyXL41zYfOvJkjncG7m04zUrwrFMGI5dACx8zTDrb76gIWiVz_KqvpA3TdQGnUMBuh7mZN2ETlgrL8zIC21CWauKA5JHrl9cLfD93i5Ob5xaNS3lPSOLXrgBpKw_b8aIhK-44B5oqNkAhQ6mxsTTaN_qTdNQrkGNQC4TuwTD5O7DcIdz2C2WseHGtdmgsN6rGAnwGbjaJ564EVQfl-P6KQoeMIXpXH2jju2JHfp0hlH85yqNCvQIoId_OS9mM-KwcrgHUl4A1Gl2oAuxTF1wh4g2qY13xaXZUo31M0MCusUX-SAfcFYdwGgFB-AIkxOicgYRxj-Qitkrp1ZIhc4-08NyyWSIngmHGS1EWE0o6bW2Mepjc7iirmziLPemtNyR9qhU7mYGPB2xajRMujiCV7jBuFgxZ8HKAV0j89Zo --list-courses
coursera_dl version 0.11.5
Listing enrolled courses
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "c:\python27\lib\site-packages\coursera\coursera_dl.py", line 232, in main
    list_courses(args)
  File "c:\python27\lib\site-packages\coursera\coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "c:\python27\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by vihigh123** [comment]
I am also facing this issue
