### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by bilaljawed** [coursera-dl/coursera-dl#804]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here.

### Your environment
* Operating System (name/version): Windows 10
* Python version: 3.9
* coursera-dl version: 0.11.5

### Steps to reproduce
Just not getting through login

### Actual behaviour

coursera_dl version 0.11.5
Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "C:\Users\X\AppData\Local\Programs\Python\Python39\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by stefandekanski** [comment]
You can workaround this by using a `-ca` option (`-ca COOKIES_CAUTH`). In Google Chrome you can find that info by going to `chrome://settings/cookies/detail?site=coursera.org`  and then find `CAUTH` cookie content value (to use as `COOKIES_CAUTH` value).
The weird thing is that you can't list courses by using this option, but you can directly download the specialization or individual course that you need.
I hope this helps.

**Comment by stefandekanski** [comment]
Also, you need a Python version lower than `3.9` since the API changed. I recommend that you use `3.8.x` version...

**Comment by pedrovgp** [comment]
I tried using the -ca option with the CAUTH cookie, it returned "Cookies file not found: a". I added the cookie context to a file, changed the command to "coursera-dl -c cookies_file my_course'. But I still get "coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3"
Any hints on where the problem might be? I am on Ubuntu 20.04
