### ISSUE TITLE
Is it still work in 2022 or abandanware?

### ISSUE THREAD

**Issue by js-god** [coursera-dl/coursera-dl#816]
Are you still update

**Comment by js-god** [comment]
coursera_dl version 0.11.3
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/anaconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/coursera/coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "/anaconda3/lib/python3.6/site-packages/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by ikxim** [comment]
Good day fam... is this still working? i tried installing but i got the error below.... please how do i solve the error?

"C:\Users\USER>pip install coursera-dl
Defaulting to user installation because normal site-packages is not writeable
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025E981F8280>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))': /simple/coursera-dl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025E981F81C0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))': /simple/coursera-dl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025E981F80A0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))': /simple/coursera-dl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025E981F88E0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))': /simple/coursera-dl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025E981F8A60>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))': /simple/coursera-dl/
ERROR: Could not find a version that satisfies the requirement coursera-dl (from versions: none)
ERROR: No matching distribution found for coursera-dl"

Thanks

**Comment by Terr** [comment]
Logging in seems to be broken but the script still works if you use the CAUTH cookie from your browser. 

Just log in to the website as usual and look for the CAUTH cookie in your browser's cookie storage, and then pass its value to the script with the `-ca` parameter (you can leave out the `-u` and `-p` parameters)

**Comment by ezxpro** [comment]
@Terr not working anymore, even though it authenticates, it can't download. I get this error:
```
coursera_dl version 0.11.5
Downloading class: it-security (1 / 1)
Parsing syllabus of on-demand course (id=quF5rVdrEeesGQokJ1NePA). This may take some time, please be patient ...
Processing module  understanding-security-threats
Processing section     introduction-to-it-security
Processing lecture         course-introduction (lecture)
Processing lecture         navigating-coursera (supplement)
Processing lecture         program-surveys (supplement)
Processing lecture         how-to-use-discussion-forums (supplement)
Processing lecture         get-to-know-your-classmates (supplement)
Processing lecture         meet-and-greet (discussionPrompt)
Unsupported typename "discussionPrompt" in lecture "meet-and-greet" (lecture id "slTDi")
Processing section     malicious-software
Processing lecture         the-cia-triad (lecture)
Processing lecture         essential-security-terms (lecture)
Processing lecture         malicious-software (lecture)
Processing lecture         malware-continued (lecture)
Processing lecture         supplemental-reading-for-malicious-software (supplement)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\extractors.py", line 161, in _parse_on_demand_syllabus
    links = course.extract_links_from_supplement(
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\api.py", line 1268, in extract_links_from_supplement
    supplement_content, self._extract_links_from_text(value))
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\api.py", line 1518, in _extract_links_from_text
    supplement_links = self._extract_links_from_a_tags_in_text(text)
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\api.py", line 1597, in _extract_links_from_a_tags_in_text
    extension = clean_filename(
  File "C:\Users\ezbie\AppData\Roaming\Python\Python310\site-packages\coursera\utils.py", line 118, in clean_filename
    s = h.unescape(s)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
PS C:\Users\ezbie\coursera>
```

**Comment by myakhlaqi** [comment]
Hi guys, yes it is still working. to resolve this issues please have a look at this post:
https://github.com/coursera-dl/coursera-dl/pull/789#issuecomment-800142031

You need to do some manual coding on the utils.py file inside this path:
C:\Users\YOUR USER NAME\AppData\Local\Programs\Python\Python3XX\Lib\site-packages\coursera
