### ISSUE TITLE
cryptography error that prevents installing coursera-dl

### ISSUE THREAD

**Issue by OmarShawky1** [coursera-dl/coursera-dl#821]
### Subject of the issue
Impossible to install `coursera-dl` on my OS no matter what python version I use (2.7, 3.6.9, 3.8). (python2 results in a different error but also related to cryptography).
### Your environment
* Operating System (name/version): Elementary OS Hera 5.1.7 (Based on Ubuntu 18.04 LTS)
* Python version: 3.6.9, 3.8
* coursera-dl version: X

### Steps to reproduce
`pip3 install coursera-dl`

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes, installing them cause exactly the same error.

### Expected behaviour
To just install.

### Actual behaviour
Does not install and here is the entire error:
```
$ python3.8 -m pip install coursera-dl
Collecting coursera-dl
  Using cached https://files.pythonhosted.org/packages/71/de/37882d8ebb0fec512b335a6c06a192c77bcf68256606aa2e33222942e4b7/coursera_dl-0.11.5-py2.py3-none-any.whl
Collecting requests>=2.10.0 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.1.3 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/69/bf/f0f194d3379d3f3347478bd267f754fc68c11cbf2fe302a6ab69447b1417/beautifulsoup4-4.10.0-py3-none-any.whl
Collecting six>=1.5.0 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting keyring>=4.0 (from coursera-dl)
  Downloading https://files.pythonhosted.org/packages/0d/bb/8e715dbb1886e6d7e4c6a7024c11a7e137559cd85366f25c67c2bdb311c3/keyring-23.5.0-py3-none-any.whl
Collecting configargparse>=0.12.0 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/af/cb/2a6620656f029b7b49c302853b433fac2c8eda9cbb5a3bc70b186b1b5b90/ConfigArgParse-1.5.3-py3-none-any.whl
Collecting attrs==18.1.0 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/41/59/cedf87e91ed541be7957c501a92102f9cc6363c623a7666d69d51c78ac5b/attrs-18.1.0-py2.py3-none-any.whl
Collecting urllib3>=1.23 (from coursera-dl)
  Using cached https://files.pythonhosted.org/packages/4e/b8/f5a25b22e803f0578e668daa33ba3701bb37858ec80e08a150bd7d2cf1b1/urllib3-1.26.8-py2.py3-none-any.whl
Collecting idna<4,>=2.5; python_version >= "3" (from requests>=2.10.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl
Collecting charset-normalizer~=2.0.0; python_version >= "3" (from requests>=2.10.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.10.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl
Collecting soupsieve>1.2 (from beautifulsoup4>=4.1.3->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/72/a6/fd01694427f1c3fcadfdc5f1de901b813b9ac756f0806ef470cfed1de281/soupsieve-2.3.1-py3-none-any.whl
Collecting jeepney>=0.4.2; sys_platform == "linux" (from keyring>=4.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/14/b8/bb3e34d71472140f9bfdf5d77cd063e2cc964b72b1bb0b70fe3c1e7db932/jeepney-0.7.1-py3-none-any.whl
Collecting SecretStorage>=3.2; sys_platform == "linux" (from keyring>=4.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/d9/1e/29cd69fdac7391aa51510dfd42aa70b4e6a826c8cd019ee2a8ab9ec0777f/SecretStorage-3.3.1-py3-none-any.whl
Collecting importlib-metadata>=3.6 (from keyring>=4.0->coursera-dl)
  Downloading https://files.pythonhosted.org/packages/f9/5f/8f5e198c94a04163fc2e1c425d3963197d59b631614db52bc02b11ee4cff/importlib_metadata-4.11.1-py3-none-any.whl
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=4.0->coursera-dl)
  Using cached https://files.pythonhosted.org/packages/f9/4b/1cf8e281f7ae4046a59e5e39dd7471d46db9f61bb564fddbff9084c4334f/cryptography-36.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mi43f3e5/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    
    ----------------------------------------

```

**Comment by OmarShawky1** [comment]
Solution:
`python3 -m pip install --upgrade pip`
