### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by obtim** [coursera-dl/coursera-dl#830]
Got this error:

coursera_dl version 0.11.5
Traceback (most recent call last):
  File "c:\users\xxx\anaconda3\envs\coursera\lib\runpy.py", line 174, in _run_
module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\xxx\anaconda3\envs\coursera\lib\runpy.py", line 72, in _run_c
ode
    exec code in run_globals
  File "C:\Users\xxx\anaconda3\envs\coursera\Scripts\coursera-dl.exe\__main__.
py", line 7, in <module>
  File "c:\users\xxx\anaconda3\envs\coursera\lib\site-packages\coursera\course
ra_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "c:\users\xxx\anaconda3\envs\coursera\lib\site-packages\coursera\cookie
s.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client
Error: Bad Request for url: https://api.coursera.org/api/login/v3

Python 2.7.18 on Windows 7
Tried running with the -c switch with the path to the cookie - don't work
Tried to change the location via VPN - didn't help
Antivirus - off. Permissions - administrator

**Comment by inobrevi** [comment]
I see the same error.
```
coursera_dl version 0.11.5
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "D:\Anaconda3\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "D:\Anaconda3\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by Mo7mud** [comment]
Did anyone manage to solve this? I'm getting the same error.
