### ISSUE TITLE
coursera: deprecating API endpoint onDemandCourseMaterials.v1

### ISSUE THREAD

**Issue by blakekjohnson** [coursera-dl/coursera-dl#834]
Hello, at Coursera we are in the process of deprecating the `onDemandCourseMaterials.v1` endpoint. When looking for usages of this API we found it used externally [here](https://github.com/coursera-dl/coursera-dl/blob/10ba6b8d8c30798a45d45db2dc147edf3b455350/coursera/api.py#L318) and wanted to notify the project owners that this endpoint will soon have traffic shut off. The `onDemandCourseMaterials.v2` endpoint can serve as an alternative to `onDemandCourseMaterial.v1`

**Comment by Ranielo** [comment]
Hey. has this happened today? as I cannot use anymore coursera-dl.

Thanks for info

**Comment by zacsyuan** [comment]
I run into this issue as well...wondering is there a way we could tweak codes at api to proceed when await owner to update package? 



![image](https://user-images.githubusercontent.com/117028237/198887079-871add9f-beee-4392-9682-a83894730f25.png)

**Comment by MadApe** [comment]
@blakekjohnson If it's not too much trouble, would you mind proving a link to the documentation for the new API?  Thanks!

**Comment by zacsyuan** [comment]
@MadApe 
@blakekjohnson 

and much appreciated if you two could keep me posted

**Comment by sbwcwso** [comment]
> @MadApe @blakekjohnson
> 
> and much appreciated if you two could keep me posted

I also had the same problem, if you have a solution now？

**Comment by blakekjohnson** [comment]
`onDemandCourseMaterials.v2` is functionally the same as v1, a simple update of the version number would resolve the issue. Adding `_V2` to the end of the variable on [this line](https://github.com/coursera-dl/coursera-dl/blob/10ba6b8d8c30798a45d45db2dc147edf3b455350/coursera/api.py#L318) will resolve the aforementioned issues.

**Comment by sbwcwso** [comment]
> `onDemandCourseMaterials.v2` is functionally the same as v1, a simple update of the version number would resolve the issue. Adding `_V2` to the end of the variable on [this line](https://github.com/coursera-dl/coursera-dl/blob/10ba6b8d8c30798a45d45db2dc147edf3b455350/coursera/api.py#L318) will resolve the aforementioned issues.

When I changed line , I have the error below,  is this a problem of my python version, I am using Python 3.10.7 now.

```
❯ ./coursera-dl build-a-computer
/home/lijunjie/Downloads/coursera-dl/coursera/api.py:948: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if extension is '':
/home/lijunjie/Downloads/coursera-dl/coursera/api.py:1593: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if extension is '':
coursera_dl version 0.11.5
Downloading class: build-a-computer (1 / 1)
Parsing syllabus of on-demand course (id=ct7G8DVLEeWfzhKP8GtZlQ). This may take some time, please be patient ...
Processing module  introduction
Processing section     introduction
Processing lecture         module-0-introduction-roadmap (supplement)
Traceback (most recent call last):
  File "/home/lijunjie/Downloads/coursera-dl/./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/lijunjie/Downloads/coursera-dl/coursera/coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "/home/lijunjie/Downloads/coursera-dl/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/home/lijunjie/Downloads/coursera-dl/coursera/coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "/home/lijunjie/Downloads/coursera-dl/coursera/extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "/home/lijunjie/Downloads/coursera-dl/coursera/extractors.py", line 161, in _parse_on_demand_syllabus
    links = course.extract_links_from_supplement(
  File "/home/lijunjie/Downloads/coursera-dl/coursera/api.py", line 1268, in extract_links_from_supplement
    supplement_content, self._extract_links_from_text(value))
  File "/home/lijunjie/Downloads/coursera-dl/coursera/api.py", line 1518, in _extract_links_from_text
    supplement_links = self._extract_links_from_a_tags_in_text(text)
  File "/home/lijunjie/Downloads/coursera-dl/coursera/api.py", line 1597, in _extract_links_from_a_tags_in_text
    extension = clean_filename(
  File "/home/lijunjie/Downloads/coursera-dl/coursera/utils.py", line 118, in clean_filename
    s = h.unescape(s)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

**Comment by zacsyuan** [comment]
@sbwcwso  I dont have your issue 

but other than adding _V2 as @blakekjohnson points out, I also edited the name down below to align the version name.

works for me now... again @blakekjohnson  much appreciated....I dont think we would ever figure out without your note

![image](https://user-images.githubusercontent.com/117028237/199140373-c3858286-a5df-4289-a03e-1d918f38d899.png)

**Comment by olawalejuwonm** [comment]
> @sbwcwso I dont have your issue
> 
> but other than adding _V2 as @blakekjohnson points out, I also edited the name down below to align the version name.
> 
> works for me now... again @blakekjohnson much appreciated....I dont think we would ever figure out without your note
> 
> ![image](https://user-images.githubusercontent.com/117028237/199140373-c3858286-a5df-4289-a03e-1d918f38d899.png)

Thank you so much, this worked

**Comment by kmp8072** [comment]
> Hello, at Coursera we are in the process of deprecating the `onDemandCourseMaterials.v1` endpoint. When looking for usages of this API we found it used externally [here](https://github.com/coursera-dl/coursera-dl/blob/10ba6b8d8c30798a45d45db2dc147edf3b455350/coursera/api.py#L318) and wanted to notify the project owners that this endpoint will soon have traffic shut off. The `onDemandCourseMaterials.v2` endpoint can serve as an alternative to `onDemandCourseMaterial.v1`

Thanks for this solution. Life saver.

**Comment by loky777** [comment]
Im a beginner programmer it is hard for me to solve the issue as mentioned above , any clear descriptions of steps would be appreciated :)

**Comment by raffaelemancuso** [comment]
I pushed these changes in [my fork](https://github.com/raffaem/coursera-dl)

**Comment by SyedUmairHassanKazmi** [comment]
how do i install this forked library using pip?

**Comment by raffaelemancuso** [comment]
> how do i install this forked library using pip?

```
pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .
```

**Comment by SadaFalah** [comment]
Worked like magic thank you so much

**Comment by loky777** [comment]
@raffaem   been waiting for this for past 2 weeks, thanks a lot :)

**Comment by warren-ch** [comment]
It perfectly worked!  :0
Thx very much! life safer!!

**Comment by ghost** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

Thanks! work for me.

**Comment by ahmmishkat** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

Thanks a lot.

**Comment by rallantan** [comment]
Hello,

How do i install this forked library using pip?

I uninstall  using this command prompt           pip3 uninstall coursera-dl

The coursera got uninstalled but after that when I typed            git clone https://github.com/raffaem/coursera-dl

It  says 'git' is not recognized as an internal or external command,
operable program or batch file.

Can someone help me how to follow the below command step by step pls

pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .


Request you pls help me

**Comment by raffaelemancuso** [comment]
@rallantan you need to install git [from here](https://git-scm.com/)

**Comment by raffaelemancuso** [comment]
@rallantan you can also go [to the repo](https://github.com/raffaem/coursera-dl) and click on Code->Download ZIP

**Comment by rallantan** [comment]
Dear Rraffaem,

Thanks for your response,let me tell you I am not a tech savy person,I still learning.

I have installed git from https://git-scm.com/

I have downloaded the  Code->Download ZIP, I have downloaded the file.

I dont know what to do next can you help me.I need coursera courses for my professional life.Pls help me

**Comment by raffaelemancuso** [comment]
> Dear Rraffaem,
> 
> Thanks for your response,let me tell you I am not a tech savy person,I still learning.
> 
> I have installed git from https://git-scm.com/
> 
> I have downloaded the Code->Download ZIP, I have downloaded the file.
> 
> I dont know what to do next can you help me.I need coursera courses for my professional life.Pls help me

If you now have git, you can follow [these instructions](https://github.com/coursera-dl/coursera-dl/issues/834#issuecomment-1314392270)

**Comment by rallantan** [comment]
Sorry to say,I still didnot understand the steps.

**Comment by rallantan** [comment]
Pls help me

I have installed git from https://git-scm.com/

I finished this step -----------  git clone https://github.com/raffaem/coursera-dl

I went to the cd coursera-dl

When I enter pip3 install it gives me a error message -----ERROR: You must give at least one requirement to install (see "pip help install") 

I upgraded the pip with this command pip install --upgrade pip 

 It says -----  Requirement already satisfied: pip in c:\users\rajal\appdata\local\programs\python\python311\lib\site-packages (22.3.1)

I am stuck now pls help me

**Comment by raffaelemancuso** [comment]
> Pls help me
> 
> I have installed git from https://git-scm.com/
> 
> I finished this step ----------- git clone https://github.com/raffaem/coursera-dl
> 
> I went to the cd coursera-dl
> 
> When I enter pip3 install it gives me a error message -----ERROR: You must give at least one requirement to install (see "pip help install")
> 
> I upgraded the pip with this command pip install --upgrade pip
> 
> It says ----- Requirement already satisfied: pip in c:\users\rajal\appdata\local\programs\python\python311\lib\site-packages (22.3.1)
> 
> I am stuck now pls help me

The command is

```
pip3 install .
```
not 
```
pip3 install
```
The dot is important.

Don't neglect the dot.

Welcome the dot in your life, and good things will happen.

**Comment by rallantan** [comment]
Thank you sir,It perfectly worked.

Thanks for the good advice.

**Comment by anny-soft** [comment]
Hello,
I'm working on Ubuntu 20.04
Python 3.8.10
I type :~/my-coursera$ coursera-dl initiation-programmation-cpp
And i have that:
coursera_dl version 0.11.5
Downloading class: initiation-programmation-cpp (1 / 1)
Parsing syllabus of on-demand course (id=zRR1L_KfEeWUoA51NO3YLQ). This may take some time, please be patient ...
Error 404 Client Error: Not Found for url: https://api.coursera.org/api/onDemandCourseMaterials.v1/?q=slug&slug=initiation-programmation-cpp&includes=moduleIds%2ClessonIds%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2CitemIds%2Ctracks&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight)%2ConDemandCourseMaterialItems.v1(name%2Cslug%2CtimeCommitment%2Ccontent%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v1/?q=slug&slug=initiation-programmation-cpp&includes=moduleIds%2ClessonIds%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2CitemIds%2Ctracks&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight)%2ConDemandCourseMaterialItems.v1(name%2Cslug%2CtimeCommitment%2Ccontent%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
The server replied: <html>
	<head>
		<title>Coursera - API Route Does Not Exist</title>
	</head>
	<body style="background-color:#e4e4e4">
		<div style="position:absolute; top:0; bottom:0; left:0; right:0; margin:auto; height:200px; width: 600px">
			<div style="text-align:center">
				<img src="https://s3.amazonaws.com/coursera/error_pages/coursera-logo.svg" width="400">
			</div>
			<h1 style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:100; color: #555">
				API Route Does Not Exist
			</h1>
			<div style="text-align:center; font-family:Helvetica, Arial, sans-serif; font-weight:300; font-size:13pt; color: #555">
				Edge does not know about this API route. <br>
				Check whether this route is exposed in the routing table.
			</div>
		</div>
	</body>
</html>
HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/onDemandCourseMaterials.v1/?q=slug&slug=initiation-programmation-cpp&includes=moduleIds%2ClessonIds%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2CitemIds%2Ctracks&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight)%2ConDemandCourseMaterialItems.v1(name%2Cslug%2CtimeCommitment%2Ccontent%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
PLEASE i need help to fix that error

**Comment by koluantic** [comment]
@blakekjohnson and @raffaem thank you so much...cheers!!!

**Comment by anny-soft** [comment]
It's ok with python 3.9  :)
Thank you all

**Comment by DevMachTech** [comment]
> 

Please, have you been able to solve this

**Comment by IMJoeyZhu** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

This saved my life!! 
Thanks a lot!! And Thank you all.

**Comment by IMJoeyZhu** [comment]
> 

Thanks a lot! This is really helpful!

**Comment by IMJoeyZhu** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

Thanks a lot! This works for me!

**Comment by lsimone** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

thanks! <3 
Worked for mee too!

**Comment by olawalejuwonm** [comment]
> I pushed these changes in [my fork](https://github.com/raffaem/coursera-dl)

How do i use your fork?

**Comment by raffaelemancuso** [comment]
> > I pushed these changes in [my fork](https://github.com/raffaem/coursera-dl)
> 
> How do i use your fork?

```
pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .
```

The dot in the last command is important.

**Comment by khrnchn** [comment]
> > > I pushed these changes in [my fork](https://github.com/raffaem/coursera-dl)
> > 
> > 
> > How do i use your fork?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```
> 
> The dot in the last command is important.

hi, same error still occurs after i did the commands you gave :c

**Comment by sebastianelsner** [comment]
The repo mentioned above worked for me: https://github.com/raffaem/coursera-dl

```
pip uninstall coursera-dl
pip install git+https://github.com/raffaem/coursera-dl.git
coursera-dl -u YOURUSER -p YOURPASSWORD -ca YOURCA YOURSPECIALIZATION
```

**Comment by CRMH3** [comment]
> > Pls help me
> > I have installed git from https://git-scm.com/
> > I finished this step ----------- git clone https://github.com/raffaem/coursera-dl
> > I went to the cd coursera-dl
> > When I enter pip3 install it gives me a error message -----ERROR: You must give at least one requirement to install (see "pip help install")
> > I upgraded the pip with this command pip install --upgrade pip
> > It says ----- Requirement already satisfied: pip in c:\users\rajal\appdata\local\programs\python\python311\lib\site-packages (22.3.1)
> > I am stuck now pls help me
> 
> The command is
> 
> ```
> pip3 install .
> ```
> 
> not
> 
> ```
> pip3 install
> ```
> 
> The dot is important.
> 
> Don't neglect the dot.
> 
> Welcome the dot in your life, and good things will happen.

Thank you so much! You are so patient and nice

**Comment by justontyme** [comment]
I have done the following 
pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .

But how do I run the commands now?  When I enter something like "coursera-dl -h" it says no command found.  In the original version when I did that, it would display the help

**Comment by thetenthousandthings** [comment]
Works great! You rock! Thank you so much for this.

**Comment by raffaelemancuso** [comment]
> I have done the following pip3 uninstall coursera-dl git clone https://github.com/raffaem/coursera-dl cd coursera-dl pip3 install .
> 
> But how do I run the commands now? When I enter something like "coursera-dl -h" it says no command found. In the original version when I did that, it would display the help

I renamed my fork. Check the README for the correct command to run.

Please post questions about my fork on my fork. This is the original fork.

**Comment by gothamnight** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```
i followed your instructions but now it's tell me :
command not found: coursera-dl

**Comment by gothamnight** [comment]
> > > how do i install this forked library using pip?
> > 
> > 
> > ```
> > pip3 uninstall coursera-dl
> > git clone https://github.com/raffaem/coursera-dl
> > cd coursera-dl
> > pip3 install .
> > ```
> 
> i followed your instructions but now it's tell me : command not found: coursera-dl

don't worry I've found my way around the problem and it worked.
what I did was substitute the command "coursera-dl" with "cs-dlp" and it worked just fine. THANKS!

**Comment by UpalkKazi** [comment]
> > > > how do i install this forked library using pip?
> > > 
> > > 
> > > ```
> > > pip3 uninstall coursera-dl
> > > git clone https://github.com/raffaem/coursera-dl
> > > cd coursera-dl
> > > pip3 install .
> > > ```
> > 
> > 
> > i followed your instructions but now it's tell me : command not found: coursera-dl
> 
> don't worry I've found my way around the problem and it worked. what I did was substitute the command "coursera-dl" with "cs-dlp" and it worked just fine. THANKS!

This is the best suggestion

**Comment by AndreyBaum** [comment]
**'cs-dlp' is not recognized as an internal or external command, operable program or batch file.**
I am writing a command in the folder where I created the coursera-dl folder, but this error comes out


UPD: _It doesn't matter anymore. I just wrote all the commands through PowerShell, not through cmd, and everything worked_

**Comment by AndreyBaum** [comment]
> 

It doesn't matter anymore. I just wrote all the commands through PowerShell, not through cmd, and everything worked

**Comment by gabi271** [comment]
After completing the 4 steps, I get the message "coursera-dl is not recognized as a command", the four steps were completed without problems

**Comment by stevienovak** [comment]
Hello Rraffaem,

Thanks for the above code! I have been using it for two months and it works like a gem but I am receiving a 403 error now. 

The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=siads532&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true

The last I used cs-dlp was on 15 Sep! Possible to advise what I should do to solve the above issue? thx!

Update on 26 Sep
I solved the problem! There was an update to my CAUTH. I changed it and the script works like a gem. thanks for the script! its a Life Saver

**Comment by inayatiphone619** [comment]
> > > > > how do i install this forked library using pip?
> > > > 
> > > > 
> > > > ```
> > > > pip3 uninstall coursera-dl
> > > > git clone https://github.com/raffaem/coursera-dl
> > > > cd coursera-dl
> > > > pip3 install .
> > > > ```
> > > 
> > > 
> > > i followed your instructions but now it's tell me : command not found: coursera-dl
> > 
> > 
> > don't worry I've found my way around the problem and it worked. what I did was substitute the command "coursera-dl" with "cs-dlp" and it worked just fine. THANKS!
> 
> This is the best suggestion

Thank you so much, 
I have cloned but getting following warning WARNING: The script cs-dlp.exe is installed in 'C:\Users\Commissioner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cs-dlp-0.12.0b0

and when i run coursera-dl  it is also not reconginized can anyone help me please

**Comment by a1timothy** [comment]
Fault on install:
_building 'lz4._version' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/_

Installing C++ as advised does not help. **Any ideas for a cure?**

**Comment by ellyturla** [comment]
> > how do i install this forked library using pip?
> 
> ```
> pip3 uninstall coursera-dl
> git clone https://github.com/raffaem/coursera-dl
> cd coursera-dl
> pip3 install .
> ```

its work. thanks

**Comment by Ananyaa32** [comment]
Hello All,

I am not a technical person pls help me.

I have installed git from https://git-scm.com/

I have done all the below steps :-

pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .


Now in the CMD prompt what should type to download the Coursera course pls help me 

Pls share the command which I need to follow. Pls help me 

I dont know how to download the Coursera course pls help me

**Comment by Ananyaa32** [comment]
Hello raffaem

Can you pls help me pls

**Comment by zasid** [comment]
Step by Step process

follow this page and steps

open windows explorer

open c drive

type cmd in the bar above 

goto this page and follow the steps

https://github.com/coursera-dl/coursera-dl/issues/834

pip3 uninstall coursera-dl
git clone https://github.com/raffaem/coursera-dl
cd coursera-dl
pip3 install .


make sure you are in this folder c:\coursers-dl> 

then

type this command 


c:\coursers-dl>cs-dlp -ca Copy the date you copied from the coursera authentication extension COURSENAME->Replace this with the course link you copied from course see below youtube video how to do that


get extension for coursera cookie copy from here 
It's available here on Github as well: https://github.com/e-learning-archive/browser-extension

https://www.youtube.com/watch?v=fDCln4C0zbI --->copy this video before they remove it for violations.

I just followed these steps and it works 1000%

**Comment by zacsyuan** [comment]
I was using it yesterday. and.it worked...make sure you get the right auth
by right clicking inspection. if not the issue with auth, go thru the codes
again.

zasid ***@***.***> 于2024年9月29日周日 13:58写道：

**Comment by zasid** [comment]
I got this working finally after alot of hard work. Thanks.
________________________________

**Comment by ryanchase0to1** [comment]
> > > > how do i install this forked library using pip?
> > > 
> > > 
> > > ```
> > > pip3 uninstall coursera-dl
> > > git clone https://github.com/raffaem/coursera-dl
> > > cd coursera-dl
> > > pip3 install .
> > > ```
> > 
> > 
> > i followed your instructions but now it's tell me : command not found: coursera-dl
> 
> don't worry I've found my way around the problem and it worked. what I did was substitute the command "coursera-dl" with "cs-dlp" and it worked just fine. THANKS!

this is because the name of raffaem's forked repo changed from "coursera-dl" to "cs-dlp"... see for yourself: 
https://github.com/raffaem/coursera-dl.  So the new command will be `cs-dlp`, not `coursera-dl` (after running `pip install .` of course)
