### ISSUE TITLE
 Issue with coursera-dl: Error 400 Client Error: Bad Request

### ISSUE THREAD

**Issue by Omar-Shams-98** [coursera-dl/coursera-dl#852]
When attempting to download the "learning-how-to-learn" course from Coursera, I executed the following command in the command prompt:

`coursera-dl -u oshideo9805@gmail.com learning-how-to-learn`

After entering my Coursera account password as prompted, I received the following error message:

`coursera_dl version 0.11.5
Traceback (most recent call last):
  File "...coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "...requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...coursera-dl.exe\__main__.py", line 7, in <module>
  File "...coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "...coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3`

I'm using Microsoft Windows version 10.0.19045.2965, and the coursera-dl version is 0.11.5. What can I do to solve this problem?

**Comment by ArbenP** [comment]
I am also getting that error, also on windows 10, with my command being `coursera-dl -u MAIL@outlook.com -p MYPASSWORD foundations-of-cybersecurity`

**Comment by ArbenP** [comment]
I resolved the issue by switching to this fork: https://github.com/raffaem/cs-dlp works perfectly

**Comment by port19x** [comment]
Also having the issue

**Comment by ryanchase0to1** [comment]
Everyone is now using this forked version of the original coursera-dl repo which works: https://github.com/raffaem/cs-dlp.
Essentially, Coursera deprecated the API endpoint onDemandCourseMaterials.v1 - see https://github.com/coursera-dl/coursera-dl/issues/834, and didn't update the code for coursera-dl...But if you read the comments there and here https://github.com/coursera-dl/coursera-dl/issues/835, you'll see that everyone is now using this forked repo, and it's working for them.  Note that the command will be `cs-dlp` instead of `coursera-dl`.  Also, you have to run `pip install .` (with the period) after you `git clone https://github.com/raffaem/cs-dlp` and cd into the cs-dsp directory in order to use the `cs-dlp` command.

**Comment by radoygeorgiev** [comment]
Is this repo available anywhere else ? it doesn't seem like it is still active  https://github.com/raffaem/cs-dlp
