### ISSUE TITLE
Not working with latest python versions

### ISSUE THREAD

**Issue by yuvalbeck** [coursera-dl/coursera-dl#854]
Can anyone update the packages in the requirements to support newer versions of python many were deleted?
Thank you

**Comment by theawesomeharris** [comment]
yo man i think the package has gone obsolete.

**Comment by csyezheng** [comment]
I forked the repository and fixed it to a working version: https://github.com/csyezheng/coursera-helper

You can install it using the command:
`pip install coursera-helper`

**Comment by fasonche** [comment]
> I forked the repository and fixed it to a working version: https://github.com/csyezheng/coursera-helper
> 
> You can install it using the command: `pip install coursera-helper`
@csyezheng 
Hello, I am using [coursera-helper](https://github.com/csyezheng/coursera-helper) trying to download
and get these errors.
Could you give me some advise to how to fix it?
-----
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fason\AppData\Roaming\Python\Python310\Scripts\coursera-helper.exe\__main__.py", line 7, in <module>
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\coursera_dl.py", line 256, in main
    error_occurred, completed = download_class(
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\coursera_dl.py", line 216, in download_class
    return download_on_demand_class(session, args, class_name)
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\coursera_dl.py", line 136, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\extractors.py", line 155, in _parse_on_demand_syllabus
    links = course.extract_links_from_lecture(
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\api.py", line 881, in extract_links_from_lecture
    links = self._extract_videos_and_subtitles_from_lecture(
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\api.py", line 1045, in _extract_videos_and_subtitles_from_lecture
    videos = VideosV1.from_json(dom)
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\api.py", line 524, in from_json
    videos = [VideoV1(resolution, links['mp4VideoUrl'])
  File "C:\Users\fason\AppData\Roaming\Python\Python310\site-packages\coursera_helper\api.py", line 524, in <listcomp>
    videos = [VideoV1(resolution, links['mp4VideoUrl'])
KeyError: 'mp4VideoUrl'

**Comment by csyezheng** [comment]
@fasonche 

What is the course that you are trying to access?
Have you tried downloading other courses and are you getting the same error?
The information you gave is too little. I can't reproduce the same error, so I can't solve the problem. 
Tell me how to reproduce this issue, so that you can help me help you.

**Comment by fasonche** [comment]
@csyezheng 

I'm very sorry for not being more careful with the instructions.
I retried my old courses, it work great. Thanks so much.
Just do not work on this course: [generative-ai-for-everyone](https://www.coursera.org/learn/generative-ai-for-everyone/home/week/1)
Thank you.

**Comment by csyezheng** [comment]
@fasonche 

This bug has been fixed in version 0.12.2.
Please upgrade coursera-helper by running:
```
python -m pip install --upgrade --index-url https://pypi.org/simple/ coursera-helper
```
Make sure you upgrade to the correct version by running:
```
coursera-helper --version
```

**Comment by fasonche** [comment]
@csyezheng 

I can download it now!
Thank you very much for the help.

**Comment by Satheshkumar-A** [comment]
Guys please help me on this how to download by giving the steps versions and if changes any...

This will be more helpful for me to download....I tried everything but all ended in error
