### ISSUE TITLE
Json Decoder error

### ISSUE THREAD

**Issue by kabib4231** [coursera-dl/coursera-dl#868]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

json decoder eroor 
### Your environment
* Operating System (Windows11/23H2):
* Python version: Python 3.12.6
* coursera-dl version:0.11.5

### Steps to reproduce
just after doing the normal download commads , like give username ,password,CAuth and course name i get this { json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) } error

### Actual behaviour
![image](https://github.com/user-attachments/assets/f4fe9575-a639-4ee7-9d26-ca815a0c30c4)

**Comment by rawsalt** [comment]
i used this pr: https://github.com/coursera-dl/coursera-dl/pull/863 with this additional change: https://github.com/coursera-dl/coursera-dl/pull/863#discussion_r1781591080
and it works now. The coursera Api changed

fork with changes https://github.com/rawsalt/coursera-dl

**Comment by kabib4231** [comment]
error still persistent !

**Comment by kabib4231** [comment]
Works now , thank you

**Comment by q-serghio** [comment]
> i used this pr: #863 with this additional change: [#863 (comment)](https://github.com/coursera-dl/coursera-dl/pull/863#discussion_r1781591080) and it works now. The coursera Api changed
> 
> fork with changes https://github.com/rawsalt/coursera-dl

It works like a charm! For those that start their journey with this repository you have to get this PR, get CAUTH from Dev Tools in the Cookie, and download course with -ca "some_long_string"

**Comment by whisperingkahuna** [comment]
> i used this pr: #863 with this additional change: [#863 (comment)](https://github.com/coursera-dl/coursera-dl/pull/863#discussion_r1781591080) and it works now. The coursera Api changed
> 
> fork with changes https://github.com/rawsalt/coursera-dl

Works for me, thanks for making it easy for us all!

**Comment by whisperingkahuna** [comment]
> i used this pr: #863 with this additional change: [#863 (comment)](https://github.com/coursera-dl/coursera-dl/pull/863#discussion_r1781591080) and it works now. The coursera Api changed
> 
> fork with changes https://github.com/rawsalt/coursera-dl

It works fine, but it gets stuck while downloading HTML files, I share a snippet


```
Downloading https://business.adobe.com/products/analytics/adobe-analytics.html -> make-the-sale/01_introduction-to-make-the-sale-build-launch-and-manage-e-commerce-stores/03_terms-tools-and-strategies-in-e-commerce/02_learn-more-about-the-basics-of-e-commerce_adobe-analytics.html

AbstractDownloader: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/coursera-dl/coursera/parallel.py", line 32, in _download_wrapper
    return url, self._file_downloader.download(url, *args, **kwargs)
  File "/content/coursera-dl/coursera/downloaders.py", line 54, in download
    self._start_download(url, filename, resume)
  File "/content/coursera-dl/coursera/downloaders.py", line 329, in _start_download
    r = self.session.get(url, stream=True, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

The following error has occurred while downloading URL https://business.adobe.com/products/analytics/adobe-analytics.html: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Downloading: make-the-sale/01_introduction-to-make-the-sale-build-launch-and-manage-e-commerce-stores/03_terms-tools-and-strategies-in-e-commerce/02_learn-more-about-the-basics-of-e-commerce_open-source.html
Downloading https://business.adobe.com/products/magento/open-source.html -> make-the-sale/01_introduction-to-make-the-sale-build-launch-and-manage-e-commerce-stores/03_terms-tools-and-strategies-in-e-commerce/02_learn-more-about-the-basics-of-e-commerce_open-source.html

```
Could you modify the code further?
Thanks again!
