### ISSUE TITLE
Error logging in?

### ISSUE THREAD

**Issue by max1000000** [coursera-dl/coursera-dl#870]
🚨Please review the [Troubleshooting](../#troubleshooting) section
before reporting any issue. Don't forget to check also the current issues to
avoid duplicates.

### Subject of the issue
Describe your issue here. 

Error logging in. I have checked the user name and password.

### Your environment
* Operating System (name/version): Windows 11 Pro/24H2
* Python version: 3.10.13
* coursera-dl version: 0.11.5

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you: 

I'm running the line:
coursera-dl -u max1@maxb.com -p *********** microsoft-365-copilot

* Is the problem happening with the latest version of the script? Yes
* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`. Yes
* What is the course that you are trying to access? microsoft-365-copilot
* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

coursera-dl -u max1@maxb.com -p *********** microsoft-365-copilot

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

root[main] coursera_dl version 0.11.5
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=O1EpubuWwzmrssckhgE6; csrf2_token_iL7YDFON=K4CxdcbbdQtRh99dy48ENLkW.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/11" 400 None
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Anaconda\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda\lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "C:\Anaconda\lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)

### Expected behaviour
Tell us what should happen.

It should download the files

### Actual behaviour
Tell us what happens instead. If the script fails, please copy the *entire*
output of the command or the stacktrace (don't forget to obfuscate your
username and password). If you cannot copy the exception, attach a screenshot.

I get the error message above

**Comment by heartInsert** [comment]
Have  you solve it ?  Or  you  find  another repository  to  download  cousera ?

**Comment by max1000000** [comment]
I've had no response from the developers here on how to solve this unfortunately.

**Comment by vipercortex** [comment]
same problem as above.
installed with "pip install coursera-dl" on Windows 11
Python 3.12.4 (WinPython)
login credentials work to log in to Coursera and I am able to download the videos from the Downloads tab by right-clicking them and saving them manually.

Here is the output I get:

coursera_dl version 0.11.5
Traceback (most recent call last):
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\WPy64-31241\python-3.12.4.amd64\Scripts\coursera-dl.exe\__main__.py", line 7, in <module>
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

**Comment by vipercortex** [comment]
The coursera login url seems to have changed. it is now "'https://www.coursera.org/?authMode=login'"
In define.py, I changed line 17 to:
AUTH_URL_V3 = 'https://www.coursera.org/?authMode=login'

With the --debug option, I now get the following output:

root[main] coursera_dl version 0.11.5
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=aPMVHmuBVu5mUPH5NSVt; csrf2_token_2cG3iRNY=1hlFHKoHmNAgp5QEFLhTLrTl.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): www.coursera.org:443
urllib3.connectionpool[_make_request] https://www.coursera.org:443 "POST /?authMode=login HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\DATA\__PRJ\downloadCoursera\coursera-dl\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\DATA\__PRJ\downloadCoursera\coursera-dl\coursera\coursera_dl.py", line 239, in main
    login(session, args.username, args.password)
  File "C:\DATA\__PRJ\downloadCoursera\coursera-dl\coursera\cookies.py", line 152, in login
    v = session.cookies.pop('CAUTH')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 945, in pop
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\requests\cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\WPy64-31241\python-3.12.4.amd64\Lib\site-packages\requests\cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='CAUTH', domain=None, path=None"
